### ISSUE TITLE
Cannot SendSendMedia

### ISSUE THREAD

**Issue by yovantya** [gram-js/gramjs#100]
Hai
Please help me
I can't SendMedia

here's the error

(node:11228) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'name' of 'file' as it is undefined.
    at Object.<anonymous> (D:\NodeJS\Tele\node_modules\telegram\client\uploads.js:38:17)
    at Generator.next (<anonymous>)
    at D:\NodeJS\Tele\node_modules\telegram\client\uploads.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\NodeJS\Tele\node_modules\telegram\client\uploads.js:4:12)
    at Object.uploadFile (D:\NodeJS\Tele\node_modules\telegram\client\uploads.js:35:12)
    at TelegramClient.uploadFile (D:\NodeJS\Tele\node_modules\telegram\client\TelegramClient.js:193:30)
    at run (D:\NodeJS\Tele\app.js:21:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
![1](https://user-images.githubusercontent.com/49070576/122551815-b3168480-d05f-11eb-926a-1755803598b2.JPG)
![2](https://user-images.githubusercontent.com/49070576/122551830-b6aa0b80-d05f-11eb-8e9a-1f2a56802dde.JPG)

**Comment by painor** [comment]
if you want to use `uploadFile` you need to use the `CustomFile` class.
you can also just use `sendFile`
https://painor.gitbook.io/gramjs/getting-started/available-methods/uploading-files-1

**Comment by yovantya** [comment]
can you give an example if i want to send a file  ?



thanks a lot

**Comment by painor** [comment]
> can you give an example if i want to send a file ?
> 
> thanks a lot

The link I sent you has an example.

**Comment by Mr-Jmail** [comment]
there is a correct code for me:
client.sendFile("me", {file: ["./picture.jpg", "./picture2.jpg"]})

**Comment by ljs19923** [comment]
@painor CustomFile is undefined for me... how to define it? Thanks a lot
<img width="402" alt="Screen Shot 2022-12-15 at 11 47 05" src="https://user-images.githubusercontent.com/5727223/207767877-52e4b4d9-9ef5-4072-98db-1771d1781ac3.png">
