### ISSUE TITLE
getParticipants pagination not working

### ISSUE THREAD

**Issue by heldersepu** [gram-js/gramjs#101]
According to the documentation offset should be available on getParticipants
  https://core.telegram.org/api/offsets

but on code:
https://github.com/gram-js/gramjs/blob/master/gramjs/client/TelegramClient.ts#L740-L745

```
    getParticipants(
        entity: EntityLike,
        params: chatMethods.IterParticipantsParams
    ) {
        return chatMethods.getParticipants(this, entity, params);
    }
```
Let's look at that `params chatMethods.IterParticipantsParams`
https://github.com/gram-js/gramjs/blob/master/gramjs/client/chats.ts#L397-L404

```
export interface IterParticipantsParams {
    /** how many members to retrieve. defaults to Number.MAX_SAFE_INTEGER (everyone) */
    limit?: number;
    /** a query string to filter participants based on their display names and usernames. defaults to "" (everyone) */
    search?: string;
    /** optional filter to be used. E.g only admins filter or only banned members filter. PS : some filters need more permissions. */
    filter?: Api.TypeChannelParticipantsFilter;
}
```

we have not implemented offset?!?!?!

**Comment by heldersepu** [comment]
I tried with a very large limit and it only max out at: 10001

**Comment by heldersepu** [comment]
https://github.com/gram-js/gramjs/blob/3f243268f2f41d39d24c5cece9c698a06719d34b/gramjs/client/chats.ts#L407-L422

**Comment by painor** [comment]
What are you trying to do? why do you want to access the offset ?

**Comment by heldersepu** [comment]
> y do you want to access the offset


> What are you trying to do? why do you want to access the offset ?

I'm trying to get all participants on: https://t.me/idexo_io
...we created a bot that allows users to mint NFT's, those are proof that they have been early adopters of our project, and they can receive rewards like participating in out private token sale, but they must be the in thegroup, if they leave they loose privileges

**Comment by painor** [comment]
getParticipants returns a list of all 20K users in that group. and it takes a while to do so. it's not recommended to use it for that. if you want to check if a single user is present in a group you should use the following : https://gram.js.org/tl/channels/GetParticipant

**Comment by heldersepu** [comment]
> getParticipants returns a list of all 20K users in that group. and it takes a while to do so. it's not recommended to use it for that. if you want to check if a single user is present in a group you should use the following : https://gram.js.org/tl/channels/GetParticipant

No it does not, I tried with large values on the limit and it max on 10001

**Comment by painor** [comment]
oh yes the limit of groups is 10K and for channels is 200. that's the telegram set by telegram. they will not return any more. 
The function getParticipants uses offset internally to get as much as it can.

**Comment by heldersepu** [comment]
> The function getParticipants uses offset internally to get as much as it can.

It is not returning anything beyond the 10K ...
and no the `channels/GetParticipant` is not an optimal solution, with that we are moving from making one call to making thousands

**Comment by painor** [comment]
anyways, if you want to use offset yourself you can try the RAW API https://gram.js.org/tl/channels/GetParticipants but you're not gonna get anything more than 10K without tricks.

**Comment by heldersepu** [comment]
That really sucks...
