### ISSUE TITLE
sendMessage - Could not find the input entity for ${peer}

### ISSUE THREAD

**Issue by banghasan** [gram-js/gramjs#105]
Work:

```javascript
let result = await client.invoke(
        new Api.messages.SendMessage({
            peer: 'username',
            message: 'hello'
        })
    )
    console.log(result);
```
if `peer` is a number, which is chat_id :  

```javascript
let result = await client.invoke(
        new Api.messages.SendMessage({
            peer: 123456789,
            message: 'hello'
        })
    )
    console.log(result);
```

got error: 
```
throw new Error(`Could not find the input entity for ${peer}.

Error: Could not find the input entity for [object Object].
```

Any solution?

**Comment by butthx** [comment]
I have a little solution for you and others if experiencing the same thing. This error trowing if i using userbot with gramjs and this is the method i use to solve it: 

Save the userbot contact in your main account and save your main contact in yout userbot account.

If still not working try sendMessage to your main account from your userbot account via the telegram app.

I hope this help. :)

**Comment by painor** [comment]
if you want to send a message by ID the library needs to have "seen" that user before. either as a group member or a dialog or a username. you can't send by id if you've never seen it.

**Comment by arlekenon** [comment]
Still encountering this error, tell me how to make the library see the address where I want to send the message.

When I put userId there the message is sent, but when I put chatId the error appears.

**Comment by painor** [comment]
> Still encountering this error, tell me how to make the library see the address where I want to send the message.
> 
> When I put userId there the message is sent, but when I put chatId the error appears.

If you are using a bot then the bot need to be in that chat or has talked to that user before.
If you are using a user then you need to get that chat somehow either with an event being sent there (like a new message) or by getting all dialogs on startup (client.getDialogs())

**Comment by arlekenon** [comment]
I do through the user, added (client.getDialogs ()) and it worked.
Thanks!

An error popped up in the process:

function iterDialogs(client, { limit = undefined, offsetDate = undefined, offsetId = 0, offsetPeer = new tl_1.Api.InputPeerEmpty(), ignorePinned = false, ignoreMigrated = false, folder = undefined, archived = undefined, }) {
                               ^
TypeError: Cannot read property 'limit' of undefined

Specified the "limit" value and everything worked!

**Comment by painor** [comment]
> I do through the user, added (client.getDialogs ()) and it worked.
> Thanks!
> 
> An error popped up in the process:
> 
> function iterDialogs(client, { limit = undefined, offsetDate = undefined, offsetId = 0, offsetPeer = new tl_1.Api.InputPeerEmpty(), ignorePinned = false, ignoreMigrated = false, folder = undefined, archived = undefined, }) {
> ^
> TypeError: Cannot read property 'limit' of undefined
> 
> Specified the "limit" value and everything worked!

Great. I forgot to add the limit in the example I sent. Usually something like 100 or 50 is enough.
