### ISSUE TITLE
NewMessage (Event) - ReferenceError: NewMessage is not defined

### ISSUE THREAD

**Issue by itsMustafa** [gram-js/gramjs#106]
NewMessage event handler not working giving the following error:
    UnhandledPromiseRejectionWarning: ReferenceError: NewMessage is not defined

**Comment by butthx** [comment]
can you give me a little code when error appears?

**Comment by itsMustafa** [comment]
> can you give me a little code when error appears?

Im following the docs itself

```
async function eventPrint(event) {
    const message = event.message;

    // Checks if it's a private message (from user or bot)
    if (event.isPrivate){
        // prints sender id
        console.log(message.senderId);
        // read message
        if (message.text == "hello"){
            const sender = await message.getSender();
            console.log("sender is",sender);
            await client.sendMessage(sender,{
                message:`hi your id is ${message.senderId}`
            });
        }
    }
}
// adds an event handler for new messages
client.addEventHandler(eventPrint, new NewMessage({}));
```

**Comment by butthx** [comment]
> > can you give me a little code when error appears?
> 
> Im following the docs itself
> 
> ```
> async function eventPrint(event) {
>     const message = event.message;
> 
>     // Checks if it's a private message (from user or bot)
>     if (event.isPrivate){
>         // prints sender id
>         console.log(message.senderId);
>         // read message
>         if (message.text == "hello"){
>             const sender = await message.getSender();
>             console.log("sender is",sender);
>             await client.sendMessage(sender,{
>                 message:`hi your id is ${message.senderId}`
>             });
>         }
>     }
> }
> // adds an event handler for new messages
> client.addEventHandler(eventPrint, new NewMessage({}));
> ```

try this. 
```ts
import {TelegramClient} from 'telegram';
import {StringSession} from 'telegram/sessions';
import {NewMessage} from 'telegram/events';
import {NewMessageEvent} from 'telegram/events/NewMessage';
import {Message} from 'telegram/tl/custom/message';
import {Api} from "telegram"

async function eventPrint(event) {
    const message = event.message as Message;
    // Checks if it's a private message (from user or bot)
    if (event.isPrivate){
        // prints sender id
        console.log(message.senderId);
        // read message
        if (message.text == "hello"){
            const sender = await message.getSender();
            console.log("sender is",sender);
            await client.sendMessage(sender,{
                message:`hi your id is ${message.senderId}`
            });
        }
    }
}
// adds an event handler for new messages
client.addEventHandler(eventPrint, new NewMessage({}));

```

**Comment by itsMustafa** [comment]
> > > can you give me a little code when error appears?
> > 
> > 
> > Im following the docs itself
> > ```
> > async function eventPrint(event) {
> >     const message = event.message;
> > 
> >     // Checks if it's a private message (from user or bot)
> >     if (event.isPrivate){
> >         // prints sender id
> >         console.log(message.senderId);
> >         // read message
> >         if (message.text == "hello"){
> >             const sender = await message.getSender();
> >             console.log("sender is",sender);
> >             await client.sendMessage(sender,{
> >                 message:`hi your id is ${message.senderId}`
> >             });
> >         }
> >     }
> > }
> > // adds an event handler for new messages
> > client.addEventHandler(eventPrint, new NewMessage({}));
> > ```
> 
> try this.
> 
> ```ts
> import {TelegramClient} from 'telegram';
> import {StringSession} from 'telegram/sessions';
> import {NewMessage} from 'telegram/events';
> import {NewMessageEvent} from 'telegram/events/NewMessage';
> import {Message} from 'telegram/tl/custom/message';
> import {Api} from "telegram"
> 
> async function eventPrint(event:NewMessageEvent) {
>     const message = event.message as Message;
>     // Checks if it's a private message (from user or bot)
>     if (event.isPrivate){
>         // prints sender id
>         console.log(message.senderId);
>         // read message
>         if (message.text == "hello"){
>             const sender = await message.getSender();
>             console.log("sender is",sender);
>             await client.sendMessage(sender,{
>                 message:`hi your id is ${message.senderId}`
>             });
>         }
>     }
> }
> // adds an event handler for new messages
> client.addEventHandler(eventPrint, new NewMessage({}));
> ```

Hey thanks! it worked perfectly
I thought importing telegram is enough! my bad.

**Comment by butthx** [comment]
> > > > can you give me a little code when error appears?
> > > 
> > > 
> > > Im following the docs itself
> > > ```
> > > async function eventPrint(event) {
> > >     const message = event.message;
> > > 
> > >     // Checks if it's a private message (from user or bot)
> > >     if (event.isPrivate){
> > >         // prints sender id
> > >         console.log(message.senderId);
> > >         // read message
> > >         if (message.text == "hello"){
> > >             const sender = await message.getSender();
> > >             console.log("sender is",sender);
> > >             await client.sendMessage(sender,{
> > >                 message:`hi your id is ${message.senderId}`
> > >             });
> > >         }
> > >     }
> > > }
> > > // adds an event handler for new messages
> > > client.addEventHandler(eventPrint, new NewMessage({}));
> > > ```
> > 
> > 
> > try this.
> > ```ts
> > import {TelegramClient} from 'telegram';
> > import {StringSession} from 'telegram/sessions';
> > import {NewMessage} from 'telegram/events';
> > import {NewMessageEvent} from 'telegram/events/NewMessage';
> > import {Message} from 'telegram/tl/custom/message';
> > import {Api} from "telegram"
> > 
> > async function eventPrint(event:NewMessageEvent) {
> >     const message = event.message as Message;
> >     // Checks if it's a private message (from user or bot)
> >     if (event.isPrivate){
> >         // prints sender id
> >         console.log(message.senderId);
> >         // read message
> >         if (message.text == "hello"){
> >             const sender = await message.getSender();
> >             console.log("sender is",sender);
> >             await client.sendMessage(sender,{
> >                 message:`hi your id is ${message.senderId}`
> >             });
> >         }
> >     }
> > }
> > // adds an event handler for new messages
> > client.addEventHandler(eventPrint, new NewMessage({}));
> > ```
> 
> Hey thanks! it worked perfectly
> I thought importing telegram is enough! my bad.

Your welcome.
