### ISSUE TITLE
Faster listeners?

### ISSUE THREAD

**Issue by king-retracted** [gram-js/gramjs#108]
I use gramjs as something to listen to certain telegram channels and forward it to a discord webhook for more convivence since I use discord more than telegram.  What I have noticed is that the "listener" is a bit delayed unless that's an issue with discord webhooks, and if so, then I'll deal with it and figure something with discord webhooks. It is a small delay of like 1-5 seconds but it's still something.

**Comment by painor** [comment]
if it's a small channel the updates should be instant. you can print the `message.date` to see when telegram sent them vs what's the current date.

**Comment by king-retracted** [comment]
Sounds good. I'll use that for debug purposes and confirm that its a discord-webhook problem.
