### ISSUE TITLE
How to fix api.tl file in webpack

### ISSUE THREAD

**Issue by DricHao** [gram-js/gramjs#112]
**I use this lib in Vue-electron app, but here's an issue with webpack.**

 error  in ./node_modules/telegram/tl/static/schema.tl

Module parse failed: Unexpected character '#' (9:5)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| ///////////////////////////////
| 
> resPQ#05162463 nonce:int128 server_nonce:int128 pq:string server_public_key_fingerprints:Vector<long> = ResPQ;
| 
| p_q_inner_data#83c95aec pq:string p:string q:string nonce:int128 server_nonce:int128 new_nonce:int256 = P_Q_inner_data;

 @ ./node_modules/telegram/tl/api.js 26:20-49
 @ ./node_modules/telegram/tl/index.js
 @ ./node_modules/telegram/index.js
 @ ./scripts/telegram-api/regist.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.100:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by rojserbest** [comment]
i have the same issue, using React.js.

**Comment by painor** [comment]
use raw loader for that. https://github.com/gram-js/gramjs/blob/master/webpack.config.js#L23

**Comment by DricHao** [comment]
> use raw loader for that. https://github.com/gram-js/gramjs/blob/master/webpack.config.js#L23

Ty bro😊
