### ISSUE TITLE
RPCError: API_ID_INVALID

### ISSUE THREAD

**Issue by nasyarobby** [gram-js/gramjs#113]
I obtained api id and api hash...
Using ```npx tgession```, I entered the api id and hash but got the following error after I entered my phone number:

```
? API ID : 1234567
? API HASH : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
? Number : +62821123456789
RPCError: API_ID_INVALID
    at Object.RPCMessageToError (/home/nsrb/.npm/_npx/a24890428da1927f/node_modules/telegram/errors/index.js:24:12)
    at MTProtoSender._handleRPCResult (/home/nsrb/.npm/_npx/a24890428da1927f/node_modules/telegram/network/MTProtoSender.js:487:36)
    at MTProtoSender.<anonymous> (/home/nsrb/.npm/_npx/a24890428da1927f/node_modules/telegram/network/MTProtoSender.js:411:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/nsrb/.npm/_npx/a24890428da1927f/node_modules/telegram/network/MTProtoSender.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: undefined
}
```

I use other combinations for phone number (using +, without +, using 0 instead of country code) but it still got the same error.

I doubled checked my API ID and Hash is the same.

my package.json contains "telegram": "^1.7.15"

**Comment by painor** [comment]
well 1234567 is not a valid api id. 
The API ID is not a secret so you can share that if you wish (Don't share API hash tho)

**Comment by nasyarobby** [comment]
well it says in the telegram page it is forbidden to share app id to third party... So I thought it is a secret.

**Comment by painor** [comment]
> well it says in the telegram page (https://my.telegram.org/apps) it is forbidden to share app id to third party... So I thought it is a secret.
> 
> Is there any way to check if my app id is valid?

Not really but that error is coming from telegram so it's probably something else. Try using the normal way to create a session shown here https://painor.gitbook.io/gramjs/

**Comment by Asjas** [comment]
@painor I'm getting this same error message, I created a Telegram App about 4 hours ago and I'm now trying the example you linked to here https://painor.gitbook.io/gramjs/.

```js
import { TelegramClient } from "telegram";
import { StringSession } from "telegram/sessions/index.js";
import input from "input"; // npm i input

const apiId = 7967860;
const apiHash = "i have my api hashed filled in here";

const stringSession = new StringSession(""); // fill this later with the value from session.save()

(async () => {
  console.log("Loading interactive example...");

  const client = new TelegramClient(stringSession, apiId, apiHash, { connectionRetries: 5 });

  await client.start({
    phoneNumber: async () => await input.text("number ?"),
    password: async () => await input.text("password?"),
    phoneCode: async () => await input.text("Code ?"),
    onError: (err) => console.log(err),
  });

  console.log("You should now be connected.");
  console.log(client.session.save()); // Save this string to avoid logging in again

  await client.sendMessage("me", { message: "Hello!" });
})();
```
![API_ID](https://user-images.githubusercontent.com/3828967/125933095-409c8846-f99f-421e-a1e3-e7da12b034a2.png)
![API_ID_INVALID](https://user-images.githubusercontent.com/3828967/125933103-cc976df1-a3d1-4d4b-95ab-6a32bd04b04e.png)

**Comment by Asjas** [comment]
I'm mainly looking at getting this script up and running so that I can query a private channel to see if someone joined the channel or not. I created a telegram bot with the Telegraf npm package and the bot has a menu button that posts a link to join a Private Channel that we would like to hide if the user already joined the private channel.

So I basically need the ability to filter a private channel using a user's telegram ID to see if they are in a private channel or not.

I'm having an issue figuring out what I need to pass to GramJS to find users in a Private Channel, I have the Private Channel's ID but I don't know how to get the hash that is linked in the Telegram Docs. I keep getting `AUTH_KEY_UNREGISTERED` when I try to find users in a channel.

**Comment by painor** [comment]
If you want to know if a user is in a channel you should use https://gram.js.org/tl/channels/GetParticipant.
The reason for the `AUTH_KEY_UNREGISTERED` is because you didn't sign in. 
Not sure why telegram doesn't like your API_ID tho. Are you sure you filled the combination correctly? 
API_ID_INVALID means The api_id/api_hash combination is invalid

**Comment by Asjas** [comment]
@painor Yeah I filled in both correctly. I copied and pasted them directly from the website.

I tried this code to get a Single User from a channel but I also get the `AUTH_KEY_UNREGISTERED`.

```js
import { Api, TelegramClient } from "telegram";
import { StringSession } from "telegram/sessions/index.js";

const apiId = 7967860;
const apiHash = "ec8dea66849f46154b5349acbfccedbb";

const session = new StringSession("");
const client = new TelegramClient(session, apiId, apiHash, {});

(async function run() {
  await client.connect();

  console.log("You should now be connected.");
  console.log(client.session.save());

  const result = await client.invoke(
    new Api.channels.GetParticipant({
      channel: new Api.InputChannel(-1001536877977),  // real channel
      participant: new Api.ChannelParticipant({ userId: 1425866959 }),  // real user
    }),
  );
  console.log(result); // prints the result
})();
```

![app](https://user-images.githubusercontent.com/3828967/125938595-b269cf33-a391-46aa-a8e1-33e5aacef7ae.png)

**Comment by Asjas** [comment]
Okay so I'm contacting Telegram on Twitter for support, I tried this with another Node.js library named `MTPromo` and I'm also getting the same error message. The issue seems related to Telegram itself and not the library.

Could be that new developer accounts are getting 7 digit APP_ID's and it could be a bug in Telegram itself that is blocking the requests. Based on a number of Google results it seems that every time the APP_ID number gets longer by a number it causes issues for people and then Telegram has to fix their API.

**Comment by painor** [comment]
that might be it. in the meantime you could probably use some random API ID keys you find online

**Comment by Asjas** [comment]
Yeah that's what I'm trying to do, seeing if I can't find any to use while I test the API 😄

**Comment by nasyarobby** [comment]
Thanks! I see that it is not the library issue so I will close it for now.. 🙌

**Comment by Asjas** [comment]
@painor I was able to get this working by using the [logging in as a user](https://gram.js.org/getting-started/authorization#logging-in-as-a-user) route. It took a few tries but I figured out how to do this. 

I was able to send myself test messages so it appears I'm authenticated.

The only issue I still have is understanding how to get the channel, I'm not sure how to write the code as I have the Channel ID but I think I'm missing something in how to write the code. 

I tested with `Pyrogram` which is a Python Telegram app and I was able to get a response as to whether a user is in a channel or not.

```python
data = await app.get_chat_member(-1001536877977, "ajroos2")
```

But when I use this code from GramJS I get an error message that says `RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -2147483648 and <= 2147483647. Received -1_001_536_877_977`.

```js
const result = await client.invoke(
    new Api.channels.GetParticipant({
      channel: new Api.InputChannel({ channelId: -1001536877977 }),
      participant: new Api.ChannelParticipant({ userId: 1425866959 }),
    }),
  );
```

I'm not sure what code I should write to get the channel access to work, if you could help with that please?

**Comment by painor** [comment]
> @painor I was able to get this working by using the [logging in as a user](https://gram.js.org/getting-started/authorization#logging-in-as-a-user) route. It took a few tries but I figured out how to do this.
> 
> I was able to send myself test messages so it appears I'm authenticated.
> 
> The only issue I still have is understanding how to get the channel, I'm not sure how to write the code as I have the Channel ID but I think I'm missing something in how to write the code.
> 
> I tested with `Pyrogram` which is a Python Telegram app and I was able to get a response as to whether a user is in a channel or not.
> 
> ```python
> data = await app.get_chat_member(-1001536877977, "ajroos2")
> ```
> 
> But when I use this code from GramJS I get an error message that says `RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -2147483648 and <= 2147483647. Received -1_001_536_877_977`.
> 
> ```js
> const result = await client.invoke(
>     new Api.channels.GetParticipant({
>       channel: new Api.InputChannel({ channelId: -1001536877977 }),
>       participant: new Api.ChannelParticipant({ userId: 1425866959 }),
>     }),
>   );
> ```
> 
> I'm not sure what code I should write to get the channel access to work, if you could help with that please?
> 
> Basically, I'm not sure what I should pass to the `channel` option of the `GetParticipant` constructor here to be a valid channel.
> 
> ```js
> channel: new Api.InputChannel({ channelId: -1001536877977 }),
> ```

If you're going to used Ids inside Api constructors don't add the -100

You can possible just pass the id without constructor
channel:-1001536877977

**Comment by Asjas** [comment]
Yup that works, thank you very much for your time. I hope that I can continue on without having to bother you again. 💯 😄 

You've been a huge help, thank you
