### ISSUE TITLE
How to use redis to store session

### ISSUE THREAD

**Issue by sathish2k** [gram-js/gramjs#114]
I'm creating a app to login multiple users and start forwarding a messages

Either i need to store session for multiple users or need to create multiple instance

creating multiple instance will lead performance issues??

need to use kafka for new message listeners

Please give some example for multiple login

**Comment by rojserbest** [comment]
For logging in with multiple users, you can simply initialize multiple `TelegramClient`s.

For saving sessions in Redis or a database, you can do something like this:
```js
const savedStringSession = /* get saved string session in database or use "" as default if not in database */;
const client = new TelegramClient(new StringSession(savedStringSession), 000000, "abcdef0123456789");
saveStringSesssion(client.session.save());
```

You can take a look at [ionbot/ion-app](https://github.com/ionbot/ion-app) which uses MongoDB to store session to get more ideas on it.

**Comment by sathish2k** [comment]
> For logging in with multiple users, you can simply initialize multiple `TelegramClient`s.
> 
> For saving sessions in Redis or a database, you can do something like this:
> 
> ```js
> const savedStringSession = /* get saved string session in database or use "" as default if not in database */;
> const client = new TelegramClient(new StringSession(savedStringSession), 000000, "abcdef0123456789");
> saveStringSesssion(client.session.save());
> ```
> 
> You can take a look at [ionbot/ion-app](https://github.com/ionbot/ion-app) which uses MongoDB to store session to get more ideas on it.

How can i listen update events for multiple users

**Comment by painor** [comment]
```js
const client1 = new TelegramClient(....);
const client2 = new TelegramClient(....);
client1.addEventHandler(...)
client2.addEventHandler(...)
```

you can obviously put it a for loop or something like that

**Comment by sathish2k** [comment]
> ```js
> const client1 = new TelegramClient(....);
> const client2 = new TelegramClient(....);
> client1.addEventHandler(...)
> client2.addEventHandler(...)
> ```
> 
> you can obviously put it a for loop or something like that

export const getChats = async () => {
    try {
         const stringSession = userSession
        const client = new TelegramClient(stringSession, api_id, api_hash, {
            connectionRetries: 5,
        });
        const { chats } = await client.invoke(new Api.messages.GetAllChats({ exceptIds: [] }))
        console.log(chats)
        console.log('called')
        return { chats: chats }
    } catch (err) {
        console.log(err)
        return { err: err }
    }
}

my client will be created dynamically

**Comment by painor** [comment]
better call .connect() and .disconnect() then
