### ISSUE TITLE
sizeType value for DownloadMediaInterface

### ISSUE THREAD

**Issue by nasyarobby** [gram-js/gramjs#117]
Hi, I'm trying to download media. However, the quality of the image is poor. Compared to the one I viewed on the telegram app on my phone.

I found out that I can add sizeType, something like this:

```js
const buffer = await client.downloadMedia(update.message.media, {
   workers: 1,
   sizeType:  '' // set to what?
});
````
Is this the correct way to make sure I download the media with the highest available quality? What value I can use for ```sizeType```. I cannot find it on the documentation.
Or is there any other ways?

Thank you.

**Comment by painor** [comment]
you are correct I forgot to document that.
const sizeTypes = ["w", "y", "d", "x", "c", "m", "b", "a", "s"];
these are the size types. s being the smallest and w the biggest. Not all pictures have all of these so the library will try to pick the closest one.

**Comment by banghasan** [comment]
> ```js
>    sizeType:  'x' // big size
> ```

not work for me, still getting bad resolution

[![2021-07-18-09-59.jpg](https://i.postimg.cc/yxgb4gPN/2021-07-18-09-59.jpg)](https://postimg.cc/LgSTjsGd)

**Comment by nasyarobby** [comment]
I tried, but I think the library pick the right size for me even though there are bigger size available. 

So, after I look at the source code , (correct me if Im wrong)  I think function ```pickFileSize``` in [client/downloads.ts:359](https://github.com/gram-js/gramjs/blob/2a77adedd65d746f8c138f6c0313e4fbb80c3c52/gramjs/client/downloads.ts#L359) ignore the size if the instance is Api.PhotoSizeProgressive.

**Comment by nasyarobby** [comment]
> > ```js
> >    sizeType:  'x' // big size
> > ```
> 
> not work for me, still getting bad resolution
> 
> [![2021-07-18-09-59.jpg](https://camo.githubusercontent.com/442ce6906db432e18c210ec02266dea610ec599fe37cceda60ae0ab85fc2629f/68747470733a2f2f692e706f7374696d672e63632f797867623467504e2f323032312d30372d31382d30392d35392e6a7067)](https://postimg.cc/LgSTjsGd)

As you can see , the className is ```PhotoSizeProgressive```, and the library will not pick this size type and find the next available size which is not ```PhotoSizeProgressive```

**Comment by nasyarobby** [comment]
I made a change in download.ts file.
Basically I add a new property ```size``` which set to the maximum size avalailble and return it, so the Downloader will pick it.

Or I can also change the line 432 where it pass the ```fileSize``` value to check if the size variable contain sizes property. If it does, it will then get the maximum size available. If it does not, then we will pass the ```size.size``` as the ```fileSize``` value.

Either way, I will be very happy to make the PR.

**Comment by painor** [comment]
PhotoSizeProgressive is a new one. I like the second option more feel free to send a PR thanks.

**Comment by nasyarobby** [comment]
PR #118 posted

**Comment by painor** [comment]
Thanks for the PR.
Fixed in https://github.com/gram-js/gramjs/pull/118
