### ISSUE TITLE
unable to get all chats list

### ISSUE THREAD

**Issue by sathish2k** [gram-js/gramjs#119]
messages.getAllChats

while calling this method i'm only getting channels list

**Comment by rojserbest** [comment]
Can you share your code?

**Comment by sathish2k** [comment]
> Can you share your code?

```js
export const getChats = async (ctx: any) => {
    const session = ctx.session.userSession;
    const userSession = new StringSession(session);
    const client = new TelegramClient(userSession, api_id, api_hash, { connectionRetries: 5 })
    await client.connect()
    try {
        const chats = await client.invoke(new Api.messages.GetAllChats({ exceptIds: [] }))
        console.log(chats)
        console.log('called')
        client.disconnect()
        return { chats: chats }
    } catch (err) {
        console.log(err)
        client.disconnect()
        return { err: err }
    }
}```

**Comment by painor** [comment]
any reason for not using getDialogs?

**Comment by sathish2k** [comment]
> any reason for not using client.getDialogs?

client.getDialogs will return all chats,channels and bots list

**Comment by rojserbest** [comment]
> > any reason for not using client.getDialogs?
> 
> client.getDialogs will return all chats,channels and bots list?

sure

**Comment by sathish2k** [comment]
> any reason for not using client.getDialogs?

Thanks a lot its works fine

**Comment by bigbigsir** [comment]
@sathish2k How do I page correctly when using getDialogs
