### ISSUE TITLE
Unable to find user in events listener

### ISSUE THREAD

**Issue by sathish2k** [gram-js/gramjs#121]
```js
const listenForMessages = (event: any) => {
    const message = event.message as Message;
    console.log(message)
    console.log(message.senderId);
   

}
export const startRedirection = async (ctx: any) => {
    const session = ctx.session.userSession;
    const userSession = new StringSession(session);
    const client = new TelegramClient(userSession, api_id, api_hash, { connectionRetries: 5 })
    await client.connect()
    try {
        console.log('event listener',client)
        let e = client.addEventHandler(listenForMessages, new NewMessage({}));
        console.log(client)
    } catch (err) {
        console.log(err)
    }
}

```

above is code snippet ,my problem is this event is triggered for multiple clients but unable to find owner of the listener

**Comment by painor** [comment]
what do you mean by that? 
do you need event._client?

**Comment by sathish2k** [comment]
> what do you mean by that?
> do you need event._client?

i got session inside event._client 
but its possible to save userid inside session

**Comment by painor** [comment]
you can use getMe() to get that. it's a very cheap Api call. an other idea would be to subclass TelegramClient and add a user_id field.

**Comment by sathish2k** [comment]
> TelegramClient

ok i will try subclass because i don`t want to make multiple api calls each time new message arrives

**Comment by sathish2k** [comment]
> > TelegramClient
> 
> ok i will try subclass because i don`t want to make multiple api calls each time new message arrives

if possible i need a small snippet of code

**Comment by painor** [comment]
well the ideal way would be to call getme() once the client has started (after .connect()) and then use client._selfInputPeer.userId

**Comment by sathish2k** [comment]
> well the ideal way would be to call getme() once the client has started (after .connect()) and then use client._selfInputPeer.userId

cool
