### ISSUE TITLE
How to convert media files eg)photo

### ISSUE THREAD

**Issue by sathish2k** [gram-js/gramjs#123]
```js
 photo: VirtualClass {
    CONSTRUCTOR_ID: 4212750949,
    SUBCLASS_OF_ID: 3581324060,
    className: 'Photo',
    classType: 'constructor',
    flags: 0,
    hasStickers: false,
    id: Integer { value: 6337094176914647905n },
    accessHash: Integer { value: -4283278571034985186n },
    fileReference: <Buffer 04 5d 10 40 6a 00 00 00 42 60 fe 2d d1 61 35 54 0b 03 0d 0a e1 f2 01 37 8c 90 d6 69 c2>,
    date: 1627268698,
    sizes: [ [VirtualClass], [VirtualClass], [VirtualClass], [VirtualClass] ],
    videoSizes: null,
    dcId: 5
  },
```

i'm getting this data but how to add watermark or something in this

**Comment by sathish2k** [comment]
> ```js
>  photo: VirtualClass {
>     CONSTRUCTOR_ID: 4212750949,
>     SUBCLASS_OF_ID: 3581324060,
>     className: 'Photo',
>     classType: 'constructor',
>     flags: 0,
>     hasStickers: false,
>     id: Integer { value: 6337094176914647905n },
>     accessHash: Integer { value: -4283278571034985186n },
>     fileReference: <Buffer 04 5d 10 40 6a 00 00 00 42 60 fe 2d d1 61 35 54 0b 03 0d 0a e1 f2 01 37 8c 90 d6 69 c2>,
>     date: 1627268698,
>     sizes: [ [VirtualClass], [VirtualClass], [VirtualClass], [VirtualClass] ],
>     videoSizes: null,
>     dcId: 5
>   },```
> 
> i'm getting this data but how to add watermark or something in this
> ```

This need to be downloaded or i can use file reference buffer

**Comment by painor** [comment]
if you want to edit the image you'll have to download then upload. if you want to edit the caption you can just use the object in sendFile

**Comment by sathish2k** [comment]
> if you want to edit the image you'll have to download then upload. if you want to edit the caption you can just use the object in sendFile

```js
const buffer = await telegram.downloadMedia(media.photo, {})
let wm = await addWaterMarkText(buffer,to)
await telegram.sendFile(forwardObj.toPeer, { file: wm, caption: event.message.message })```

I tried this but not working

**Comment by painor** [comment]
> > if you want to edit the image you'll have to download then upload. if you want to edit the caption you can just use the object in sendFile
> 
> ```js
> const buffer = await telegram.downloadMedia(media.photo, {})
> let wm = await addWaterMarkText(buffer,to)
> await telegram.sendFile(forwardObj.toPeer, { file: wm, caption: event.message.message })
> ```
> 
> I tried this but not working
> 
> Here i'm trying to add watermark

Well it depends on what wm is. Is it a local path or a buffer or what exactly ?

**Comment by sathish2k** [comment]
> > > if you want to edit the image you'll have to download then upload. if you want to edit the caption you can just use the object in sendFile
> > 
> > 
> > ```js
> > const buffer = await telegram.downloadMedia(media.photo, {})
> > let wm = await addWaterMarkText(buffer,to)
> > await telegram.sendFile(forwardObj.toPeer, { file: wm, caption: event.message.message })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tried this but not working
> > Here i'm trying to add watermark
> 
> Well it depends on what wm is. Is it a local path or a buffer or what exactly ?

Buffer

**Comment by sathish2k** [comment]
> > > > if you want to edit the image you'll have to download then upload. if you want to edit the caption you can just use the object in sendFile
> > > 
> > > 
> > > ```js
> > > const buffer = await telegram.downloadMedia(media.photo, {})
> > > let wm = await addWaterMarkText(buffer,to)
> > > await telegram.sendFile(forwardObj.toPeer, { file: wm, caption: event.message.message })
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I tried this but not working
> > > Here i'm trying to add watermark
> > 
> > 
> > Well it depends on what wm is. Is it a local path or a buffer or what exactly ?
> 
> @painor Buffer

Please any suggestion or solution for this

**Comment by painor** [comment]
The easiest way is to save it in a file (using the fs module) and then use that path in sendFile. the other option is using the  CustomFile class with the buffer but that's harder.

**Comment by sathish2k** [comment]
> The easiest way is to save it in a file (using the fs module) and then use that path in sendFile. the other option is using the CustomFile class with the buffer but that's harder.

using custom file doesn't need upload?
```js
const toUpload = new CustomFile("photo."+image.info.format, image.info.size,'', image.data);
```

**Comment by painor** [comment]
> > The easiest way is to save it in a file (using the fs module) and then use that path in sendFile. the other option is using the CustomFile class with the buffer but that's harder.
> 
> using custom file doesn't need upload?
> 
> ```js
> const toUpload = new CustomFile("photo."+image.info.format, image.info.size,'', image.data);
> ```

that should be working. if it still doesn't feel free to provide your full code and I'll take a look at it when I can

**Comment by ljs19923** [comment]
@painor @sathish2k can you show me your full code because for me, CustomFile is undefined...

**Comment by guotie** [comment]
How to get media contentType, eg image/png or image/jpeg?
