### ISSUE TITLE
How to handle updates like given in telegram doc

### ISSUE THREAD

**Issue by sathish2k** [gram-js/gramjs#125]
updatesTooLong#e317af7e = Updates;
updateShort#78d4dec1 update:Update date:int = Updates;
updateShortMessage#2296d2c8 flags:# out:flags.1?true mentioned:flags.4?true media_unread:flags.5?true silent:flags.13?true id:int user_id:int message:string pts:int pts_count:int date:int fwd_from:flags.2?MessageFwdHeader via_bot_id:flags.11?int reply_to:flags.3?MessageReplyHeader entities:flags.7?Vector<MessageEntity> = Updates;
updateShortChatMessage#402d5dbb flags:# out:flags.1?true mentioned:flags.4?true media_unread:flags.5?true silent:flags.13?true id:int from_id:int chat_id:int message:string pts:int pts_count:int date:int fwd_from:flags.2?MessageFwdHeader via_bot_id:flags.11?int reply_to:flags.3?MessageReplyHeader entities:flags.7?Vector<MessageEntity> = Updates;
updateShortSentMessage#11f1331c flags:# out:flags.1?true id:int pts:int pts_count:int date:int media:flags.9?MessageMedia entities:flags.7?Vector<MessageEntity> = Updates;
updatesCombined#725b04c3 updates:Vector<Update> users:Vector<User> chats:Vector<Chat> date:int seq_start:int seq:int = Updates;
updates#74ae4240 updates:Vector<Update> users:Vector<User> chats:Vector<Chat> date:int seq:int = Updates;

How to subscribe to updates

**Comment by painor** [comment]
Use event handler for that. 
https://painor.gitbook.io/gramjs/getting-started/updates-events

**Comment by sathish2k** [comment]
> Use event handler for that.
> https://painor.gitbook.io/gramjs/getting-started/updates-events

```js
mtproto.updates.on('updatesTooLong', (updateInfo) => {
  console.log('updatesTooLong:', updateInfo);
});

mtproto.updates.on('updateShortMessage', (updateInfo) => {
  console.log('updateShortMessage:', updateInfo);
});

mtproto.updates.on('updateShortChatMessage', (updateInfo) => {
  console.log('updateShortChatMessage:', updateInfo);
});

mtproto.updates.on('updateShort', (updateInfo) => {
  console.log('updateShort:', updateInfo);
});

mtproto.updates.on('updatesCombined', (updateInfo) => {
  console.log('updatesCombined:', updateInfo);
});

mtproto.updates.on('updates', (updateInfo) => {
  console.log('updates:', updateInfo);
});
```

Is there is any way to use like this

**Comment by painor** [comment]
You can use if (event instanceof Api.UpdatesTooLong) if you need

**Comment by sathish2k** [comment]
> instanceof

By using Raw({}) ?

**Comment by painor** [comment]
yes
```js
 client.addEventHandler((update: Api.TypeUpdate) => {
    if (update instanceof Api.UpdatesTooLong){
    // do something
    } else if (update instanceof Api.UpdatesCombined){
    // do something else
    }
    
    console.log("Received new Update")
    console.log(update);
});

```

**Comment by sathish2k** [comment]
> ```js
> client.addEventHandler((
> ```

perfect i will check this

**Comment by sathish2k** [comment]
```js
client.addEventHandler((update: Api.TypeUpdate) => {
            if (update instanceof Api.Updates) {
                console.log('Updates', update)
            } else if (update instanceof Api.UpdatesCombined) {
                // do something else
                console.log('UpdatesCombined', update)
            }
            else if (update instanceof Api.UpdatesTooLong) {
                // do something else
                console.log('UpdatesTooLong', update)
            } else if (update instanceof Api.UpdateShortMessage) {
                // do something else
                console.log('UpdateShortMessage', update)
            }else if (update instanceof Api.UpdateShortSentMessage) {
                // do something else
                console.log('UpdateShortSentMessage', update)
            }else if(update instanceof Api.UpdateShort){
                // do something else
                console.log('UpdateShort', update)
            }
        });
```
Only update short message is working.Other updates not working

**Comment by sathish2k** [comment]
> ```js
> client.addEventHandler((update: Api.TypeUpdate) => {
>             if (update instanceof Api.Updates) {
>                 console.log('Updates', update)
>             } else if (update instanceof Api.UpdatesCombined) {
>                 // do something else
>                 console.log('UpdatesCombined', update)
>             }
>             else if (update instanceof Api.UpdatesTooLong) {
>                 // do something else
>                 console.log('UpdatesTooLong', update)
>             } else if (update instanceof Api.UpdateShortMessage) {
>                 // do something else
>                 console.log('UpdateShortMessage', update)
>             }else if (update instanceof Api.UpdateShortSentMessage) {
>                 // do something else
>                 console.log('UpdateShortSentMessage', update)
>             }else if(update instanceof Api.UpdateShort){
>                 // do something else
>                 console.log('UpdateShort', update)
>             }
>         });
> ```
> 
> Only update short message is working.Other updates not working
