### ISSUE TITLE
Why chatId in session different with JSON from incoming message? 

### ISSUE THREAD

**Issue by butthx** [gram-js/gramjs#129]
Hi, sorry. 
This is a little question that popped into my mind and I just wanted to ask for an explanation. 
I using StoreSession and I get a file whose contents are like this : 
```
[-1001228946795,"-3620484959366505492","hiddensender",null,"a user",1627024531676]
```
Why the chatId different? on incoming message the chatId not started with `-100`.

**Comment by painor** [comment]
are you sure this is not a channel? It should only add -100 to channel if it's adding -100 to users then it might be a bug

**Comment by butthx** [comment]
it channel more specifically supergroups.

**Comment by painor** [comment]
Then it's fine. 

Channels and Supergroups have -100 added to them to differentiate them from Users. This is the same way the Bot Api does it
