### ISSUE TITLE
where is the API directory with settings file?

### ISSUE THREAD

**Issue by luluhoc** [gram-js/gramjs#13]
head to api/ directory and create a copy of the settings_example file, naming it settings (lowercase!). Then fill the file with the corresponding values (your api_id, api_hash and phone number in international format).

**Comment by painor** [comment]
oh that's actually the old way of doing it. it changed in the latest version and I forgot to update the readme. 
The current way needs you to provide promises to enter your phone number and code. you can find an example in the examples folder 

```
const apiId = // put your api id here [for example 123456789]
const apiHash = // put your api hash here [for example '123456abcfghe']

const client = new TelegramClient(new StringSession(''), apiId, apiHash) // you can pass a string session here from previous logins.
// If you want to run this example in the test servers uncomment this line
//client.session.setDC(2, '149.154.167.40', 80)

client.start({
    phone: phoneCallback,
    password: passwordCallback,
    code: codeCallback,
})
```

you can then save the session string wherever you want to use it later with `const string = client.save()`
