### ISSUE TITLE
Files larger than 1.5GB cannot be downloaded

### ISSUE THREAD

**Issue by zjmqlf** [gram-js/gramjs#134]
Utils.ts

export function getAppropriatedPartSize(fileSize: number) {
    if (fileSize <= 104857600) {
        // 100MB
        return 128;
    }
    if (fileSize <= 786432000) {
        // 750MB
        return 256;
    }
    if (fileSize <= 1572864000) {
        // 1500MB
        return 512;
    }
    throw new Error("File size too large");
}

Is it the Telegram official limit for gramjs not to download files greater than 1.5GB? Or gramjs limitations?

**Comment by painor** [comment]
Should be fixed in latest update
