### ISSUE TITLE
Add users to channel

### ISSUE THREAD

**Issue by mkhoshkam** [gram-js/gramjs#136]
how to invite users to channel with userID(not username)?

**Comment by painor** [comment]
why would you want that? anyway you can't use userIds until the library has seen that user somewhere.

**Comment by mkhoshkam** [comment]
When I try to add users from one channel to another, only users with usernames are added, but users whose usernames are hidden are not added and give an error.

**Comment by painor** [comment]
you shouldn't be adding users without their consent anyway.

It's telegram that returns the errors not the library

**Comment by mkhoshkam** [comment]
Thanks
