### ISSUE TITLE
How to compile this repo by myself

### ISSUE THREAD

**Issue by DricHao** [gram-js/gramjs#142]
Bro, I changed some stuffs in source code. well, how to compile project?

**Comment by rojserbest** [comment]
What do you mean? Building for browsers?

**Comment by DricHao** [comment]
> What do you mean? Building for browsers?

node env not broswer, you know source code is writed by Typescript

**Comment by rojserbest** [comment]
> > What do you mean? Building for browsers?
> 
> node env not broswer, you know source code is writed by Typescript

Maybe it is `npx tsc`.

**Comment by DricHao** [comment]
> > > What do you mean? Building for browsers?
> > 
> > 
> > node env not broswer, you know source code is writed by Typescript
> 
> Maybe it is `npx tsc`.

I've tried, but got an error, doesn't include static folder in tl folder, it's weird

**Comment by itsLucario** [comment]
Try `npx webpack`
