### ISSUE TITLE
Possible to submit PRs to Gitbook documentation?

### ISSUE THREAD

**Issue by KidA001** [gram-js/gramjs#147]
There were some small typos and an incorrect function call, is it possible to submit PR's to the documentation? Happy to help contribute.

In [Create Channel](https://painor.gitbook.io/gramjs/working-with-channels-and-supergroups-and-geogroups/channels.createchannel) the example on line 8 should be `Api.channels.CreateChannel` instead of `Api.channels.createChannel`

Glad to help!

**Comment by painor** [comment]
The docs there are outdated and will be replaced by the ones at https://gram.js.org/ and https://gram.js.org/beta soon. 

the /beta docs are pulled from the doc strings inside the code in this repo and the other files are from the markdown files at https://github.com/gram-js/docs
