### ISSUE TITLE
How to set the 2fa password of the account

### ISSUE THREAD

**Issue by 594904020** [gram-js/gramjs#148]
How to set the 2fa password of the account

**Comment by painor** [comment]
You would need to use the RAW Api  for that. There is no friendly method for it yet. 

You can use this functions from here in the meantime. https://github.com/Ajaxy/telegram-tt/blob/master/src/lib/gramjs/client/2fa.ts#L54

**Comment by 594904020** [comment]
https://github.com/alik0211/mtproto-core/issues/180

Reference here, combined with the source code and using "Buffer. From(xxx)" to solve this problem
