### ISSUE TITLE
Client disconnection error

### ISSUE THREAD

**Issue by 594904020** [gram-js/gramjs#149]
When I was listening for message events，Maybe I'll close the client connection in the background，
Report an error at this time：Error: Could not get me

code:
1、client.addEventHandler(xxxxxxx)
and Maybe I'll close the client connection in the background，
2、await client.destroy();

error：
  1、Error: Could not get me
  2、Error: Cannot send requests while disconnected. You need to call .connect()

**Comment by painor** [comment]
why are you doing that? once you .destroy or .disconnect a client you can no longer call any requests. your client probably still has some pending requests so it's probably best to remove the event handler as well.

**Comment by 594904020** [comment]
Because I'm sure I will destroy it instead of using it

**Comment by 594904020** [comment]
Because I really don't use it anymore, I need to disconnect

**Comment by painor** [comment]
then you'll need to remove all event handlers as well. 
client._eventBuilders = []

**Comment by 594904020** [comment]
Thank you for your help

**Comment by 594904020** [comment]
Thank you for your help
