### ISSUE TITLE
checkHistoryImport in tl file

### ISSUE THREAD

**Issue by adamsr123** [gram-js/gramjs#155]
I saw a `checkHistoryImport` line in the schema file.
But I don't find this in the Telegram docs.

**Comment by painor** [comment]
not all requests/types are in telegram's docs. 

https://gram.js.org/tl/messages/CheckHistoryImport
https://corefork.telegram.org/method/messages.checkHistoryImport

**Comment by adamsr123** [comment]
Oh I see
So I wondered what is the algorithm of this request
