### ISSUE TITLE
How to use Socks5

### ISSUE THREAD

**Issue by 594904020** [gram-js/gramjs#157]
How to use Socks5

**Comment by painor** [comment]
https://gram.js.org/faq#can-i-use-a-proxy

you'll have to use it outside the script itself.

**Comment by 594904020** [comment]
Thank you. I have solved this problem

**Comment by painor** [comment]
> > Thank you. I have solved this problem
> 
> @594904020 how? Could you say some details please?

https://gram.js.org/getting-started/authorization#using-mtproxies-and-socks5-proxies

**Comment by 594904020** [comment]
> > 谢谢你。我已经解决了这个问题
> 
> @594904020怎么样？你能说一些细节吗？

Modify source file  "PromisedNetSockets"，use  dependent  "socket-client-proxy"   replace  new net.Socket

https://www.npmjs.com/package/socket-client-proxy
