### ISSUE TITLE
Problem starting session

### ISSUE THREAD

**Issue by JLC000** [gram-js/gramjs#161]
Hello, good morning.

I am trying to start session using the api, but it returns the code "PHONE_CODE_EXPIRED", I have previously started session using the api. 
previously I was able to start session but now I can't.
I share my code, if you can give me a hand.
Clarification, is exposing the results with express.js

**Sending the code**

const bodySendCode = (req) => {
      return {
        phoneNumber: phoneComplete(req),
        apiId: Number(config.apiId),
        apiHash: String(config.apiHash),
        settings: new Api.CodeSettings({
            allowFlashcall: true,
            currentNumber: true,
            allowAppHash: true,
        })
    }

const sendCodeHandler = async (req, res) => {

    try {

        const telegramClient = clientTelegram("");
        await telegramClient.connect();

        const result = await telegramClient
            .invoke(new Api.auth.SendCode(bodySendCode(req)));

        res.json(result);

    } catch (err) {
        console.log(err + '')

        const code = err.code == undefined ? 400 : err.code;

        res.status(code).json({ error: err.toString() });
    }
}

**Starting session**

const bodySignIn = (req) => {
    return {
        phoneNumber: req.body.phone_number,
        phoneCodeHash: req.body.phone_code_hash,
        phoneCode: req.body.phone_code
    }
}

const signInHandler = async (req, res) => {

    try {
        validationResult(req).throw();

        const telegramClient = clientTelegram("");
        await telegramClient.connect();

        const result = await telegramClient
            .invoke(new Api.auth.SignIn(bodySignIn(req)));

        result.token = telegramClient.session.save();

        res.json(result);
    } catch (err) {
        console.log(err)
        res.status(400).json({ error: err.toString() });
    }
}

**Comment by painor** [comment]
you need to use the same client for both sending the code and signing in. 
gramjs has helper methods for those. you can probably use the .start() function to all of that for you py providing callbacks to it.

**Comment by JLC000** [comment]
The problem is that I can't use .start() because I perform the two operations "send code" and "start session" in two different endpoints with express.js.

Isn't there any other mechanism to start the session?

**Comment by painor** [comment]
Eitherway you'll need to use the same TelegramClient instance and not create a new one. 
Basically the logic is as follows:

First endpoint to send code 
```ts
            const sendCodeResult = await client.sendCode(
                apiCredentials,
                phoneNumber,
                authParams.forceSMS
            );
            phoneCodeHash = sendCodeResult.phoneCodeHash;
            isCodeViaApp = sendCodeResult.isCodeViaApp;

```

Second endpoint to login

```ts
            const result = await client.invoke(
                new Api.auth.SignIn({
                    phoneNumber,
                    phoneCodeHash,
                    phoneCode
                })
            );

```

**Comment by JLC000** [comment]
Thank you very much, I was able to solve the problem.

Greetings, you are creating an excellent tool.

**Comment by VityaSchel** [comment]
<img width="499" alt="image" src="https://github.com/gram-js/gramjs/assets/59040542/412d8c40-49f8-4ec4-8301-adc64773924d">

If anyone sees this error, please DO NOT send the code through telegram messages or obscure it. Telegram blocks and expires the code if you send it in message to other people.
