### ISSUE TITLE
Error when starting client

### ISSUE THREAD

**Issue by KidA001** [gram-js/gramjs#162]
I'm getting an error `Cannot send requests while disconnected. You need to call .connect()` when I call `start()` on my gramJs client (see code below).  This error seems out of the blue as I'm not sure what if anything has changed in my code. I've logged out any existing sessions to this client.

My code:
```typescript
// `sessionToken` is an empty string in this situation
const session = new StringSession(sessionToken);
const client = new TelegramClient(session, creds.apiId, creds.apiHash, { connectionRetries: 0 });
await client.start({
  phoneNumber: creds.phone,
  phoneCode: async () => authCode(),
  password: async () => '',
  onError: (err) => handleConnectionErr(err),
});
```

```
Error: Cannot send requests while disconnected. You need to call .connect()
    at MTProtoSender.send (path-to-app/node_modules/telegram/network/MTProtoSender.js:201:19)
    at TelegramClient.<anonymous> (path-to-app/node_modules/telegram/client/TelegramClient.js:940:32)
    at Generator.next (<anonymous>)
    at fulfilled (path-to-app/node_modules/telegram/client/TelegramClient.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Any insight appreciated

**Comment by KidA001** [comment]
For some reason `connectionRetries` needs to be at least 1.

**Comment by painor** [comment]
yeah sometimes telegram would disconnect you randomly and you'll need to recreate the connection. It's usually safer to put it something like 5 since the disconnect can happen twice.
