### ISSUE TITLE
How to trigger the robot button

### ISSUE THREAD

**Issue by 594904020** [gram-js/gramjs#168]
![image](https://user-images.githubusercontent.com/32348909/135470321-74955ffe-dc99-47af-85f5-2896141b0b65.png)
![image](https://user-images.githubusercontent.com/32348909/135471001-fda2d663-018d-4026-8511-e8cbeca24225.png)

**Comment by painor** [comment]
you can try `message.buttons[0].click()` (which calls https://gram.js.org/tl/messages/GetBotCallbackAnswer)

**Comment by 594904020** [comment]
> message.buttons[0].click()

 RPCError: 400: MESSAGE_ID_INVALID

Listening for messages in
![image](https://user-images.githubusercontent.com/32348909/135482706-7162915a-4d09-4dd6-8457-77339f96e691.png)
