### ISSUE TITLE
Search channels

### ISSUE THREAD

**Issue by alexauvray** [gram-js/gramjs#183]
Is there a way to search for channels through GramJS, just as if we'd do CMD+K in the app and search for a specific chan?

On Telethon it appears to be the `contacts.search` method from what I read here :

https://stackoverflow.com/questions/62016386/how-to-search-for-groups-and-channel-in-telegram-using-telethon

**Comment by painor** [comment]
it's probably this then https://gram.js.org/tl/contacts/Search (ignore the description there).
