### ISSUE TITLE
How to reply a message to the sender

### ISSUE THREAD

**Issue by 594904020** [gram-js/gramjs#184]
How to get peer in addEventHandler？？

 client.addEventHandler((event)=>{
        if(event.originalUpdate.className == "UpdateShortMessage"){
           //How to get peer
            client.sendMessage(peer, { message: 'reply message!' });
        }
    }, new NewMessage({}));

**Comment by painor** [comment]
you can just do `event.message.reply()` or `event.message.respond()`

**Comment by 594904020** [comment]
> 你可以做`event.message.reply()`或`event.message.respond()`

thanks
