### ISSUE TITLE
RPCError: 406: AUTH_KEY_DUPLICATED

### ISSUE THREAD

**Issue by 594904020** [gram-js/gramjs#189]
RPCError: 406: AUTH_KEY_DUPLICATED

Why does session login report this error and how to solve it

**Comment by 594904020** [comment]
thanks

**Comment by prakashgp** [comment]
What if I disconnect from one IP and immediately connect from another IP (proxy rotation), I am facing this error. Is there any delay I should use  and how much ?

**Comment by apexJay015** [comment]
Connection error occurred: 406: AUTH_KEY_DUPLICATED (caused by InvokeWithLayer) {"code":406,"errorMessage":"AUTH_KEY_DUPLICATED","stack":"RPCError: 406: AUTH_KEY_DUPLICATED (caused by InvokeWithLayer)\n    at RPCMessageToError

I got this problem how to recover this issue?
