### ISSUE TITLE
Multiple connections

### ISSUE THREAD

**Issue by megaDannyIng** [gram-js/gramjs#191]
I have code like this.

```ts
const { StringSession } = require('telegram/sessions')
const input = require('input') // npm i input

const apiId = 111111
const apiHash = 'fcf............................'
const stringSession = new StringSession(''); // fill this later with the value from session.save()
(async () => {
    console.log('Loading interactive example...')
    const client = new TelegramClient(stringSession, apiId, apiHash, { connectionRetries: 5 })
    await client.start({
        phoneNumber: async () => await input.text('number ?'),
        password: async () => await input.text('password?'),
        phoneCode: async () => await input.text('Code ?'),
        onError: (err) => console.log(err),
    });
    console.log('You should now be connected.')
    console.log(client.session.save()) // Save this string to avoid logging in again
  async function eventPrint(event: NewMessageEvent) {
  console.log(event.message);
  };
  client.addEventHandler(eventPrint, new NewMessage({ chats: [chatId] }));
})()
```

When i run this code on express server in different por only work last telegram. That is, the last running one always works, the previous ones do not work. It feels like the new connection is killing the old one. How to solve the problem with multi-connection?

**Comment by painor** [comment]
I'm sorry but I don't understand what you mean.

the connection is tied to the client object. if you create a new TelegramClient you are creating a new connection.

if you want to have multiple connections maybe put the clients inside an array?

**Comment by ddonchuk** [comment]
@painor i have express app which find message in telegram channel and i want run 1 app for one channel and 2 app on another chanel. i need run telegram in different terminals . Array not suits me.

**Comment by painor** [comment]
I don't see the issue then. if you have multiple running clients on different terminals it shouldn't be a problem

**Comment by ddonchuk** [comment]
> I don't see the issue then. if you have multiple running clients on different terminals it shouldn't be a problem

i recorded video with issues
https://monosnap.com/file/d1wm4zvDI0Zltr0WXO7rnWBB3xG0n9

**Comment by painor** [comment]
you can't run the same session multiple times. Telegram will only send updates to the latest running client.

if you want to receive updates you'll need a new session for each client.

**Comment by ddonchuk** [comment]
can i save connection in db and work with client without connect? i see that client diefferent before and after connect
![image](https://user-images.githubusercontent.com/59068428/142059558-97ac980c-981f-4e9d-9c04-61042ed4a73b.png)

**Comment by painor** [comment]
GramJS returns a SessionString that you can save in your DB if you want.

you can use the same session string in the same IP to send messages 

You would need a different session string if you want to receive messages/updates. it's a telegram limitation

**Comment by ddonchuk** [comment]
okay thank
