### ISSUE TITLE
MTProtoSender memory leaks

### ISSUE THREAD

**Issue by ahdruwa** [gram-js/gramjs#192]
When running for a long time, gramjs consumes more and more memory, even at idle. Presumably, this happens because the `_lastAcks` array contained in the `MTProtoSender._sendLoop` class method is not cleared in any way. You can see this behavior in the example code as well.

Also, if I understand correctly, there's another problem with memory. The thing is in RequestState, which contains `Api.MsgsAck`, the promise doesn't complete, and that causes the `_pendingStates` array to grow.

![image](https://user-images.githubusercontent.com/43544886/141381071-1aee12d4-f273-4dab-abf3-b8d44fed6726.png)

**Comment by painor** [comment]
hey, thank you for your investigation. You are correct about msgAcks. they shouldn't resolve (nor be added to the array). I've tried to fix both of these in 1.10.8 please take a look

**Comment by ahdruwa** [comment]
Yes, it works. Thank you very much for the quick solution to the problem
