### ISSUE TITLE
PEER_ID_INVALID with some users

### ISSUE THREAD

**Issue by floor12** [gram-js/gramjs#196]
Hi. May be somebody could help me...

`Api.messages.GetDialogs` returns a list of dialogs with users, chats and groups with the ids and access hashes. But when i try to load latest messages with `Api.messages.GetHistory` method, i can do it only from users from my phone book. When i try to fetch `Api.messages.GetHistory` with the user, who already has a chat with me, but not exists on my phone book, i got code and **PEER_ID_INVALID** error.
I dont understand how to fetch history of this types of users...

**Comment by floor12** [comment]
I also cannot send message these users with `Api.messages.SendMessage`, i use `Api.InputPeerUser` with valid userId and accessHash...

**Comment by painor** [comment]
try using client.getDialogs and client.getMessages  https://gram.js.org/beta/classes/client_telegramclient.telegramclient.html#getmessages

**Comment by floor12** [comment]
thanx. it helped a lot!

**Comment by floor12** [comment]
@painor may you can help me with one more problem. I dont understand how i can mark chat as read? I found the only one way with `Api.messages.ReadHistory()`. But it doesn't work with all groups, with some groups it throws PEER_ID_INVALID error.I create `inputEntity` with `clientgetInputEntity()` or manually with the same negative result with some groups...

**Comment by painor** [comment]
there are 2 different functions for that.
`Api.messages.ReadHistory` for small chats and users(not supergroup)
and 
`Api.channels.ReadHistory` for supergroups and channels.

**Comment by floor12** [comment]
Oh yes... Thanx a lot.
