### ISSUE TITLE
Connect to the proxy and log in TG, but the IP still shows the source server IP, not the proxy IP

### ISSUE THREAD

**Issue by chougaigai** [gram-js/gramjs#197]
Connect to the proxy and log in TG, but the IP still shows the source server IP, not the proxy IP

**Comment by painor** [comment]
if you use mtproxies it'll show your ip not the proxy

**Comment by 594904020** [comment]
no  use MTProxy

**Comment by painor** [comment]
you might have used your IP without a proxy before then. It's telegram that picks what IP to show.
