### ISSUE TITLE
RPCError: 406: UPDATE_APP_TO_LOGIN

### ISSUE THREAD

**Issue by jayserjune** [gram-js/gramjs#199]
What wrong with this?
UnhandledPromiseRejectionWarning: RPCError: 406: UPDATE_APP_TO_LOGIN (caused by auth.SendCode)

**Comment by vulongc3** [comment]
I have the same issue, the library worked yesterday

**Comment by jayserjune** [comment]
> 

I can't find the official explanation

**Comment by vulongc3** [comment]
https://core.telegram.org/method/auth.sendcode
I find 406 is the error code for login too many times, but I don't think I logged in that much

**Comment by vulongc3** [comment]
This error is from this [issue](https://github.com/LonamiWebs/Telethon/issues/3215) of Telethon library

**Comment by MichaelCasaDev** [comment]
Same problem to me, waiting for an update...

**Comment by Asjas** [comment]
If you have the same issue, please react with a thumbs-up (👍) emoji to the original post rather than posting another comment to avoid notifying everyone.

**Comment by zhongfly** [comment]
> I can't find the official explanation

https://core.telegram.org/api/layers#layer-133
Telegram switch to 64-bit identifiers for users, groups, supergroups and channels

**Comment by Pew0h** [comment]
We need to wait an update of GramJS ?

**Comment by MichaelCasaDev** [comment]
> We need to wait an update of GramJS ?

Yes...

**Comment by ddaniel987** [comment]
Fix this ASAP, please!

**Comment by painor** [comment]
Fixed in 2.0.0 https://www.npmjs.com/package/telegram/v/2.0.0

**Comment by bwithai** [comment]
`pip install -U Telethon `
