### ISSUE TITLE
 Error: Cannot cast to any kind of peer

### ISSUE THREAD

**Issue by AndrewTheRocket** [gram-js/gramjs#200]
Hello!
After 2.0 update I have a problem with getting group id.
My code dont have any changes before 2.0 update of this package.

When im trying to get group id, i have a error:
"Cannot cast https://t.me/linkToAnyGroup to any kind of peer."

Im using js, not ts.

Here is my code:

```js
async function getGroupId() {
    const result = await client.invoke(
        new Api.channels.GetFullChannel({
            channel: tgLinkFromInput,
        })
    );
    let jsonResult = JSON.stringify(result, null, 2);
    let parsedResult = JSON.parse(jsonResult);
    return parsedResult['fullChat']['id'];
}
```

**Comment by sumboid** [comment]
Noticed same behavior of `sendMessage`, not able to send message by `nickname` nor `phone` with same error.

**Comment by painor** [comment]
With the new updates telegram has made ids 64bit (bigInts in JS) and stopped older layers from working. 
GramJS now converts strings to IDs because they can't be normal numbers anymore and that has broken link and phone resolving. 

This will be fixed soon. For phones you will be required to add a "+" and for links it'll work as it used to.

**Comment by AndrewTheRocket** [comment]
> With the new updates telegram has made ids 64bit (bigInts in JS) and stopped older layers from working. GramJS now converts strings to IDs because they can't be normal numbers anymore and that has broken link and phone resolving.
> 
> This will be fixed soon. For phones you will be required to add a "+" and for links it'll work as it used to.

didnt work for me.
what is right format?

I tried https://t.me/+linkToGroup

**Comment by painor** [comment]
Check the latest version. 2.0.2

Use https://t.me/linkToGroup

**Comment by sumboid** [comment]
@painor sending messages by username looks working however phone number case is not working yet (version 2.0.2):
```
Cannot cast +7951XXXXXXX to any kind of peer
```

**Comment by AndrewTheRocket** [comment]
@painor 
its not fix a problem :<

same error.
Yep, i updated to 2.0.2

**Comment by sumboid** [comment]
Also just FYI because not sure if you plan to make `getEnitity` behavior as it was: it still does not work for phone number

**Comment by painor** [comment]
could you try 2.0.3

**Comment by painor** [comment]
what were you trying exactly? I just tried 
```ts
    const result = await client.invoke(
        new Api.channels.GetFullChannel({
            channel: "https://t.me/gramjschat",
        })
    );
    let jsonResult = JSON.stringify(result, null, 2);
    let parsedResult = JSON.parse(jsonResult);
    console.log(parsedResult['fullChat']['id']);

```
and it works fine

**Comment by sumboid** [comment]
@painor my case is a bit different:
```ts
await client.sendMessage(to, { message })
```
In case `to` is phone number I'm getting error about casting.

**Comment by painor** [comment]
how does the phone number look like ?

**Comment by sumboid** [comment]
Like `+79511234567`

**Comment by AndrewTheRocket** [comment]
@painor 
thanks for fix!

now i have another trouble, but i'll fix it for myself.

let chatIdFromEvent = message._chatPeer.channelId - result was string
Now its a NativeBigInt(value: )

**Comment by painor** [comment]
> Like `+79511234567`

ah ok I understand. 2.0.5 might fix it but if it doesn't I'll have to do more investigations :/

**Comment by painor** [comment]
> @painor thanks for fix!
> 
> now i have another trouble, but i'll fix it for myself.
> 
> let chatIdFromEvent = message._chatPeer.channelId - result was string Now its a NativeBigInt(value: )

Yes all values from the API are bigInt. you can also use message.chatId for that btw

**Comment by sumboid** [comment]
@painor `2.0.5` seems to fix the issue, thanks a lot :)
