### ISSUE TITLE
RPCError: 406: UPDATE_APP_TO_LOGIN

### ISSUE THREAD

**Issue by dankiv** [gram-js/gramjs#202]
When trying to sign in the first time it shows the error "RPCError: 406: UPDATE_APP_TO_LOGIN" 

A similar issue appear on Telethon yesterday, and was already fixed, check here:
https://github.com/LonamiWebs/Telethon/issues/3215

<img width="1131" alt="Screen Shot 2021-12-02 at 6 53 22 AM" src="https://user-images.githubusercontent.com/3027015/144360272-3b799529-def4-4f76-9f88-6b201ff7840d.png">

**Comment by Saifkhann** [comment]
Same issue I face!

**Comment by Saifkhann** [comment]
I just updated my telethon and it does not give the error

**Comment by kevin1193** [comment]
> I just updated my telethon and it does not give the error

How you do that?

**Comment by BramGamingNL** [comment]
> > I just updated my telethon and it does not give the error
> 
> How you do that?

I used this, but it did not work personally https://docs.telethon.dev/en/latest/basic/installation.html

**Comment by painor** [comment]
Update to latest https://www.npmjs.com/package/telegram/v/2.0.6 to fix that
