### ISSUE TITLE
Could not find a matching Constructor ID 

### ISSUE THREAD

**Issue by happymaskterriblefate** [gram-js/gramjs#204]
Recently on one of my apps that deals with larger channels, I started getting this error message:

`Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 2245446626. Most likely, a TLObject was trying to be read when it should not be read. Remaining bytes: 1000
`

This just started happening recently, within the last week. I've upgraded to the latest version and the issue persists. I'll dig in and see if I can debug, but just wanted to flag here.

Thanks!

**Comment by painor** [comment]
what version did this happen on btw? 2245446626 is  0x85d6cbe2 which should be the Api.Message class. you can console log that class and see if the ids match.

**Comment by happymaskterriblefate** [comment]
`2.0.4` is the version that i saw it on

**Comment by happymaskterriblefate** [comment]
fwiw i observed it on large channels like @disclosetv, and couldn't repo it on my 1 person test channel

**Comment by ivorynoise** [comment]
I also got a related error message. #205

**Comment by happymaskterriblefate** [comment]
This is fixed on `2.0.8`

**Comment by happymaskterriblefate** [comment]
Thank you @painor !

**Comment by N150429** [comment]
Is it will fix, if  i update telegram version,    "telegram": "^2.17.10", to latest
