### ISSUE TITLE
Can not insert correct channel and user parameters InviteToChannel method

### ISSUE THREAD

**Issue by quangkhoi1228** [gram-js/gramjs#212]
I use InviteToChannel method but it throws me some errors: code: 403, errorMessage: 'USER_INVALID'.
I have inserted channel and user from Api.messages.GetAllChats and Api.channels.GetParticipants results. 
Please help me to solve it.
**InviteToChannel code**
![image](https://user-images.githubusercontent.com/52962526/145353240-518970ab-0762-447c-a53d-ff0f1ce91a03.png)

**Bugs**
![image](https://user-images.githubusercontent.com/52962526/145353278-5d8464ab-7830-423c-af7a-754fc0985240.png)

**channel info from GetAllChats**
![image](https://user-images.githubusercontent.com/52962526/145353151-ed7df518-b617-44c1-8611-81f51a7c53ad.png)

**user info from GetParticipants ** 
![image](https://user-images.githubusercontent.com/52962526/145352994-b1eca078-b70f-453c-bb73-4b7e27ddd0e9.png)

**Comment by painor** [comment]
the accesssHash is a bigInt. 
![image](https://user-images.githubusercontent.com/30215770/145356122-533630c7-89f4-4031-b5e0-9b405105c26b.png)
you should either put it as String or add an n at the end
![image](https://user-images.githubusercontent.com/30215770/145356178-1ed2a16e-3f5b-484f-af83-d3c976ae06d9.png)

**Comment by quangkhoi1228** [comment]
thank you so much, it is working
