### ISSUE TITLE
replyMarkup and inline buttons

### ISSUE THREAD

**Issue by Wooody82** [gram-js/gramjs#217]
Hi,
How Could I send buttons inline or as keyboard with my message? Tried to import Button from telegram but does not work!
Thanks
I send the message like this now

`await client.sendMessage( CHAT_ID , {
					message: 'THE MESSAGE',
				})`

**Comment by painor** [comment]
You can use `buildReplyMarkup`
```ts
import {Button} from "telegram";
 // PS this function is not async
const markup = client.buildReplyMarkup(Button.inline("Hello!"));

await client.sendMessage(chat, {
    message: "click me!",
    buttons: markup,
}

```

you can find more at https://gram.js.org/beta/classes/client_telegramclient.telegramclient.html#buildreplymarkup

**Comment by Wooody82** [comment]
Thanks @painor 
I use require not import.. so this does not work with me! 
`const { Button, TelegramClient } = require("telegram");`

**Comment by painor** [comment]
Can you try doing this 
`const { Button } = require("telegram/tl/custom/button");`

**Comment by Wooody82** [comment]
Thanks.. I required that.. But the button not showing anyway.. I am not sure why!
```
const { Button } = require("telegram/tl/custom/button");
const markup = client.buildReplyMarkup(Button.inline("Hello!"));
await client.sendMessage(chat, {
    message: "click me!",
    buttons: markup,
}
```

**Comment by painor** [comment]
Are you using a bot account? only bots can use buttons

**Comment by Wooody82** [comment]
I have apiId and apiHash created from app page. and I use my account to login and save session.
```
	await client.start({
		phoneNumber: async () => await input.text("number?"),
		password: async () => await input.text("2F password?"),
		phoneCode: async () => await input.text("Code?"),
		onError: (err) => console.log(err),
	});
```

**Comment by Wooody82** [comment]
Thanks works fine with Bot account :-)
```
 await client.start({
    botAuthToken: "",
  });
```
https://github.com/gram-js/gramjs/blob/master/examples/main.ts#L40

**Comment by ravindu01manoj** [comment]
how to use button with command
