### ISSUE TITLE
How to get gAHash using gramjs?

### ISSUE THREAD

**Issue by mdl** [gram-js/gramjs#218]
I'm trying to call `Api.phone.RequestCall`.
If I use random value for `gAHash` like `Buffer.from("lol12345")` I'm getting an error `Call error RPCError: 400: DH_G_A_HASH_INVALID (caused by phone.RequestCall)`

**Comment by painor** [comment]
You can maybe use `messages.GetDhConfig` to get that.

**Comment by mdl** [comment]
> You can maybe use `messages.GetDhConfig` to get that.

Could you please share an example?

**Comment by painor** [comment]
A while ago I made a gist using another library , maybe you can use it and convert it to JS? https://gist.github.com/painor/537cdba90c21b8e64b3e156760775147

**Comment by pablodgonzalez** [comment]
@ghost that's is what I got
```typescript
function int_256_to_bytes(int: bigint) {
    const bytesArray = [];
    for (let i = 0; i < 32; i++) {
        let shift = int >> BigInt(8 * i)
        shift &= BigInt(255)
        bytesArray[i] = Number(String(shift))
    }
    return Buffer.from(bytesArray)
}


const dhc = await client.invoke(new Api.messages.GetDhConfig({
        version: config.version,
        randomLength: 256
    })) as Api.messages.DhConfig;


    const one = BigInt(1);
    const g = BigInt(dhc.g);
    const p = BigInt(`0x${dhc.p.toString('hex')}`)
    let a = BigInt(0);
    while (a <= 1 && a >= p) {
        a = BigInt(`0x${randomBytes(256).toString('hex')}`);
    }

    const g_a = (g ** a) % p;

    const shag_a = await sha256(int_256_to_bytes(g_a));
```
