### ISSUE TITLE
How to list all channels?

### ISSUE THREAD

**Issue by blacksabbatherMJ** [gram-js/gramjs#221]
I know I can use Api.messages.GetAllChats({exceptIds:[]}) to list all chats but cannot find a function to list all the channels I'm in. Please advise

**Comment by painor** [comment]
You can try iterating over https://gram.js.org/beta/classes/client_telegramclient.telegramclient.html#getdialogs and filtering to channels only.

**Comment by blacksabbatherMJ** [comment]
Thank you; Now

**Comment by painor** [comment]
I would use the same manner for chats as well. it has more friendly methods and it handles pagination for you .

**Comment by blacksabbatherMJ** [comment]
Do you mind show the sample code of use getDialogs to list all chats? I couldn't find it. I only know the way to list all channels as below:
const dialogs = await client.getDialogs();
dialogs.forEach(
dialog=>{
if(dialog.isChannel){
console.log(dialog.title);
}
}
)

**Comment by painor** [comment]
by chats you mean groups? 
You can do dialog.isGroup
if you want only legacy chats you can do
dialog.isGroup && !dialog.isChannel

**Comment by blacksabbatherMJ** [comment]
No I'm afraid this one "dialog.isGroup && !dialog.isChannel" doesn't work. Now I use className == "Chat" to list all chats and className=="Channel" to list all channels
