### ISSUE TITLE
How can i join to private group/dialog

### ISSUE THREAD

**Issue by ddonchuk** [gram-js/gramjs#224]
when i use method with link like   https://t.me/+KktwQzDOMh0xOTVi, it's not work.
```
const result = (await client.invoke(
            new Api.channels.JoinChannel({
              channel: linkFromMessage,
            })
          )) as any;
```
How can i join to private group/dialog ?
![image](https://user-images.githubusercontent.com/59068428/147858035-5502fba2-ea7b-4c1d-826b-3908f96a10c0.png)

**Comment by painor** [comment]
JoinChannel is for public channels with usernames. 
you'll need https://gram.js.org/tl/messages/ImportChatInvite

**Comment by ddonchuk** [comment]
> 

it's work. Thanks!
