### ISSUE TITLE
Get private group ID from invite link

### ISSUE THREAD

**Issue by elBarkey** [gram-js/gramjs#238]
How to get group chat ID from invite link like http://t.me/+hash
I tried  to use https://gram.js.org/tl/messages/ImportChatInvite the RESULT is:
`400 | USER_ALREADY_PARTICIPANT`

**Comment by painor** [comment]
you can use https://gram.js.org/tl/messages/CheckChatInvite

**Comment by elBarkey** [comment]
Thank you, that works!
