### ISSUE TITLE
[ERROR] - [TypeError: this._sendArray is not a function] improvements suggestions

### ISSUE THREAD

**Issue by NBMSacha** [gram-js/gramjs#240]
Hey, I already talked about this on another issue, but I think it's better to create a new one specially for this as it's a bit critical.

This issue happens when a lot of sessions are open on the same script, maybe a memory leak.

`[2022-01-17T15:44:01.881Z] [ERROR] - [TypeError: this._sendArray is not a function]`

Three things need to be improved here : 

- Error should be more verbose (the _sendArray isn't the real error here, there is something behind)
- Error should be catchable
- Error shouldn't lead to a stop of the running process

In my script for example, I'm using gramJS to manage accounts, and when I get this error, the while loop stops processing even if the script isn't killed. That's a big problem.

**Comment by painor** [comment]
Did you manage to reproduce the error ? I want to know where it exactly happen so I can fix those issues.

**Comment by NBMSacha** [comment]
The problem is that it is an error fired by the "external" logger hardcoded in the lib, so I can't print the trace logs. I can reproduce this error, it happens randomly but always happens at least once every 12 hours.

**Comment by NBMSacha** [comment]
I sent you an email, if you want to check it.

**Comment by painor** [comment]
You can create your own custom logging mechanism if you want. 
I have pushed an update that might fix the issue tho. it was a typo.

**Comment by NBMSacha** [comment]
Ok, I'll re-install the lib right now on my server and I'll let you know if it fixes it. Did you check my mail? + Can you tell me more about the custom logging mechanism?
