### ISSUE TITLE
error Cannot cast +628xxxxxx to any kind of peer when chatting for the first time using a cellphone number or username

### ISSUE THREAD

**Issue by thaziz** [gram-js/gramjs#244]
error when chatting for the first time using a cellphone number or username.

code:
await client.sendMessage("+6285xxxx", { message: "Hello!" });

and get an error like this

throw new Error(`Cannot cast ${toWrite} to any kind of ${target}`);
          ^
Error: Cannot cast +628xxxxxx to any kind of peer

**Comment by painor** [comment]
1) Are you using a user or a bot?
2) are you sure it's not working with a real username?
3) what version of the library are you using?

**Comment by thaziz** [comment]
> * Are you using a user or a bot?
> * are you sure it's not working with a real username?
> * what version of the library are you using?

1. I use user
2. Sorry, apparently I can't send using a phone number
3. version 2.4.6

**Comment by thaziz** [comment]
> When you use a phone number it'll only send it to them if you have them as a mutual contact,

does that mean it can't for new numbers?

**Comment by painor** [comment]
you'll have to add them as contact first https://gram.js.org/tl/contacts/ImportContacts

**Comment by thaziz** [comment]
> When you use a phone number it'll only send it to them if you have them as a mutual contact,

Is there a function to check if the number is already in our contacts or not?

**Comment by painor** [comment]
not that I know of :/ 
you could probably use https://gram.js.org/tl/contacts/GetContacts to get a list of contacts and filter manually
