### ISSUE TITLE
click() method instead of client.invoke() + Api.messages.GetBotCallbackAnswer()

### ISSUE THREAD

**Issue by M4ss1ck** [gram-js/gramjs#245]
Since GramJS's core is based in Telethon, I would like to see something like Telethon's `message.click()` in GramJS as well.
In order to achieve a "click" I'm currently using `client.invoke()` and then using `Api.messages.GetBotCallbackAnswer()`

For example, to click the first button of a bot message, I have to do something like this:
```
await client.invoke(
    new Api.messages.GetBotCallbackAnswer({
         peer: "botusername",
         msgId: id,
         data: event.message.replyMarkup.rows[0].buttons[0].data,
    })
 );
```

Perhaps there's already an easier way I don't know about

**Comment by painor** [comment]
try using 2.5.0 https://gram.js.org/beta/classes/custom.CustomMessage.html#click

**Comment by M4ss1ck** [comment]
Thanks, `message.click()` did the trick!
