### ISSUE TITLE
error after login 

### ISSUE THREAD

**Issue by thoriq-dumet** [gram-js/gramjs#248]
I did a scan with qrcode and it worked, but I got the error after I received an incoming message

![Screenshot_1](https://user-images.githubusercontent.com/71113561/152802755-605a7c53-cb56-4776-8380-de7dacf61aae.png)
        return peer.userId.toString();
                           ^

TypeError: Cannot read properties of undefined (reading 'toString')
    at Object.getPeerId (C:\xampp\htdocs\atele\node_modules\telegram\Utils.js:997:28)
    at VirtualClass.init (C:\xampp\htdocs\atele\node_modules\telegram\tl\custom\message.js:51:30)
    at new VirtualClass (C:\xampp\htdocs\atele\node_modules\telegram\tl\api.js:242:22)
    at NewMessage.build (C:\xampp\htdocs\atele\node_modules\telegram\events\NewMessage.js:78:40)
    at _dispatchUpdate (C:\xampp\htdocs\atele\node_modules\telegram\client\updates.js:121:29)
    at _processUpdate (C:\xampp\htdocs\atele\node_modules\telegram\client\updates.js:101:5)
    at TelegramClient._handleUpdate (C:\xampp\htdocs\atele\node_modules\telegram\client\updates.js:90:9)
    at MTProtoSender._handleUpdate (C:\xampp\htdocs\atele\node_modules\telegram\network\MTProtoSender.js:527:18)
    at MTProtoSender._processMessage (C:\xampp\htdocs\atele\node_modules\telegram\network\MTProtoSender.js:408:15)

**Comment by painor** [comment]
can you share your code and the exact steps you used?

**Comment by painor** [comment]
save the string from session.save() ? just like a normal sign in

**Comment by thoriq-dumet** [comment]
> save the string from session.save() ? just like a normal sign in

**i get eror sir,**

C:\xampp\htdocs\atele\node_modules\telegram\client\auth.js:186
                throw new Error("Unexpected");
                      ^

Error: Unexpected
    at C:\xampp\htdocs\atele\node_modules\telegram\client\auth.js:186:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.signInUserWithQrCode (C:\xampp\htdocs\atele\node_modules\telegram\client\auth.js:206:9)
    at async C:\xampp\htdocs\atele\app2.js:21:14




**this my code :**  

const user = await client.signInUserWithQrCode({ apiId, apiHash },
        {
            onError: async function(p1,Error) {
                console.log("error", p1);
                // true = stop the authentication processes
                return true;
            },
            qrCode: async (code) => {
                console.log("Convert the next string to a QR code and scan it");
                console.log(
                    `tg://login?token=${code.token.toString("base64url")}`
                );
            
            },
            password: async (hint) => {
                // password if needed
                return "1111";
            }
        }
    );
  console.log("You should now be connected.");
  console.log(client.session.save());
    console.log(stringSession.save());
  await client.sendMessage("me", { message: "Hello!" });

**Comment by painor** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/30215770/152893907-6c5ac012-7d9b-46f4-8442-ecf0709a37d9.png)
My code : 
```ts
    const client = new TelegramClient(new StringSession(), apiId, apiHash, {});
    await client.connect();
    const user = await client.signInUserWithQrCode({ apiId, apiHash },
        {
            onError: async function(p1) {
                console.log("error", p1);
                // true = stop the authentication processes
                return true;
            },
            qrCode: async (code) => {
                console.log("Convert the next string to a QR code and scan it");
                console.log(
                    `tg://login?token=${code.token.toString("base64url")}`
                );

            },
            password: async (hint) => {
                // password if needed
                return "1111";
            }
        }
    );
    console.log("You should now be connected.");
    console.log(client.session.save());
    await client.sendMessage("me", { message: "Hello!" });

```

I used this website to convert the string to QR.
https://www.qr-code-generator.com/solutions/text-qr-code/

**Comment by painor** [comment]
did you use the string that was logged to the console and use that in StringSession ?

**Comment by thoriq-dumet** [comment]
> did you use the string that was logged to the console and use that in StringSession ?

**this is code  i use storeSession:**

const { StoreSession } = require('telegram/sessions');
const storeSession = new StoreSession("my_session3");

const client = new TelegramClient(storeSession, apiId, apiHash, {});

**Comment by thaziz** [comment]
Help me mr @painor

**Comment by painor** [comment]
I just tested it again and it works fine. not sure what you guys are doing wrong.

```ts
    const client = new TelegramClient(new StoreSession("testing"), apiId, apiHash, {});
    await client.connect();
    if (!await client.isUserAuthorized()){
        await client.signInUserWithQrCode({ apiId, apiHash },
            {
                onError: async function(p1) {
                    console.log("error", p1);
                    // true = stop the authentication processes
                    return true;
                },
                qrCode: async (code) => {
                    console.log("Convert the next string to a QR code and scan it");
                    console.log(
                        `tg://login?token=${code.token.toString("base64url")}`
                    );

                },
                password: async (hint) => {
                    // password if needed
                    return "1111";
                }
            }
        );
    }

    console.log("You should now be connected.");
    console.log(client.session.save());
    await client.sendMessage("me", { message: "Hello!" });

```

This will try to ask you to QR the code on first run and run directly on second run

**Comment by thaziz** [comment]
> I just tested it again and it works fine. not sure what you guys are doing wrong.
> 
> ```ts
>     const client = new TelegramClient(new StoreSession("testing"), apiId, apiHash, {});
>     await client.connect();
>     if (!await client.isUserAuthorized()){
>         await client.signInUserWithQrCode({ apiId, apiHash },
>             {
>                 onError: async function(p1) {
>                     console.log("error", p1);
>                     // true = stop the authentication processes
>                     return true;
>                 },
>                 qrCode: async (code) => {
>                     console.log("Convert the next string to a QR code and scan it");
>                     console.log(
>                         `tg://login?token=${code.token.toString("base64url")}`
>                     );
> 
>                 },
>                 password: async (hint) => {
>                     // password if needed
>                     return "1111";
>                 }
>             }
>         );
>     }
> 
>     console.log("You should now be connected.");
>     console.log(client.session.save());
>     await client.sendMessage("me", { message: "Hello!" });
> ```
> 
> This will try to ask you to QR the code on first run and run directly on second run

Thanks sir

**Comment by roj1512** [comment]
@thaziz please close the issue if your problem has been resolved. :)

**Comment by thaziz** [comment]
> > I just tested it again and it works fine. not sure what you guys are doing wrong.
> > ```ts
> >     const client = new TelegramClient(new StoreSession("testing"), apiId, apiHash, {});
> >     await client.connect();
> >     if (!await client.isUserAuthorized()){
> >         await client.signInUserWithQrCode({ apiId, apiHash },
> >             {
> >                 onError: async function(p1) {
> >                     console.log("error", p1);
> >                     // true = stop the authentication processes
> >                     return true;
> >                 },
> >                 qrCode: async (code) => {
> >                     console.log("Convert the next string to a QR code and scan it");
> >                     console.log(
> >                         `tg://login?token=${code.token.toString("base64url")}`
> >                     );
> > 
> >                 },
> >                 password: async (hint) => {
> >                     // password if needed
> >                     return "1111";
> >                 }
> >             }
> >         );
> >     }
> > 
> >     console.log("You should now be connected.");
> >     console.log(client.session.save());
> >     await client.sendMessage("me", { message: "Hello!" });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will try to ask you to QR the code on first run and run directly on second run
> 
> Thanks sir

hello sir i have tried it but when we do the first scan it stops here, then i run it again and the new scan runs, does it have to be scanned twice? thanks @painor 

![image](https://user-images.githubusercontent.com/34264066/154173256-003b03b2-ca47-4edc-9285-d8cdd5329a15.png)

**Comment by painor** [comment]
it changes servers because your account is DC5 that's all. it's part of the processes

**Comment by jeffersonveloso** [comment]
How to stop qrcode generation after reading qrcode and connecting?
