### ISSUE TITLE
How to use Api.ReplyMarkup

### ISSUE THREAD

**Issue by Nafidinara** [gram-js/gramjs#252]
Hello thanks for making this, Im trying to send message to channel with markup. but Im getting this error : 
`Error: Required object ReplyInlineMarkup of undefined is undefined`

this is the message that I send :
`const result = await client.invoke(new Api.messages.SendMessage({
        noWebpage: true,
        silent: true,
        background: true,
        clearDraft: true,
        peer: new Api.InputPeerChannel({
            channelId:1680943xxxn,
            accessHash:6967653601753368xxxn
        }),
        replyToMsgId: 6872073,
        message: "hello",
        randomId: 1848690,
        replyMarkup: new Api.ReplyInlineMarkup({
                "buttons": [{
                    "text": "� Open youtube �",
                    "url": "https://youtube.com"
                }),
        scheduleDate: 789917,
    }));
    console.log(result);`
    
    Can you give some clear example to do this?

**Comment by butthx** [comment]
try like this
```js 
new Api.ReplyInlineMarkup({
  rows : [
    new Api.KeyboardButtonRow({
       buttons : [
         new Api.KeyboardButtonUrl({
            text : "button text",
            url : "button url"
         })
       ]
    })
  ]
})
```

**Comment by Nafidinara** [comment]
> try like this
> 
> ```js
> new Api.ReplyInlineMarkup({
>   rows : [
>     new Api.KeyboardButtonRow({
>        buttons : [
>          new Api.KeyboardButtonUrl({
>             text : "button text",
>             url : "button url"
>          })
>        ]
>     })
>   ]
> })
> ```
Hi @butthx , thanks for reply, I've been try, but still nothing

**Comment by butthx** [comment]
> > try like this
> > ```js
> > new Api.ReplyInlineMarkup({
> >   rows : [
> >     new Api.KeyboardButtonRow({
> >        buttons : [
> >          new Api.KeyboardButtonUrl({
> >             text : "button text",
> >             url : "button url"
> >          })
> >        ]
> >     })
> >   ]
> > })
> > ```
> 
> Hi @butthx , thanks for reply, I've been try, but still nothing

any error throwing? or you can see this answer. [#217](https://github.com/gram-js/gramjs/issues/217#issuecomment-1001073145) it hope help you.

**Comment by Nafidinara** [comment]
> 

no error showing sir, message has been sent, but not showing, or I need to put new `Api.MessageEntity({...})` too?

**Comment by butthx** [comment]
> > 
> 
> no error showing sir, message has been sent, but not showing, or I need to put new `Api.MessageEntity({...})` too?

should be no, btw are loggined as bot? inline keyboard only work with bot.

**Comment by Nafidinara** [comment]
> > > 
> > 
> > 
> > no error showing sir, message has been sent, but not showing, or I need to put new `Api.MessageEntity({...})` too?
> 
> should be no, btw are loggined as bot? inline keyboard only work with bot.

Ah okay, Im logged in as a user :). there is any way to do that with the user mode?

**Comment by butthx** [comment]
> > > > 
> > > 
> > > 
> > > no error showing sir, message has been sent, but not showing, or I need to put new `Api.MessageEntity({...})` too?
> > 
> > 
> > should be no, btw are loggined as bot? inline keyboard only work with bot.
> 
> Ah okay, Im logged in as a user :). there is any way to do that with the user mode?

nope ig

**Comment by Nafidinara** [comment]
ok thanks!
