### ISSUE TITLE
How to send messages in bold font?

### ISSUE THREAD

**Issue by blacksabbatherMJ** [gram-js/gramjs#253]
I use below code to send out messages:

new Api.messages.SendMessage({
                                        peer: new Api.InputPeerChat({"chatId":id}),
                                        message: message
                                })

if I put something like "**Dear customer**", it won't give me bold font but double stars. In telethon, I can use this way to send message in bold font

**Comment by butthx** [comment]
if you use raw api, you must parse that text to a valid entities manually or you can use 
```js 
client.sendMessage(peer,{
  message : "**text**",
  parseMode : "markdown"
})
```
it should be automatic parsing as valid entities. cmiiw :)

**Comment by blacksabbatherMJ** [comment]
Thanks but I don't think it works...

**Comment by blacksabbatherMJ** [comment]
This one works. Thank you~~~

**Comment by roj1512** [comment]
@blacksabbatherMJ please close the issue and if you had questions like this, ask in the discussions.

**Comment by BaalDev-Solutions** [comment]
Where is this documented?
