### ISSUE TITLE
Outdated content about `How do I stop logging?` on GitBook docs

### ISSUE THREAD

**Issue by amirrh6** [gram-js/gramjs#255]
Hi! Thanks for maintaining such a great library.

I found outdated content on https://painor.gitbook.io/gramjs/faq about 'How do I stop logging?':

```
import {Logger} from "telegram/extensions";
Logger.setLevel("none"); // no logging
Logger.setLevel("error"); // only errors
Logger.setLevel("none"); // warnings too
Logger.setLevel("none"); // info too
Logger.setLevel("debug"); // everything
```

Up to date (correct) content is already available on https://painor.gitbook.io/gramjs/faq:

```
client.setLogLevel("none"); // no logging
client.setLogLevel("error"); // only errors
client.setLogLevel("warn"); // warnings too
client.setLogLevel("info"); // info too
client.setLogLevel("debug"); // everything
```

Generally, I suggest uniting every documentation content [Website, Website Beta Section, GitBook docs and ...] to a single cleaned-up resource.
In some weird cases, some essential info about objects are only found inside Typescript definition files!
I'd love to help on doing so.

Best wishes!

**Comment by painor** [comment]
I've updated gitbook,

The documentation kinda changed to https://gram.js.org/faq and https://gram.js.org/beta and the gitbook version is being slowly ditched.

**Comment by csjui** [comment]
I have set client.setLogLevel("none"); but I still get the following log messages on every connect. Can this be avoided?

[2023-06-12T14:39:38.739] [INFO] - [Running gramJS version 2.17.0]
