### ISSUE TITLE
Webpack fails

### ISSUE THREAD

**Issue by mu3** [gram-js/gramjs#26]
> npx webpack

    [BABEL] Note: The code generator has deoptimised the styling of .../gramjs/gramjs/tl/types/index.js as it exceeds the max of 500KB.

    Version: webpack 4.41.2
    Time: 16694ms
    Built at: 04/19/2020 8:19:13 PM
        Asset      Size  Chunks             Chunk Names
    gramjs.js  4.43 MiB    main  [emitted]  main
    Entrypoint main = gramjs.js
    [./gramjs/Helpers.js] 8.11 KiB {main} [built]
    [./gramjs/Password.js] 9.07 KiB {main} [built]
    [./gramjs/Utils.js] 40.5 KiB {main} [built]
    [./gramjs/Version.js] 25 bytes {main} [built]
    [./gramjs/client/TelegramClient.js] 95.7 KiB {main} [built]
    [./gramjs/crypto/RSA.js] 3.76 KiB {main} [built]
    [./gramjs/errors/Common.js] 11.1 KiB {main} [built]
    [./gramjs/errors/RPCBaseErrors.js] 12.4 KiB {main} [built]
    [./gramjs/errors/RPCErrorList.js] 208 KiB {main} [built]
    [./gramjs/errors/index.js] 3.57 KiB {main} [built]
    [./gramjs/events/index.js] 3.64 KiB {main} [built]
    [./gramjs/index.js] 559 bytes {main} [built]
    [./gramjs/network/index.js] 713 bytes {main} [built]
    [./gramjs/sessions/index.js] 227 bytes {main} [built]
    [./gramjs/tl/index.js] 383 bytes {main} [built]
        + 318 hidden modules

    ERROR in ./node_modules/better-sqlite3/build/better_sqlite3.node 1:0
    Module parse failed: Unexpected character '�' (1:0)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    (Source code omitted for this binary file)
    @ ./node_modules/better-sqlite3/lib/database.js 11:18-57
    @ ./node_modules/better-sqlite3/lib/index.js
    @ ./gramjs/sessions/SQLiteSession.js
    @ ./gramjs/client/TelegramClient.js
    @ ./gramjs/index.js

    ERROR in ./node_modules/integer/build/integer.node 1:0
    Module parse failed: Unexpected character '�' (1:0)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    (Source code omitted for this binary file)
    @ ./node_modules/integer/lib/index.js 3:31-63
    @ ./node_modules/better-sqlite3/lib/index.js
    @ ./gramjs/sessions/SQLiteSession.js
    @ ./gramjs/client/TelegramClient.js
    @ ./gramjs/index.js

**Comment by painor** [comment]
what node version is that ?

**Comment by mu3** [comment]
v12.11.1

**Comment by mu3** [comment]
I'm  actually planning to use a session stored in sqlite

**Comment by watzon** [comment]
You likely need to downgrade to an 11.x.x version, Node 12 messed something up and SQLite doesn't compile.

**Comment by painor** [comment]
also I think you need to put it as external https://webpack.js.org/configuration/externals/

**Comment by mu3** [comment]
externals: {
"better-sqlite3": 'better-sqlite3'
},

This fixed the problem. Thank you!

Do I need it for importing a sqlite session?
And how can I save a session into sqlite file? (sorry for offtopic)

>

**Comment by watzon** [comment]
We need to make it an optional dependency, if you're not using the SQLiteSession you don't need it. I'll add that as a new issue so I don't forget.

**Comment by AndrewLaneX** [comment]
This issue should be fixed now, please re-open this issue if the problem persists.
