### ISSUE TITLE
getFullChannel for private channels

### ISSUE THREAD

**Issue by bobo23** [gram-js/gramjs#262]
Hi, we get channels like this:

```javascript
function channel (channels) {
    return channels.map(function (channel) { 
        return new Api.channels.GetFullChannel({
            channel
        });
    });
}
```

But for a private channel (that we already have joined) we don't get the username. And the private link (like https://t.me/+zerjwid0kwdfe03a) is also not working. With our last client we worked with it was possible, because we used (like in the telgram api docu: https://core.telegram.org/constructor/inputChannel) the channel id and the access hash.

Is there a possibility to get the infos of private channels we previously joined?

**Comment by painor** [comment]
if you want a list of channels/groups that you are already in you can use, https://gram.js.org/beta/classes/TelegramClient.html#iterDialogs

if you want to convert that link to a chat you can use https://gram.js.org/tl/messages/CheckChatInvite

**Comment by bobo23** [comment]
Thank you, that helped!
