### ISSUE TITLE
How to listen on delete Message

### ISSUE THREAD

**Issue by Nafidinara** [gram-js/gramjs#263]
Hello, I want to  add listener that triggered when some message in channel got delete, how I can do that?

**Comment by painor** [comment]
You can use the MessageDeleted event for that https://gram.js.org/beta/classes/custom.DeletedMessage.html

**Comment by Nafidinara** [comment]
like `client.addEventHandler(eventPrint, new UpdateDeleteChannelMessages();` ?

**Comment by Nafidinara** [comment]
> You can use the MessageDeleted event for that https://gram.js.org/beta/classes/custom.DeletedMessage.html

Ok sir thanks for help!
