### ISSUE TITLE
Invalid bots methods

### ISSUE THREAD

**Issue by Gercov** [gram-js/gramjs#265]
From a bot account I'm trying use: `GetMessageStats`, `GetMessagePublicForwards` and `GetMegagroupStats` and all of them throw `BOT_METHOD_INVALID` error, although the documentation it is written that they can call them

**Comment by painor** [comment]
The documentation uses the official telegram site to pull that info, https://core.telegram.org/method/stats.getMessageStats 
it doesn't say whether it can or not so it defaults to True when generating the documentation.

In short the documentation is wrong and bots can't use those methods
