### ISSUE TITLE
addEventHandler: how to listen for message send from client.sendMessage

### ISSUE THREAD

**Issue by batara666** [gram-js/gramjs#273]
currently when a message send by `Api.messages.SendMessage`, the message are not logged in `client.addEventHandler(eventPrint, new NewMessage({}));`

**Comment by painor** [comment]
Yes this is by design, otherwise you would end up with infinite loops quite easily, the update is received as a result to the function call not in the update handlers

**Comment by batara666** [comment]
I don't understand, I want to do something like:

```js
// the handler only listen for a message, no reply or no message send
client.addEventHandler(eventPrint, new NewMessage({}));

// send message from database
var result = await client.invoke(
    new Api.messages.SendMessage({
      peer: obj["target_chat_id"],
      message: obj["text"],
    })
);
```

Is there any non-hacky way to still receive our own message that send from `Api.messages.SendMessage` ?

**Comment by painor** [comment]
well I wouldn't say "non hacky" but you can do the following.
```ts
const result = await client.sendMessage(...); // you need client.sendMessage not .invoke
eventPrint({message:result})
```
