### ISSUE TITLE
Send message in channel post thread

### ISSUE THREAD

**Issue by mdl** [gram-js/gramjs#276]
What is correct way to send a message within channel post thread. I'm trying to send message like this:
`client.sendMessage(targetChat, {
   message: 'Some message',
   replyTo: post.id
  })`

Result is `RPCError: 400: CHAT_ADMIN_REQUIRED (caused by messages.SendMessage)`

**Comment by painor** [comment]
well it's a bit more complicated than that. 
You first have to call.

`https://gram.js.org/tl/messages/GetDiscussionMessage` then get the first message from the result and the appropriate chat,
you will then be able to send messages to it, 

A new release today will have this feature  built in.

**Comment by mdl** [comment]
@painor thanks, once this feature is released, could you please provide full example on how to comment under post in channel to make sure I don't miss anything?

**Comment by painor** [comment]
it's been pushed to npm already (2.5.3).

```ts
await client.sendMessage(
    targetChat,
    {
        message:"test",
        commentTo:post.id,
    }
)

```

**Comment by mdl** [comment]
@painor it works but for some channels I'm getting an error `Send message error {"code":400,"errorMessage":"MSG_ID_INVALID"}`

**Comment by painor** [comment]
> @painor it works but for some channels I'm getting an error `Send message error {"code":400,"errorMessage":"MSG_ID_INVALID"}`

Well are you sure you can comment on those IDs ? sometimes a channel deletes the message after posting.

**Comment by mdl** [comment]
yes, correct, thanks for help
