### ISSUE TITLE
Error: Cannot find module './crypto/crypto'

### ISSUE THREAD

**Issue by Nafidinara** [gram-js/gramjs#277]
Hello, I have this issues when try to use gramjs in client-side, Im using browserify to use `require('modules')` in the client side. Any solution for this?
![image](https://user-images.githubusercontent.com/44227618/156911821-e6282a1d-78cb-4d48-8157-3c47a4b81107.png)

**Comment by painor** [comment]
how are you bundeling it? the easiest way would be to clone the repo, use webpack to generate a js file and require that

**Comment by Nafidinara** [comment]
can you explain me? Im already using webpack, but still require not defined
![image](https://user-images.githubusercontent.com/44227618/156927994-a9562cf1-e69b-4433-8d80-dd02faf4a34f.png)
![image](https://user-images.githubusercontent.com/44227618/156928009-3be13090-e3f8-4c5f-90c4-a196a896f2d2.png)
@painor

**Comment by painor** [comment]
don't use webpack on your script. use it on the library only if you want to run it client side.

just do theses steps.

1) clone the repo
2) cd to repo
3) npm i
4) call `webpack`
5) you will find a new file in a folder called browser. 
6) either require("") the new file in your script or <script src="the file"> in your HTML

**Comment by painor** [comment]
don't use webpack on your script. use it on the library only if you want to run it client side.

just do theses steps.

1) clone the repo
2) cd to repo
3) npm i
4) call `webpack`
5) you will find a new file in a folder called browser. 
6) either require("") the new file in your script or <script src="the file"> in your HTML

**Comment by painor** [comment]
don't use webpack on your script. use it on the library only if you want to run it client side.

just do theses steps.

1) clone the repo
2) cd to repo
3) npm i
4) call `webpack`
5) you will find a new file in a folder called browser. 
6) either require("") the new file in your script or <script src="the file"> in your HTML

**Comment by Nafidinara** [comment]
> don't use webpack on your script. use it on the library only if you want to run it client side.
> 
> just do theses steps.
> 
> 1. clone the repo
> 2. cd to repo
> 3. npm i
> 4. call `webpack`
> 5. you will find a new file in a folder called browser.
> 6. either require("") the new file in your script or <script src="the file"> in your HTML

![image](https://user-images.githubusercontent.com/44227618/156929234-37c14a65-1e06-4504-9208-fd4544970627.png)

Unfortunately got this error when try to build

**Comment by Nafidinara** [comment]
any solution of this sir? @painor

**Comment by painor** [comment]
just do webpack without any flags.
Did you npm i?
What node version do you have?

**Comment by painor** [comment]
[telegram.zip](https://github.com/gram-js/gramjs/files/8192966/telegram.zip)
In any case here is a zip file that contains the bundeld file while you fix your issue

**Comment by Nafidinara** [comment]
yes, thank you, maybe its problem with my npm version

**Comment by Nafidinara** [comment]
Sorry sir, one questions again, how can I use the NewMessage events?
![image](https://user-images.githubusercontent.com/44227618/157036765-2fe803fe-361d-40ee-95b5-8b8900467977.png)

**Comment by Nafidinara** [comment]
Always get this problem with zip file that you sent

> [telegram.zip](https://github.com/gram-js/gramjs/files/8192966/telegram.zip) In any case here is a zip file that contains the bundeld file while you fix your issue

`Cannot destructure property 'NewMessage' of 'telegram.events' as it is undefined.`

**Comment by painor** [comment]
What code did you try?

**Comment by Nafidinara** [comment]
> What code did you try?

try to import `const { NewMessage } = telegram.events;`

**Comment by painor** [comment]
ah, for browsers events isn't there. It's in TelegramClient.events

**Comment by Nafidinara** [comment]
> ah, for browsers events isn't there. It's in TelegramClient.events

seems not working. `client.addEventHandler(getMessageEvent, new NewMessage({chats : [1618359068,1519789792,1747246894]}));` Im try this but nothing happened, when I try in server side, its working well

**Comment by Nafidinara** [comment]
![image](https://user-images.githubusercontent.com/44227618/157058292-96eda365-cea6-49ed-a942-894fde6f9c6c.png)

**Comment by painor** [comment]
Make sure to call client.getMe at least once so that telegram  can send  you updates.

**Comment by Nafidinara** [comment]
> Make sure to call client.getMe at least once so that telegram can send you updates.

been trying and `client.getMe` working

**Comment by painor** [comment]
if it's still not working feel free to send the full code and I'll try it

**Comment by Nafidinara** [comment]
> 

https://github.com/Nafidinara/tg-scrapper-bot
check this sir, I hope you can help me, really need this :(

**Comment by painor** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/30215770/157068980-e9c8732c-4f25-43f3-bd4e-b426222b3f88.png)

You had some issues in your code. You are calling addEventHandler in two places instead of one. 

Your grab function returns nothing which means x.addEventHandler will not work.

```ts
const getMessageEvent = (event) => {
    let data = event.message;
    Handler.appendScannerTextarea(data.text);
}

```
```ts

client = new TelegramClient(stringSession, api_id, api_hash, {connectionRetries: 5});
await client.connect();
const me = await client.getMe();
Handler.appendScannerTextarea('now you should be connected '+me.username);
client.addEventHandler(getMessageEvent, new NewMessage({chats: [-1001227726823]})); //testing 1227726823

```

If it's a channel don't forget to add -100 so that the library can find it easier.

**Comment by painor** [comment]
done

**Comment by Nafidinara** [comment]
Ok i found the problem, wrong in pass channel id :(. thanks sir for helping me, I'll close this
