### ISSUE TITLE
sendMessage() method

### ISSUE THREAD

**Issue by mirismaili** [gram-js/gramjs#28]
I expected a `sendMessage()` method in `TelegramClient`. Like [`send_message()` in Telethon](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.messages.MessageMethods.send_message).

If it hasn't been implemented yet, is there an alternative way to send messages?

**Comment by watzon** [comment]
There is a lot that hasn't been implemented yet. I am working on all of that, for now you can follow #25 to get updated.

**Comment by mirismaili** [comment]
@watzon OK. Thanks anyway. I wait or if it's possible I will try to help you.

**Comment by watzon** [comment]
There's a lot to be done, but I hope to have something workable by the end of next week.

**Comment by painor** [comment]
You can use raw api for now  https://gram.js.org/methods/messages/send_message.html
