### ISSUE TITLE
Iterate messages from a specific date range 

### ISSUE THREAD

**Issue by phatnhse** [gram-js/gramjs#283]
Hi team, I want to create a method to get the messages in some specific range (for instance: a range of 2 days). 

I know there is an option to specify the `offsetDate` with api `getMessages` (or `iterMessages`)  but it seems not supported for this case since it will try get the all the messages before that day only. Do we have something like `startDate` and `endDate` or any alternative way to help with my query? 

Hope can get your response. Thanks

**Comment by painor** [comment]
There is no in built way in telegram for that sadly, what you can do is to get all messages from `startDate ` and `endDate` is:

Get the last message you want to get using `offsetDate` and pass it to `minId` ( this is the `startDate`) and then use the `endDate` for the `offsetDate`

**Comment by phatnhse** [comment]
appreciate for your help! setting `minId` and `offsetDate` did the trick!

**Comment by bhnybrohn** [comment]
please @phatnhse  can you share how you did this

**Comment by KirisakiAria** [comment]
> offsetDate

+1

**Comment by KirisakiAria** [comment]
> please @phatnhse can you share how you did this

+1
