### ISSUE TITLE
GetChatInviteImporters returns an error

### ISSUE THREAD

**Issue by hailovigor** [gram-js/gramjs#284]
Hello everyone.
I can't use the GetChatInviteImporters function.
`const result = await client.invoke(new Api.messages.GetChatInviteImporters({`
`       peer: "FLJHTIT",`
`       link: "https://t.me/+gcakHiMKKuAxOWYy"`
`}));`

I get an error:

`Error: Cannot cast undefined to any kind of undefined`

What could be the problem? Thanks.

**Comment by painor** [comment]
as you can see in https://gram.js.org/tl/messages/GetChatInviteImporters , it has more params than just peer and link

**Comment by hailovigor** [comment]
I think I did it. I didn't know about the designation of required fields.

Thank you so much for the quick response!
