### ISSUE TITLE
Upload from browser?

### ISSUE THREAD

**Issue by NumairAwan** [gram-js/gramjs#287]
How can i upload from browser? file path? 

i tried this:

```
$('input[type=file]').change(async function () {
     console.log(this.files[0]);
     
     const result = await client.sendFile("me",{
        file: this.files[0].name,
     });
     
     console.log(result); // prints the result
     
  });
```
but got 

> _TypeError: fs_1.promises is undefined_

**Comment by painor** [comment]
why are you passing the name? can't you just pass the file directly? 
Another way of doing it is to convert it to a buffer and use the CustomFile class.

**Comment by NumairAwan** [comment]
If i pass the file object then still getting the error like "you cannot pass file object".

Can you give any example of CustomFile?

**Comment by NumairAwan** [comment]
When using CustomFile i am also getting error _`ReferenceError: CustomFile is not defined`_

```
 $('input[type=file]').change(async function () {
    
     var tmppath = URL.createObjectURL(this.files[0]);
     
     const toUpload = new CustomFile(this.files[0].name, this.files[0].size, tmppath);
     
     const result = await client.sendFile(-1001681244853 ,{
        file: toUpload,
        workers: 1,
     });
     
     console.log(result); // prints the result
     
  });
```

**Comment by painor** [comment]
obviously you have to import it. 
it should be in telegram.upload

**Comment by NumairAwan** [comment]
here is the full code that should work. 

```
$('input[type=file]').change(async function () {

  var reader = new FileReader();
  reader.onload = async function() {

    var arrayBuffer = this.result,
      array = new Uint8Array(arrayBuffer),
      binaryString = String.fromCharCode.apply(null, array);

     const toUpload = new CustomFile(this.files[0].name, this.files[0].size, array);
    
    const result = await client.uploadFile(-1001681244853 ,{
       file: toUpload,
       workers: 1,
    });
     
    console.log(result); // prints the result
  }
  reader.readAsArrayBuffer(this.files[0]);
       
  });
```

And i can't use import in browser.

**Comment by painor** [comment]
No it only auto loads the Telegram class. 
custom file should be telegram.upload.CustomFile

**Comment by NumairAwan** [comment]
still the same `TypeError: telegram.upload is undefined`

**Comment by painor** [comment]
maybe try telegram.client.uploads.CustomFile
You can log the class to see where it's from. 
Also it's `constructor(name, size, path, buffer)` so if you have no path you should leave it empty

**Comment by NumairAwan** [comment]
Now CustomFile is working but getting other error;

```
$('input[type=file]').change(async function() {

    var filesize = this.files[0].size;
    var filename = this.files[0].name;

    var reader = new FileReader();
    reader.onload = async function() {

        var arrayBuffer = this.result,
            array = new Uint8Array(arrayBuffer),
            binaryString = String.fromCharCode.apply(null, array);

        const toUpload = new telegram.client.uploads.CustomFile(filename, filesize, '', arrayBuffer)

        console.log(toUpload);

        const result = await client.uploadFile(-1001681244853, {
            file: toUpload,
            workers: 1,
        });

        console.log(result); // prints the result

    }
    reader.readAsArrayBuffer(this.files[0]);

});
```

![image](https://user-images.githubusercontent.com/62851858/159565668-9dab3e5e-6fc1-4715-a472-a2744d6acc2a.png)

![image](https://user-images.githubusercontent.com/62851858/159565806-fbd9902b-fbba-4144-a15c-37b2d489ecb8.png)

**Comment by painor** [comment]
that's not how you upload a file. use client.sendFile

**Comment by NumairAwan** [comment]
Thank you very much @painor for help. Now it's working.

Here is the short and working code:

```
$('input[type=file]').change(async function() {

    var file = this.files[0];

    const toUpload = new telegram.client.uploads.CustomFile(file.name, file.size, '', file.arrayBuffer())

    const result = await client.sendFile(-1001681244853, {
        file: toUpload,
        workers: 1,
    });

    console.log(result); // prints the result

});
```

**Comment by ljs19923** [comment]
const toUpload = new telegram.client.uploads.CustomFile(file.name, file.size, '', file.arrayBuffer())

telegram is undefined for me. Do you know why?
