### ISSUE TITLE
Remove "this is a comment"

### ISSUE THREAD

**Issue by pheianox** [gram-js/gramjs#293]
Just drives me mad ))

**Comment by painor** [comment]
wops;

**Comment by painor** [comment]
https://github.com/gram-js/gramjs/commit/68c25b6d342da7dffc39c54223a94fbcee827610

**Comment by pheianox** [comment]
Thank you so much! Btw I really liked this project. I don't know why Node.js with gram-js seems to respond faster  than .NET Core 6.0 + TDLib
