### ISSUE TITLE
How do handle errors?

### ISSUE THREAD

**Issue by pheianox** [gram-js/gramjs#294]
I get INVALID_MESSAGE_ID way too often and I'm wondering if there's any way to handle errors
I'm thinking about this. 
```ts
client.addEventHandler(handleError, new ErrorEvent({}))
```
Am I missing something? Like catch doesn't catches those errors when for example sending message

**Comment by painor** [comment]
the error is usually caused by a request you did. 
So it's probably 
```
try {
    your request
} catch(e) {

}
```
