### ISSUE TITLE
TypeError due to undefined `peer.userId`

### ISSUE THREAD

**Issue by robin-hartmann** [gram-js/gramjs#299]
I get `TypeError: Cannot read properties of undefined (reading 'toString')` in `telegram\Utils.js:1040` (`return peer.userId.toString();`) when trying to handle new messages I sent myself.

This is the code I use to handle new messages:

```ts
client.addEventHandler(async (event) => {
  console.log('got new message!');
}, new NewMessage({}));
```

`got new message!` is never printed, because the error above is thrown before that can happen.

**Comment by robin-hartmann** [comment]
I think I already found the culprit and have opened PR #300. More information in the PR.

**Comment by painor** [comment]
did you client.addEventHandler before doing client.connect / client.start ?

**Comment by robin-hartmann** [comment]
I used `client.start` and even another API request (`await client.invoke(new Api.messages.GetAllChats({ exceptIds: [] }))`) beforehand successfully.

I also currently call `await client.getMe()` before `client.addEventHandler` as a workaround, because `getMe()` sets `userId`, as explained in the PR #300.
