### ISSUE TITLE
examples do not work

### ISSUE THREAD

**Issue by DestroyerIV** [gram-js/gramjs#30]
After compiling everything and trying to run the index.js file, it doesn't finish loading. In the HTML file the phone number box is disabled. I tried to start all the .js files and none of them initialize the connection.

When running /examples/main.js
```
(async () => {
^

TypeError: require(...) is not a function
    at Object.<anonymous> (/mnt/c/Users/Isco/Desktop/gramjs-master/examples/main.js:4:1)
```

When running /examples/simpleLogin.js
```
const phoneDiv = document.getElementById('phoneDiv')
                 ^

ReferenceError: document is not defined
    at Object.<anonymous> (/mnt/c/Users/Isco/Desktop/gramjs-master/examples/simpleLogin.js:1:18)
```

Does anyone know what that might be?

**Comment by painor** [comment]
are you trying to run them in a node environment instead of a normal browser ?.

**Comment by DestroyerIV** [comment]
> are you trying to run them in a node environment instead of a normal browser ?.

Obviously, but it still doesn't work

**Comment by IscoV** [comment]
> are you trying to run them in a node environment instead of a normal browser ?.

I use the following command in /example/main.js
`node main.js`
and shows the error indicated above

**Comment by DestroyerIV** [comment]
> are you trying to run them in a node environment instead of a normal browser ?.

I use the command 

`node main.js`

 in /example/main.js but it shows the error indicated above

**Comment by DestroyerIV** [comment]
Nobody? Really?

**Comment by Lonami** [comment]
People in the open source world have no obligation to attend to issues, and generally are busy doing other things. Your issue is open and will be reviewed when a maintainer has time and is willing to do so. It's only been 2 days, please be more patient or try to resolve it yourself.

**Comment by Lonami** [comment]
If you found a solution, please indicate which it is. If you didn't, please don't close the issue, because the issue still exists.

**Comment by foodornt** [comment]
bru, this is not supposed to be run in a node js environment

**Comment by painor** [comment]
it can run fine on the nodejs environment
