### ISSUE TITLE
Error: Cannot send requests while disconnected. You need to call .connect()

### ISSUE THREAD

**Issue by icanary** [gram-js/gramjs#303]
My app work fine, but sometimes it fall down with error:

**Error: Cannot send requests while disconnected. You need to call .connect()**, which begin run in endless cycle

then script die with another error:

`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

so my question is:

what is the bug with this:

`Error: Cannot send requests while disconnected. You need to call .connect()` ?

Why this sometimes run in endless cycle and never end? This definitely need to be fixed.

This bug was in version 2.5.* and now in 2.6.13 it has too.

Full error look like this:

```
Error: Cannot send requests while disconnected. You need to call .connect()
    at MTProtoSender.send (/code/node_modules/telegram/network/MTProtoSender.js:197:19)
    at Object.invoke (/code/node_modules/telegram/client/users.js:31:36)
    at async TelegramClient.getDC (/code/node_modules/telegram/client/TelegramClient.js:1120:28)
    at async TelegramClient._connectSender (/code/node_modules/telegram/client/telegramBaseClient.js:200:20)
    at async TelegramClient._borrowExportedSender (/code/node_modules/telegram/client/telegramBaseClient.js:243:22)
```

p.s.: right before this error it show this:

```
Error: Disconnect 
 at /code/node_modules/telegram/extensions/MessagePacker.js:106:33 
 at Array.forEach (<anonymous>) 
 at MessagePacker.rejectAll (/code/node_modules/telegram/extensions/MessagePacker.js:105:29) 
 at MTProtoSender._disconnect (/code/node_modules/telegram/network/MTProtoSender.js:247:25) 
 at MTProtoSender.disconnect (/code/node_modules/telegram/network/MTProtoSender.js:168:20) 
 at MTProtoSender._reconnect (/code/node_modules/telegram/network/MTProtoSender.js:728:24) 
 at /code/node_modules/telegram/network/MTProtoSender.js:721:22
```

Thanks.

**Comment by painor** [comment]
Are you sure it's not a network issue? maybe your internet got disconnected and the library was trying to reconnect forever?

**Comment by wind-hx** [comment]
> Are you sure it's not a network issue? maybe your internet got disconnected and the library was trying to reconnect forever?

I am sure there is no problem with the network, after a while there will be a lot of timeouts, Connect 20 accounts, 15 will have timeout, and the remaining 5 are normal. I don't think it has anything to do with the network.

https://github.com/gram-js/gramjs/issues/302

**Comment by wind-hx** [comment]
> Are you sure it's not a network issue? maybe your internet got disconnected and the library was trying to reconnect forever?

I think it should be a bug that caused the infinite loop, but my development environment cannot be reproduced. This error has always existed in the production environment, causing the cpu to be full.

**Comment by painor** [comment]
if I can't reproduce the issue I really can't solve it :(

**Comment by icanary** [comment]
> Are you sure it's not a network issue? maybe your internet got disconnected and the library was trying to reconnect forever?

even if reason was internet this is need to be fixed. Problems with internet should not crash the app

**Comment by icanary** [comment]
what i know for current moment:

i see in my logs this: [screenshot](https://sun9-79.userapi.com/s/v1/if2/rlnFZZy1HpqhlQZuIgBG3bxIFyma_k1_osgCfTiyMcgNBxMew1NPYXAv1SbzdJ3owLPLiefZphcH5GY3BaqR-QIg.jpg?size=2004x1714&quality=96&type=album)

so here, after client init (**TelegramClient**), connected(**connect**) and successfully logged in(**checkAuthorization**), i try to get info about some channel(**inside my custom getInfo method**).

right after that i set 20 sec sleep, i can see it in screenshot(_i do this to not get flood errors_)

then i try to download photo of channel (**inside my custom channelBuild method**)

so, somewhere around this time, i get errors **Disconnect** and **Timeout** and then app fall in infinite loop. And crash.

=======

**intersting fact**: when i restart app and try to connect client via same user session, i was **NOT** logged in.
So maybe something happened to the user session during these operations.

=======

Whatever it was, the library should not crash an app. It should deal with any variants of events during execution

**Comment by icanary** [comment]
maybe we can together find out the bug if you tell, what exactly mean each of this peaces of code:

Error: Cannot send requests while disconnected. You need to call .connect()

- `at MTProtoSender.send (/code/node_modules/telegram/network/MTProtoSender.js:197:19)`
- `at Object.invoke (/code/node_modules/telegram/client/users.js:31:36)`
- `at async TelegramClient.getDC (/code/node_modules/telegram/client/TelegramClient.js:1120:28)`
- `at async TelegramClient._connectSender (/code/node_modules/telegram/client/telegramBaseClient.js:200:20)`
- `at async TelegramClient._borrowExportedSender (/code/node_modules/telegram/client/telegramBaseClient.js:243`

what is going on in this lines? and why this can fall in repeatable situation?

**Comment by painor** [comment]
when you download a file from a different DC you need to create a new connection. 

That's what line does. It tries to create a new connection in the new DC but for some reason it fails for you. it waits 1 second between each fails and tries again.

**Comment by icanary** [comment]
> when you download a file from a different DC you need to create a new connection.
> 
> That's what line does. It tries to create a new connection in the new DC but for some reason it fails for you. it waits 1 second between each fails and tries again.

but i don't wait 1 sec, it fall in infinite loop every .001 ml-sec. Look at screenshot, there is three calls with tine:

1. 09:03:42.134
2. 09:03:42.134
3. 09:03:42.135

and so on, while not crash an app.

**Comment by painor** [comment]
yes, clearly there is an issue somewhere in the code. 
how many connections do you have open btw.?

**Comment by icanary** [comment]
it start like this:

```
const client = new TelegramClient(session, this.api_id, this.api_hash, {
    connectionRetries: 2,
    requestRetries: 2,
    autoReconnect: false,
    proxy: {
        ip: data.proxy.ip,
        port: parseInt(String(data.proxy.port)),
        username: data.proxy.login,
        password: data.proxy.password,
        socksType: 5,
        MTProxy: false
    },
    baseLogger: new Logger(LogLevel.ERROR)
})

await client.connect()
```

for now it can have 2-10 parallel connections.

**Comment by painor** [comment]
```
    connectionRetries: 2,
    requestRetries: 2,
    autoReconnect: false,

```

can you put theses to 5 and true and see if the error stays?

**Comment by icanary** [comment]
done. Now we need to wait

**Comment by karpotkin** [comment]
> ```
>     connectionRetries: 2,
>     requestRetries: 2,
>     autoReconnect: false,
> ```
> 
> can you put theses to 5 and true and see if the error stays?

I have a similar situation when downloading a photo. These options don't help.

<img width="643" alt="Screenshot 2022-04-22 at 12 23 01" src="https://user-images.githubusercontent.com/5529387/164677411-fb17aedc-3d73-4da3-ba17-c161811fda65.png">

<img width="895" alt="Screenshot 2022-04-22 at 12 25 38" src="https://user-images.githubusercontent.com/5529387/164677866-cfdc5b59-ab89-4339-a05e-c9c15e31b3fa.png">

If you wait a bit (until the connection is made) and try to download the file again, then everything is fine

**Comment by icanary** [comment]
yes, no difference on init parameters.
error arrive again, see [this screenshot](https://sun9-36.userapi.com/s/v1/if2/6xOezX6RaNUzhnXHMzA7MBC14TUFjuE2YiECbMGyH9p2Mm07p7Cy1x4XQesFyIrGwAUrDfA2W_rqyImpW42TIMh3.jpg?size=2338x1758&quality=96&type=album)

maybe it exists in destroy method.. so anyway, bug is out there, need to be finded...

**Comment by icanary** [comment]
> yes, clearly there is an issue somewhere in the library's code. how many connections do you have open btw.? Also do you have any specific attributes when creating a new TelegramClient ?

hi, did you try something to find error? can't use this library with this bug ( crash 1-2 times per day

**Comment by Dima564** [comment]
experienced this issue too

**Comment by icanary** [comment]
> I've pushed a potential fix to the latest version, can you try it out? I've been trying to reproduce the issue but I'm not able to.

can you give link to that fix?

**Comment by karpotkin** [comment]
> > I've pushed a potential fix to the latest version, can you try it out? I've been trying to reproduce the issue but I'm not able to.
> 
> can you give link to that fix?

last commit to the master

**Comment by icanary** [comment]
> I've pushed a potential fix to the latest version, can you try it out? I've been trying to reproduce the issue but I'm not able to.

work fine 3 days and again crash with the same error

**Comment by vitalyster** [comment]
I have the same issue on latest version `2.8.2` from npm.
I'm using single account but did received FLOOD_WAIT with 86400s. The client never waits for this time and tries to reconnect every second lot of time and then crashes with `out of memory`.

**Comment by painor** [comment]
> I have the same issue on latest version `2.8.2` from npm. I'm using single account but did received FLOOD_WAIT with 86400s. The client never waits for this time and tries to reconnect every second lot of time and then crashes with `out of memory`.

By default the library only waits if the floodwait is lower than 60.

If there is an error during the authentication process there is an "onError" callback that you can use to either continue the authentication process or to exit.
If you want to stop just return "true" from the onError callback when floodwait occurs.

**Comment by icanary** [comment]
> If there is an error during the authentication process there is an "onError" callback that you can use to either continue the authentication process or to exit.
this may happen during client.connect(), but not during authentication process. So this is another situation here.

**Comment by vitalyster** [comment]
@painor I just want to sleep that period of time specified in the FLOOD_WAIT error and pretty sure this is a bug

**Comment by vitalyster** [comment]
Well, after checking source code I see that FLOOD_WAIT errors are handled only in `invoke` function, but not in `connect`, I just added something like `onError: async (err) => await err["seconds"]` and now I sleep correctly. I'm still sure these kind of errors should be handled in library itself

**Comment by painor** [comment]
> Well, after checking the source code I see that FLOOD_WAIT errors are handled only in the `invoke` function, but not in `connect`, I just added something like `onError: async (err) => await sleep(err["seconds"]*1000)` and now I sleep correctly. I'm still sure these kind of errors should be handled in the library itself

I think you are misunderstanding something. 

.connect() does call .invoke() 

Do you really want the library to sleep for 24 hours?

The library will sleep by default if the floodwait is less than 60 seconds. this parameter can be configured here https://gram.js.org/beta/classes/TelegramClient.html#floodSleepThreshold

your error happens only during login not when connecting to telegram.

**Comment by vitalyster** [comment]
> Do you really want the library to sleep for 24 hours?
Yes, it MUST sleep for `error.seconds` timeout, otherwise it is blocked

**Comment by vitalyster** [comment]
FLOOD_WAIT issue is just a case when "Error: Cannot send requests while disconnected" and crash happens

**Comment by nbulian** [comment]
Hi, same problem here.
It's worked like a charm for a few days, but now it throw the error:

`Cannot send requests while disconnected. You need to call .connect()`

My stack:
Debian GNU/Linux 10 (buster)
node v16.15.1
telegram 2.10.2

Any idea?

**Comment by wind-hx** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by RedLightsDistrict** [comment]
> > Are you sure it's not a network issue? maybe your internet got disconnected and the library was trying to reconnect forever?
> 
> I am sure there is no problem with the network, after a while there will be a lot of timeouts, Connect 20 accounts, 15 will have timeout, and the remaining 5 are normal. I don't think it has anything to do with the network.
> 
> #302

Hello brother, have you solved this problem
