### ISSUE TITLE
Setting parse_mode with SendMedia / InputMediaPhoto

### ISSUE THREAD

**Issue by heycryptobob** [gram-js/gramjs#304]
Hello,

I am trying to send a photo with a caption, I am using the following code:

```ts
const result: Api.TypeUpdates = await client.invoke(
  new Api.messages.SendMedia({
    peer: peer,
    media: new Api.InputMediaPhotoExternal({ url: mediaURL }),
    message: message,
  })
);
```

The `message` I am sending includes html tags i.e. `<strong>heading</strong>`. So I would like to set the `parse_mode` to `html`.

Unfortunately, I can't find this option, and setting `client.setParseMode("html")` does not impact this request.

From my research on the telegram API, [InputMediaPhoto](https://core.telegram.org/bots/api#inputmediaphoto) has the ability to set the `parse_mode`. This doesn't seem to be available with `InputMediaPhotoExternal` on gramjs.

Please let me know if I am doing something incorrectly. Thank you!

**Comment by painor** [comment]
The docs you are looking for are for the Bot API. they are completely different. 

You should use client.sendFile instead, that one does support parseMode. 

if you still want to use Api.message.SendMedia then you need to manually pass the entities 

```ts
[message, msgEntities] = await _parseMessageText(
            client,
            message,
            parseMode
);
  new Api.messages.SendMedia({
    peer: peer,
    media: new Api.InputMediaPhotoExternal({ url: mediaURL }),
    message: message,
    entities: msgEntities
  })

```

**Comment by heycryptobob** [comment]
@painor thank you!

Here was my final solution!

```ts
const result = client.sendFile(peer, {
    file: new Api.InputMediaPhotoExternal({ url: mediaURL }),
    caption: message,
    parseMode: "html"
  })
```
