### ISSUE TITLE
Progress not wokirng in sendFile

### ISSUE THREAD

**Issue by NumairAwan** [gram-js/gramjs#306]
Hi @painor can you please check why the progress is not working?

```
const result = await client.sendFile(-1001812478853, {
    file: fileUpload,
    workers: 10,
    onProgress: (progress) => console.log(progress)
});
```

**Comment by optionsx** [comment]
**use .uploadFile it has what you looking for, at the moment onProgress isn't available through .sendFile**

**Comment by dzwzqlx** [comment]
> Hi @painor can you please check why the progress is not working?
> 
> ```
> const result = await client.sendFile(-1001812478853, {
>     file: fileUpload,
>     workers: 10,
>     onProgress: (progress) => console.log(progress)
> });
> ```

actually you can use **progressCallback**:
```
const result = await client.sendFile(-1001812478853, {
    file: fileUpload,
    workers: 10,
    progressCallback: (progress) => console.log(progress)
});
```
