### ISSUE TITLE
How do you reply to a reply?

### ISSUE THREAD

**Issue by pheianox** [gram-js/gramjs#312]
This userbot sends comments on new posts of channels 

Users leave comments on comments section, but some of them reply to my userbot's messages 

I want the userbot to reply back to them too when that happens

Basically send them a reply in the comments section

>Maybe my explanation is bad, but
> What I want to do is just
>Reply to a message in `Replies` dialog
```ts
...

// id of "Replies" dialog
const REPLIES_ID = "1271266957"

// handle incoming message
async function handle_new_message({ message }: NewMessageEvent) {
  try {
    // check if message from "Replies" dialog
    if (message.chatId.toString() === REPLIES_ID) {
      // reply to user in chat
      await client.sendMessage(message.peerId, { message: 'OK', replyTo: message })
    }
  } catch (err) {
    console.error(err)
  }
}

// listen for incoming messages
client.addEventHandler(handle_new_message, new Message({ incoming: true }))

... 
```

Instead I get an error saying
```
400: YOU_BLOCKED_USER (caused by messages.SendMessage)
```
As far as I know "Replies" dialog is a bot

**Comment by painor** [comment]
you want to use message.chatId instead of message.peerId in sendMessage

**Comment by pheianox** [comment]
Same error
```
400: YOU_BLOCKED_USER (caused by messages.SendMessage)
```

**Comment by pheianox** [comment]
Maybe my explanation is bad, but

What I want to do is just

**Reply to a message in `Replies`  dialog**

**Comment by painor** [comment]
ah, then you need to use commentTo not replyTo

**Comment by pheianox** [comment]
nothing seems to help :(

**Comment by pheianox** [comment]
I think there's something related with frwFrom

**Comment by painor** [comment]
I'm not sure what you are trying to do tbh :/

**Comment by pheianox** [comment]
Reply to a message in Replies dialog

**Comment by pheianox** [comment]
This helped
```bash
entity: message.replyTo.replyToPeerId,
replyTo: message.fwdFrom.savedFromMsgId,
```

**Comment by painor** [comment]
That's great, Sorry I couldn't help but I've never tried the "Replies" feature of telegram..

**Comment by pheianox** [comment]
Oh, it's okay! Actually, I just needed to read about [Threads#replies ](https://core.telegram.org/api/threads#replies)

Btw, we can include this function to reply to a reply from "Replies" dialog 😂 it can be helpful for others too

```ts
export async function replyToRepliesMessage /* or something better */
(
  // telegram client
  client: TelegramClient,

  // message object that we want to reply to 
  // ensure that it comes from chat with id 1271266957 ("Replies")
  message: Api.Message 

  // text
  text: string,  
) 
{
  return client.invoke(
    new Api.messages.SendMessage({
      peer: message.replyTo.replyToPeerId,
      replyToMsgId: message.fwdFrom?.savedFromMsgId,
      message: text,
    })
  )
}

```
**Note: it doens't handles anything like if the message is deleted... just a raw api call**

**Comment by pheianox** [comment]
Also I've noticed it's a good practice to get all dialogs at startup, so that no errors like this appear

```
400: CHANNEL_INVALID (caused by channels.GetChannels)
```

**Comment by StepinPV** [comment]
@painor Hi, friend! Could you show how to send comment message in channel?) Pleease!

In message object i have this field 

id: 6,
replies: {
    CONSTRUCTOR_ID: 2211844034,
    SUBCLASS_OF_ID: 1825397986,
    className: 'MessageReplies',
    classType: 'constructor',
    flags: 1,
    comments: true,
    replies: 0,
    repliesPts: 0,
    recentRepliers: null,
    channelId: Integer { value: 1938248357n },
    maxId: null,
    readMaxId: null
  },
 peerId: {
    CONSTRUCTOR_ID: 2728736542,
    SUBCLASS_OF_ID: 47470215,
    className: 'PeerChannel',
    classType: 'constructor',
    channelId: Integer { value: 1395520188n }
  }
