### ISSUE TITLE
Add timezone to logger

### ISSUE THREAD

**Issue by MoKhajavi75** [gram-js/gramjs#317]
Hey
Thanks for your awesome library!

I was trying to set the timezone for logger and found [this line](https://github.com/gram-js/gramjs/blob/master/gramjs/extensions/Logger.ts#L96).

Should I add a PR to add `process.env.TZ` to that?

Or is there any other way to set TZ for logger?

**Example:**

```bash
#       Here ↓
[2022-05-12T14:58:07.519Z] [INFO] - [Running gramJS version 2.7.30]
```

**Comment by painor** [comment]
maybe add it to the logger's constructor? 
The library also works on browser's and those don't have "process"

**Comment by MohamadKh75** [comment]
When can we have a new version @painor ?

**Comment by painor** [comment]
probably tomorrow, I'm currently refactoring some of the websocket code

**Comment by MohamadKh75** [comment]
I really appreciate your efforts!
Thanks @painor
