### ISSUE TITLE
Logging in as a User (password?)

### ISSUE THREAD

**Issue by valorloff** [gram-js/gramjs#321]
Hi!
I study your API:
```
await client.start({
    phoneNumber: async () => await input.text("number ?"),
    password: async () => await input.text("password?"),
    phoneCode: async () => await input.text("Code ?"),
    onError: (err) => console.log(err),
  });
```
What does this password mean and where can I get it?

Thanks!

**Comment by ULTRAxHURRICANE** [comment]
@valorloff password is 2fa ig

**Comment by valorloff** [comment]
> 

sorry, what does is mean "2fa ig" ?

**Comment by ULTRAxHURRICANE** [comment]
> > 
> 
> sorry, what does it mean "2fa ig" ?

Two Factor Authentication

**Comment by valorloff** [comment]
> Two Factor Authentication

Is it mandatory or can it be done without it?
```
await client.start({
    phoneNumber: "+7xxxxxxxx",
    phoneCode: async () => await input.text("Code ?"),
    onError: (err) => console.log(err),
  });
```

**Comment by ULTRAxHURRICANE** [comment]
> 

If you have 2fa in your account then only it will ask.

**Comment by painor** [comment]
as mentioned before, it's optional and will only be called if your account is password protected.

**Comment by valorloff** [comment]
Ok! Thanks for help!

If i run sample app, script don't prompt Login code and stop executing:

```
I20220515-20:51:10.477(3)? [2022-05-15T17:51:10.476Z] [INFO] - [Running gramJS version 2.7.30]
I20220515-20:51:10.481(3)? [2022-05-15T17:51:10.481Z] [INFO] - [Connecting to 149.154.167.91:80/TCPFull...]
I20220515-20:51:11.663(3)? [2022-05-15T17:51:11.663Z] [INFO] - [Connection to 149.154.167.91:80/TCPFull complete!]
I20220515-20:51:11.667(3)? [2022-05-15T17:51:11.664Z] [INFO] - [Using LAYER 140 for initial connect]
I20220515-20:51:12.216(3)? [2022-05-15T17:51:12.216Z] [INFO] - [Phone migrated to 2]
I20220515-20:51:12.300(3)? [2022-05-15T17:51:12.295Z] [INFO] - [Reconnecting to new data center 2]
I20220515-20:51:12.419(3)? [2022-05-15T17:51:12.419Z] [INFO] - [Disconnecting from 149.154.167.91:80/TCPFull...]
I20220515-20:51:12.420(3)? [2022-05-15T17:51:12.420Z] [INFO] - [Connecting to 149.154.167.50:80/TCPFull...]
I20220515-20:51:12.421(3)? [2022-05-15T17:51:12.421Z] [INFO] - [connection closed]
```

**Comment by ULTRAxHURRICANE** [comment]
> Ok! Thanks for help!
> 
> If i run sample app, script doesn't prompt Login code and stop executing:
> 
> ```
> I20220515-20:51:10.477(3)? [2022-05-15T17:51:10.476Z] [INFO] - [Running gramJS version 2.7.30]
> I20220515-20:51:10.481(3)? [2022-05-15T17:51:10.481Z] [INFO] - [Connecting to 149.154.167.91:80/TCPFull...]
> I20220515-20:51:11.663(3)? [2022-05-15T17:51:11.663Z] [INFO] - [Connection to 149.154.167.91:80/TCPFull complete!]
> I20220515-20:51:11.667(3)? [2022-05-15T17:51:11.664Z] [INFO] - [Using LAYER 140 for initial connect]
> I20220515-20:51:12.216(3)? [2022-05-15T17:51:12.216Z] [INFO] - [Phone migrated to 2]
> I20220515-20:51:12.300(3)? [2022-05-15T17:51:12.295Z] [INFO] - [Reconnecting to new data center 2]
> I20220515-20:51:12.419(3)? [2022-05-15T17:51:12.419Z] [INFO] - [Disconnecting from 149.154.167.91:80/TCPFull...]
> I20220515-20:51:12.420(3)? [2022-05-15T17:51:12.420Z] [INFO] - [Connecting to 149.154.167.50:80/TCPFull...]
> I20220515-20:51:12.421(3)? [2022-05-15T17:51:12.421Z] [INFO] - [connection closed]
> ```

Please read the tutorial at https://gram.js.org/

**Comment by valorloff** [comment]
> Please read the tutorial at https://gram.js.org/

I just run this example, only without "2fa" (pass).
Is it possible to client.start without a phone number, but only with apiId and apiHash?

**Comment by painor** [comment]
> > Please read the tutorial at https://gram.js.org/
> 
> I just run this example, only without "2fa" (pass). Is it possible to client.start without a phone number, but only with apiId and apiHash?

You need to authenticate with an account or a bot to use the library.

**Comment by valorloff** [comment]
> You need to authenticate with an account or a bot to use the library.
Logging in as a User:
```
           await client.start({
                phoneNumber: '+3xxxxxxxxx',
                phoneCode: async () => await input.text("Login code ?:"),
                onError: (err) => console.log(err)
            });
```
Login code is coming to inbox (service notification)
```
I20220515-22:53:37.317(3)? [2022-05-15T19:53:37.315Z] [INFO] - [Disconnecting from 149.154.167.50:80/TCPFull...]
I20220515-22:53:37.317(3)? [2022-05-15T19:53:37.316Z] [INFO] - [Connecting to 149.154.167.50:80/TCPFull...]
I20220515-22:53:37.387(3)? [2022-05-15T19:53:37.386Z] [INFO] - [Connection to 149.154.167.50:80/TCPFull complete!]
I20220515-23:52:39.023(3)? [2022-05-15T20:52:39.019Z] [INFO] - [Using LAYER 140 for initial connect]
.........................................
```
and process stop without prompt.

no further testing possible due error
`FloodWaitError: A wait of 75415 seconds is required (caused by auth.SendCode)`

I expected the input prompt to be on the command line, right ?

**Comment by painor** [comment]
Yes it should be in the command line, if it's not then maybe your command line doesn't support inputs?

**Comment by valorloff** [comment]
Thanks @painor for your patience.

run in linux terminal:

```
I20220516-21:03:43.890(3)? [2022-05-16T18:03:43.890Z] [INFO] - [Running gramJS version 2.7.30]
I20220516-21:03:43.894(3)? [2022-05-16T18:03:43.893Z] [INFO] - [Connecting to 149.154.167.91:80/TCPFull...]
I20220516-21:03:45.118(3)? [2022-05-16T18:03:45.116Z] [INFO] - [Connection to 149.154.167.91:80/TCPFull complete!]
I20220516-21:03:45.119(3)? [2022-05-16T18:03:45.117Z] [INFO] - [Using LAYER 140 for initial connect]
I20220516-21:03:45.745(3)? [2022-05-16T18:03:45.744Z] [INFO] - [Phone migrated to 2]
I20220516-21:03:45.825(3)? [2022-05-16T18:03:45.825Z] [INFO] - [Reconnecting to new data center 2]
I20220516-21:03:46.029(3)? [2022-05-16T18:03:46.028Z] [INFO] - [Disconnecting from 149.154.167.91:80/TCPFull...]
I20220516-21:03:46.030(3)? [2022-05-16T18:03:46.029Z] [INFO] - [Connecting to 149.154.167.50:80/TCPFull...]
I20220516-21:03:46.031(3)? [2022-05-16T18:03:46.030Z] [INFO] - [connection closed]
I20220516-21:03:47.369(3)? [2022-05-16T18:03:47.368Z] [INFO] - [Connection to 149.154.167.50:80/TCPFull complete!]
I20220516-21:03:47.370(3)? [2022-05-16T18:03:47.369Z] [INFO] - [Using LAYER 140 for initial connect]
```
that'`s all, nothing more. I run this sample by MeteorJS method, maybe there is a problem in the runtime environment? what environment do you work in?

**Comment by painor** [comment]
I use windows CMD and nodeJS to run it. 

The input() method is supposed to work node terminal not in browsers. if you have this in browser you'll need to use something similar like prompt()

**Comment by valorloff** [comment]
> The input() method is supposed to work node terminal not in browsers.

I think it's asynchronous issue with 
`phoneCode: async () => await input.text("Login code ?:"),`
function exits before phoneCode receives value

**Comment by painor** [comment]
Nope, it has nothing to do with that. That's just a callback function.

Can you try a simple nodeJS script and see if that works? I'm not sure if meteorJS supports the "input" library.

You can also use your own callback methods btw, the input one is just an example.

**Comment by rafaelfaria** [comment]
So, if the telegram account doesn't have 2FA enabled you can just use phone number and password to authenticate?

**Comment by painor** [comment]
you can login once and save the session to use again without needing to login.

**Comment by valorloff** [comment]
> You can also use your own callback methods btw

would you mind giving an short example?
thanks

**Comment by valorloff** [comment]
looks like it's [impossible](https://github.com/meteor/meteor/issues/4836):

**Comment by painor** [comment]
you can run the code in nodeJS and use the session string in meteor, 
In that case you will not need to login again. 

When I said a callback I meant a custom callback not the same input method. 
Like maybe read from a file or something.

**Comment by rafaelfaria** [comment]
> 

Can you still use the same session token on another environment? I thought this wasn't possible.

**Comment by painor** [comment]
Yes you can use the same session token on another environment. You just can't use the same session at the same time with two separate IPs. so if you only use it in one place it's fine.

**Comment by rafaelfaria** [comment]
Let's say I create a session token. How often would I need to renew the session? does anyone know? Couldn't find it in the docs.

**Comment by painor** [comment]
You only need to do this once. 
It's the same as logging in with your mobile app, you never need to relog unless you have logged out from somewhere else.

**Comment by valorloff** [comment]
> You only need to do this once.

```
const client = new TelegramClient( **savedStringSession**, apiId, apiHash, {
    connectionRetries: 5,
  });
  await client.start({
    phoneNumber: async () => await input.text("number ?"),
    onError: (err) => console.log(err),
  });

```
and this is enough for all subsequent sessions ?

**Comment by valorloff** [comment]
> .connect() is enough

Thanks @painor, you really helped

**Comment by atkisai** [comment]
> Ok! Thanks for help!
> 
> If i run sample app, script doesn't prompt Login code and stop executing:
> 
> ```
> I20220515-20:51:10.477(3)? [2022-05-15T17:51:10.476Z] [INFO] - [Running gramJS version 2.7.30]
> I20220515-20:51:10.481(3)? [2022-05-15T17:51:10.481Z] [INFO] - [Connecting to 149.154.167.91:80/TCPFull...]
> I20220515-20:51:11.663(3)? [2022-05-15T17:51:11.663Z] [INFO] - [Connection to 149.154.167.91:80/TCPFull complete!]
> I20220515-20:51:11.667(3)? [2022-05-15T17:51:11.664Z] [INFO] - [Using LAYER 140 for initial connect]
> I20220515-20:51:12.216(3)? [2022-05-15T17:51:12.216Z] [INFO] - [Phone migrated to 2]
> I20220515-20:51:12.300(3)? [2022-05-15T17:51:12.295Z] [INFO] - [Reconnecting to new data center 2]
> I20220515-20:51:12.419(3)? [2022-05-15T17:51:12.419Z] [INFO] - [Disconnecting from 149.154.167.91:80/TCPFull...]
> I20220515-20:51:12.420(3)? [2022-05-15T17:51:12.420Z] [INFO] - [Connecting to 149.154.167.50:80/TCPFull...]
> I20220515-20:51:12.421(3)? [2022-05-15T17:51:12.421Z] [INFO] - [connection closed]
> ```
Hello, did you solve this problem? I run both in the browser and in the node environment and get this every time.

**Comment by YakovL** [comment]
@painor are you aware if there's a method to learn whether a user has 2FA set up? I.e. can I ask them for a password only if they have it? I can see there's the `client.signInWithPassword` method, but what should I check after using

    await client.start({
        phoneNumber: async () => await input.text("Please enter your number: "),
        phoneCode: async () => await input.text("Please enter the code you received: "),
        onError: (error) => console.log(error),
    })

to understand whether I need to ask them and use `client.signInWithPassword`?

**Comment by mcfriend99** [comment]
Can it be done with an existing code and password? Like for example doing this from a website and sending the code to the server.

**Comment by painor** [comment]
@mcfriend99 if you want that flow you can check out the example here https://github.com/gram-js/gramjs/blob/master/examples/expressExample/lowLevel.js
