### ISSUE TITLE
TS "Type 'number' is not assignable to type 'TypeInputMessage'."

### ISSUE THREAD

**Issue by SupchickCode** [gram-js/gramjs#323]
i use code from here "https://gram.js.org/tl/channels/GetMessages"

i don't understand why i have this error and how to fix it

![x](https://user-images.githubusercontent.com/58991461/168861742-666324ce-d5c7-450b-9f0b-54edaf1891ab.png)

Error message "Type 'number' is not assignable to type 'TypeInputMessage'."

**Comment by painor** [comment]
Well you're supposed to do 
` id: [new Api.InputMessageID({ id: 43 })]` but using 43 directly also works (and is shorter).

You can ignore the TS error or use the 'correct' way

**Comment by SupchickCode** [comment]
I can't event compile.
![image](https://user-images.githubusercontent.com/58991461/168867738-7cc8ba1d-2a6d-4c19-8657-ecccaa0704cf.png)

But thx it works fine for me `id : [new Api.InputMessageID({ id: 43 })]`

> Well you're supposed to do ` id: [new Api.InputMessageID({ id: 43 })]` but using 43 directly also works (and is shorter).
> 
> You can ignore the TS error or use the 'correct' way

**Comment by SupchickCode** [comment]
[painor](https://github.com/painor) one more quesiton.

Can i get users and messages created by this users in chanel (group) ? 

From this group for example 
![image](https://user-images.githubusercontent.com/58991461/168868605-a9e49925-d956-4aad-825d-7c8a3b8bff81.png)

**Comment by painor** [comment]
it's not very clear what you are asking for.

if you want to get a list of users in the group use: https://gram.js.org/beta/classes/TelegramClient.html#iterParticipants

If you want messages from a user in a group use: https://gram.js.org/beta/classes/TelegramClient.html#iterMessages with fromUser filter

**Comment by SupchickCode** [comment]
Thx u a lot, i got it =)
