### ISSUE TITLE
event.message.text not getting all styles of formatted message

### ISSUE THREAD

**Issue by leandroribeir0** [gram-js/gramjs#327]
I'm monitoring a chat to forward all messages to another channel, but if the message has specific styles I can't get them using `event.message.text`.

Examples after send a message to same chat with the content of `event.message.text`:

![image](https://user-images.githubusercontent.com/62257278/169528857-6c597159-68b5-495b-bd36-1a1c674bd646.png)

Underline texts, for example, lose their formatting.

**Comment by painor** [comment]
The message also has a .entities which contains all the formating. maybe you want to use that as well when resending?
