### ISSUE TITLE
RPC Error handling

### ISSUE THREAD

**Issue by salacoste** [gram-js/gramjs#330]
Hello,
I'm trying to sanitize channelId from user input in the method via try/catch approach, how can I grab RPCError object from the method
`await telegram_client.invoke(
            new Api.channels.GetFullChannel({
                channel: channel_id
            })
        );`
as I have the Error message in stdout 
`RPCError: 400: CHANNEL_INVALID (caused by channels.GetChannels)`

but catch handler gives me the following: 
`Error: Could not find the input entity for {"channelId":"xxxx","className":"PeerChannel"}.
         Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.`

**Comment by painor** [comment]
I'm not sure what you mean by "sanitize" 
The be able to get a channel you need both channel id and access hash if the library didn't see the access hash fo the specific channel it can't use any requests.

**Comment by painor** [comment]
you won't get CHANNEL_INVALID beacuse the ID might be valid but you don't have permission to see it as you need the acceshash for that.

If you want to always get CHANNEL_INVALID you have to manually put the access hash. 

 
telegram_client.invoke( new Api.channels.GetFullChannel({ channel: channel_id, acessHash:.. }) );

**Comment by salacoste** [comment]
> you won't get CHANNEL_INVALID beacuse the ID might be valid but you don't have permission to see it as you need the acceshash for that.
> 
> If you want to always get CHANNEL_INVALID you have to manually put the access hash.
> 
> telegram_client.invoke( new Api.channels.GetFullChannel({ channel: channel_id, acessHash:.. }) );

I'll check it later today, hope that helps in that matter.

I have a question about: how to carry out handling of RPCErrors, I mean in the documents there is mentioning that you can extend the RPC error class with custom one. Can you share the code example how should it be done?

**Comment by painor** [comment]
I'm not sure why you would want that, 

you can probably just do if (error instanceof RPCError) maybe?

**Comment by salacoste** [comment]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/12632895/171303372-166fc1a3-d346-49c5-a4dd-d15df0984020.png">
That's what i try to achieve,
I would like to get in error object code of error to arrange the right handling approach, but based on code above I got the error code only in the console, in error object of catch(){} I have only message and stack options:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/12632895/171303575-8664cac1-1ac4-4064-b5cc-2dfbe6beb118.png">

How is it possible to get err.code and err.errorMessage in catch handler?

**Comment by painor** [comment]
try e.errorMessage

**Comment by salacoste** [comment]
<img width="887" alt="image" src="https://user-images.githubusercontent.com/12632895/171305425-50917c05-3c1c-45d5-abc4-6f95d0cb1659.png">
I consolled Object.getOwnPropertyNames to show all possible methods/properties: it has only stack and message regarding screenshot below
<img width="260" alt="image" src="https://user-images.githubusercontent.com/12632895/171305515-9c00e2ed-0c0a-49ca-9f2c-4d6169777e82.png">

e.errorMessage
<img width="539" alt="image" src="https://user-images.githubusercontent.com/12632895/171305582-f066d38a-803c-4c26-ac66-e4e6ea213623.png">

<img width="384" alt="image" src="https://user-images.githubusercontent.com/12632895/171305592-d057d0c9-62fa-4cfb-967c-da466d9c1e63.png">


It's pretty much strange, because for some gram's methods I do get the "right"/expected error message with error code, for some not.

**Comment by salacoste** [comment]
for example here
<img width="446" alt="image" src="https://user-images.githubusercontent.com/12632895/171305792-5eb08339-bbd3-4197-8273-d740094eeb55.png">
<img width="475" alt="image" src="https://user-images.githubusercontent.com/12632895/171305873-76f57a0b-6cc0-4b41-9e15-589575fe3931.png">

it works as expected
<img width="867" alt="image" src="https://user-images.githubusercontent.com/12632895/171305908-3a6aa35a-999f-4b04-8823-f75ba767b44d.png">

**Comment by painor** [comment]
> <img alt="image" width="887" src="https://user-images.githubusercontent.com/12632895/171305425-50917c05-3c1c-45d5-abc4-6f95d0cb1659.png">
> 
> I consolled Object.getOwnPropertyNames to show all possible methods/properties: it has only stack and message regarding screenshot below
> <img alt="image" width="260" src="https://user-images.githubusercontent.com/12632895/171305515-9c00e2ed-0c0a-49ca-9f2c-4d6169777e82.png">
> 
> e.errorMessage <img alt="image" width="539" src="https://user-images.githubusercontent.com/12632895/171305582-f066d38a-803c-4c26-ac66-e4e6ea213623.png">
> 
> <img alt="image" width="384" src="https://user-images.githubusercontent.com/12632895/171305592-d057d0c9-62fa-4cfb-967c-da466d9c1e63.png">
> 
> It's pretty much strange, because for some gram's methods I do get the "right"/expected error message with error code, for some not.

when the error is about "missing" entity then the library throws the error not telegram, and that will not have an errorMessage field.

When the error is about something with the API itself telegram will return the error and the library will put the API result in errorMessage

**Comment by salacoste** [comment]
@painor did you hve a chance to take a look on that?

**Comment by painor** [comment]
hey, yes, sadly I was not able to reproduce the issue, in my case it shows `Error: Could not find the input entity for {"userId:XXX"}` for both cases.

The library cannot send the request if it hasn't seen the ID before. and if it didn't see the ID it will throw that error. 

The check happens here https://github.com/gram-js/gramjs/blob/master/gramjs/tl/api.js#L149

**Comment by gee666** [comment]
@salacoste how did you resolve the issue? I get exactly the same thing: the error I can catch in the try ... catch block is not the RPCError, it doesn't have code, errMessage.
