### ISSUE TITLE
getFullChat returns error

### ISSUE THREAD

**Issue by StasTikh** [gram-js/gramjs#333]
Hello! First of all, thanks for your work, it’s very useful. 
I have a problem. Trying to use getFullChat method. When chat_id has 9 digits, it works. But if chat_id has 10 numbers and starts with “1”, I’m getting an error “chat if invalid”. What can be a problem? Thanks

**Comment by painor** [comment]
getFullChat  is only for small chats,
if you want to use something on supergroup use https://gram.js.org/tl/channels/GetFullChannel#channelsgetfullchannel

**Comment by StasTikh** [comment]
> getFullChat is only for small chats,
> if you want to use something on supergroup use https://gram.js.org/tl/channels/GetFullChannel#channelsgetfullchannel

Thanks, I tried this method too. Same story

**Comment by painor** [comment]
can you share your code?

**Comment by StasTikh** [comment]
> can you share your code?
yes, of course. 
(async function run() {
    await client.connect();
    const result = await client.invoke(
        new Api.channels.GetFullChannel({
          channel: "1247153954"
        })
    );
    console.log(result); 
  })();
and i've got an error: 
"Error: Could not find the input entity for {"userId":"1247153954","className":"PeerUser"}."

**Comment by StasTikh** [comment]
thanks! it works, but i've got only me. all the other users i didnt got

**Comment by StasTikh** [comment]
> 1247153954 is a user's ID. use -1001247153954

thanks! but i got only my data in userrs array. or vevn an empty array
