### ISSUE TITLE
Reconnection problem

### ISSUE THREAD

**Issue by Aaron-lv** [gram-js/gramjs#334]
![1](https://user-images.githubusercontent.com/58249729/172631979-bace343a-7c2b-453c-a188-cf3a903fcef5.png)
The program does not listen for new messages after the connection is disconnected and reconnected

**Comment by Aaron-lv** [comment]
Please how can I solve this problem, thank you

**Comment by painor** [comment]
did you fix it? (why did you close the issue)

**Comment by Aaron-lv** [comment]
![image](https://user-images.githubusercontent.com/58249729/172673643-5a2e3d6d-3a9a-490c-9d20-02efd569cdd9.png)
I don't know how to fix it, there is a temporary way

**Comment by painor** [comment]
eh, if it works for you then it's fine, 
the library should have done that internally. also to get messages you need to call at least one high level call. (client.getMe()) for example

**Comment by Aaron-lv** [comment]
I have done this, 
but there is no way to do it after the connection is reconnected, causing the connection to close

So I can only continuously detect if there is a connection. .
