### ISSUE TITLE
The file to be accessed is currently stored in DC 5 (caused by upload.GetFile)

### ISSUE THREAD

**Issue by ljs19923** [gram-js/gramjs#356]
Hi guys,

I'm trying to download the profile picture of a private channel, from a bot connection. The bot is admin of the channel.

Problem: 
The bot is in the DC5 and the channel in the DC4

So I got this error on the upload.getfile call:
The file to be accessed is currently stored in DC 4 (caused by upload.GetFile)

Do you know the solution?

I tried to call  Api.auth.ExportAuthorization and Api.auth.ImportAuthorization, but I got another error : 
RPCError: 400: AUTH_BYTES_INVALID (caused by auth.ImportAuthorization)

I'm on that since 7hours.. without any solutions

<img width="562" alt="Screen Shot 2022-07-20 at 16 13 32" src="https://user-images.githubusercontent.com/5727223/180004260-6f27d2bb-9d5c-4851-9aee-e980961cfda6.png">

**Comment by painor** [comment]
the library kinda handles all of this for you. 

You can either use client.downloadProfilePhoto https://gram.js.org/beta/classes/TelegramClient.html#downloadProfilePhoto
or you can use client.downloadFile  https://gram.js.org/beta/classes/TelegramClient.html#downloadFile
or if you really want to do it alone you can use 
```js
const sender = await client.getSender(dcId);
const result = await sender.send(
      new Api.upload.GetFile({
              location: inputLocation,
                offset: 0,
                 limit: 1024*1024,
         })
       );
```

**Comment by ljs19923** [comment]
Thanks a lot @painor ! You saved me
