### ISSUE TITLE
not posting properly

### ISSUE THREAD

**Issue by Vo0oX** [gram-js/gramjs#362]
post on the channel from which I take information
![image](https://user-images.githubusercontent.com/20887300/180619356-10c7a9b8-5c40-4647-8d97-23553ab91a34.jpeg)

and this is how the bot posts

![image](https://user-images.githubusercontent.com/20887300/180619373-03e942a6-be32-490c-98aa-b9eac7d34025.jpeg)

**Comment by painor** [comment]
The first message seems like an album.
maybe you want to use await client.sendFile(chat, {file:[file1,file2]}

**Comment by Vo0oX** [comment]
> await client.sendFile(chat, {file:[file1,file2]}
**я использую эту команду:**
`await client.sendMessage(id_channel_toPeer, {message: update.message})
`
the channel sometimes sends simple text, text + picture, text + video, text + video +  picture.

**Comment by Vo0oX** [comment]
`client.addEventHandler(async (update) => {

                            if (update.message) {
                                if (update.message.peerId) {

                                    let idChannel = update.message.peerId.channelId.value;

                                    if (idChannel.toString() === id_channel_fromPeer) {

                                        (async () => {

                                            update.message.message = update.message.message.slice(0, -22);

                                        })().then(async () => {
                                            await client.sendMessage(id_channel_toPeer, {message: update.message})

                                        })

                                    }
                                }
                            }

                        }, new NewMessage({}));`

**Comment by painor** [comment]
well you see some messages are a part of an "album".
you can know this by checking for this attribute https://gram.js.org/beta/classes/custom.CustomMessage.html#groupedId

you can ignore them in that hander and use another handler for albums. 

https://gram.js.org/beta/classes/custom.Album.html

it's a bit complicated so good luck
