### ISSUE TITLE
adding users from one group to another

### ISSUE THREAD

**Issue by Vo0oX** [gram-js/gramjs#363]
not found in the documentation.

tell me if there is a method to get a list of subscribers to one group and the possibility of adding them to another group?

**Comment by vidrepar** [comment]
@Vo0oX did you find a way how to do this?

**Comment by Vo0oX** [comment]
> @Vo0oX did you find a way how to do this?

apiHash, {});

(async function run() {
  await client.connect(); // This assumes you have already authenticated with .start()

  const result = await client.invoke(
    new Api.channels.InviteToChannel({
      channel: "username",
      users: ["username"],
    })
  );
  console.log(result); // prints the result
})();
