### ISSUE TITLE
Using separate client for media downloads

### ISSUE THREAD

**Issue by KishanBagaria** [gram-js/gramjs#367]
https://core.telegram.org/api/files recommends
> It is recommended that large queries ([upload.getFile](https://core.telegram.org/method/upload.getFile), [upload.saveFilePart](https://core.telegram.org/method/upload.saveFilePart), [upload.getWebFile](https://core.telegram.org/method/upload.getWebFile)) be handled through a separate session and a separate connection, in which no methods other than these should be executed. If this is done, then data transfer will cause less interference with [getting updates](https://core.telegram.org/api/updates) and other method calls.

We've tried this like this:
```ts
const mediaClient = new MemorySession()
mediaClient.setAuthKey(this.dbSession.getAuthKey())
mediaClient.setDC(this.dbSession.dcId, this.dbSession.serverAddress, this.dbSession.port)
this.mediaClient = new TelegramClient(mediaSession, API_ID, API_HASH, this.clientParams)
await this.mediaClient.connect()
// ...
this.mediaClient.downloadMedia(...)
```

and this:
```ts
this.mediaClient = new TelegramClient(this.dbSession, API_ID, API_HASH, this.clientParams)
await this.mediaClient.connect()
// ...
this.mediaClient.downloadMedia(...)
```

Both snippets result in some users randomly getting `406: AUTH_KEY_DUPLICATED`. 

What are we doing wrong? How would you suggest doing what the docs recommend with gramjs?

**Comment by painor** [comment]
The library already does that for you. 
what they mean by connection is a new "sender", not a new client. Having two separate clients using the same session under two different IPs will result in the  `AUTH_KEY_DUPLICATED` error.

https://github.com/gram-js/gramjs/blob/master/gramjs/client/telegramBaseClient.ts#L493

**Comment by KishanBagaria** [comment]
Got it, thanks.
