### ISSUE TITLE
TypeError: Api.messages.sendReaction is not a constructor WHY?

### ISSUE THREAD

**Issue by BHIgor** [gram-js/gramjs#370]
Why does it write TypeError: Api.messages.sendReaction is not a constructor? I do everything according to the manual gram js
HELP

 await clientApiReaction.connect(); 
            
const result = await clientApiReaction.invoke(new Api.messages.SendReaction({
    peer: '-1001392042824',
    msgId: 39207,
    big: true,
    reaction: 'U+1F44D'
}));

**Comment by painor** [comment]
it's SendRection not sendReaction https://gram.js.org/tl/messages/SendReaction

**Comment by BHIgor** [comment]
> it's SendRection not sendReaction https://gram.js.org/tl/messages/SendReaction

![image](https://user-images.githubusercontent.com/56978682/182419300-cea50b60-ec59-4867-a432-34b11a23f14b.png)

changed but the error remains

**Comment by BHIgor** [comment]
What could be the problem?

**Comment by painor** [comment]
what version are you using? are you sure you're writing it correctly?.

**Comment by BHIgor** [comment]
Thanks a lot! Updated version and it worked!
