### ISSUE TITLE
messageEntityBold => <b>bold</b>, <strong>bold</strong>, **bold**

### ISSUE THREAD

**Issue by Vo0oX** [gram-js/gramjs#381]
how to highlight text?  
await client.sendMessage(id_channel_toPeer, {message: update.message})

**Comment by painor** [comment]
https://gram.js.org/beta/classes/TelegramClient.html#sendMessage

**Comment by Vo0oX** [comment]
**This works, but if I need to send a picture with text, then this option no longer works for me.**
`await client.sendMessage('me', {message:'Hello, **world**!', {parseMode:"md"}})
`

**how to achieve this result with a picture?**
```
update.message.message = `**${oldText}**`;
 await client.sendMessage(id_channel_toPeer, {message: update.message});
```

**Comment by painor** [comment]
you'd have to send them separately then. 
client.sendMessage(id_channel, {file:update.message.media, message:update.message.message});

**Comment by Vo0oX** [comment]
> you'd have to send them separately then.
> client.sendMessage(id_channel, {file:update.message.media, message:update.message.message});

/Users/user/Desktop/forward_Bot/node_modules/telegram/client/uploads.js:448
        throw new Error(`Cannot use ${file} as file.`);
              ^

Error: Cannot use [object Object] as file.
    at Object.sendFile (/Users/user/Desktop/forward_Bot/node_modules/telegram/client/uploads.js:448:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/user/Desktop/forward_Bot/app.js:294:53

Process finished with exit code 1

**Comment by Vo0oX** [comment]
> > you'd have to send them separately then.
> > client.sendMessage(id_channel, {file:update.message.media, message:update.message.message});
> 
> ```
> /Users/user/Desktop/forward_Bot/node_modules/telegram/client/uploads.js:448
>         throw new Error(`Cannot use ${file} as file.`);
>               ^
> 
> Error: Cannot use [object Object] as file.
>     at Object.sendFile (/Users/user/Desktop/forward_Bot/node_modules/telegram/client/uploads.js:448:15)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async /Users/user/Desktop/forward_Bot/app.js:294:53
> 
> Process finished with exit code 1
> ```

sorry my mistake
