### ISSUE TITLE
link preview

### ISSUE THREAD

**Issue by Vo0oX** [gram-js/gramjs#382]
please tell me, I'm sending a link - how to remove the link preview.

And how can I make the text be a link: 'CLICK LINK' ( www.exemple.com)

`await client.sendMessage(id_channel_toPeer, {message:'CLICK LINK ',link: www.exemple.com});
`

**Comment by painor** [comment]
you can do `<a href="www.url.com">CLICK</a>`

**Comment by Vo0oX** [comment]
but how do i remove the preview?

**Comment by painor** [comment]
do {linkPreview:false}
