### ISSUE TITLE
Can I cache the peer information to redis and use it to send message?

### ISSUE THREAD

**Issue by laocoi** [gram-js/gramjs#384]
Dear all,

I have a task to send multiple messages to just ONE person by him username. I got this error
```FloodWaitError: A wait of 24597 seconds is required (caused by contacts.ResolveUsername)```

So, my idea is use Redis to cache the peer information and use it to sending message to the same people the next time.

I am following this article to rebuild the peer object by the cached information
https://gram.js.org/beta/classes/Api.PeerUser.html

```
 var u = {
    peer: { 
      userId: BigInt(xxx), 
      className: 'PeerUser',
      CONSTRUCTOR_ID: 1498486562,
      SUBCLASS_OF_ID: 47470215,
      classType: 'constructor'
    }
  }

var p = new Api.PeerUser(u.peer);
```

Then send message by the API
```
let res = await client.invoke(new Api.messages.SendMessage({
        peer: p,
        message: message      
}));
console.log(res)
```

I got this error:
```
Error: Could not find the input entity for {"userId":"xxx","className":"PeerUser","CONSTRUCTOR_ID":1498486562,"SUBCLASS_OF_ID":47470215,"classType":"constructor"}.
```

Can you tell me why?
Thanks for your time!

**Comment by painor** [comment]
how did you get the "peer" object there?

you should be doing `const peer = await client.getEntity(username)`

**Comment by laocoi** [comment]
@painor I use API

```
uinfo = await client.invoke(new Api.contacts.ResolveUsername({
    username: username
  }));
```

I have tried your code but it gets the same response as my method, they use contacts.ResolveUsername first

**Comment by painor** [comment]
are you sure? do you not get an "accessHash" attribute ?

**Comment by laocoi** [comment]
@painor I don't see the accessHash attr in the original response from ResolveUsername

```
{
  CONSTRUCTOR_ID: 2131196633,
  SUBCLASS_OF_ID: 4033196968,
  className: 'contacts.ResolvedPeer',
  classType: 'constructor',
  peer: {
    CONSTRUCTOR_ID: 1498486562,
    SUBCLASS_OF_ID: 47470215,
    className: 'PeerUser',
    classType: 'constructor',
    userId: Integer { value: xxxn }
  },
  chats: [],
  users: [
    {
      CONSTRUCTOR_ID: 1073147056,
      SUBCLASS_OF_ID: 765557111,
      className: 'User',
      classType: 'constructor',
      flags: 33669163,
      self: false,
      contact: false,
      mutualContact: false,
      deleted: false,
      bot: true,
      botChatHistory: true,
      botNochats: true,
      verified: false,
      restricted: false,
      min: false,
      botInlineGeo: false,
      support: false,
      scam: false,
      applyMinPhoto: true,
      fake: false,
      botAttachMenu: false,
      premium: false,
      attachMenuEnabled: false,
      id: [Integer],
      accessHash: [Integer],
      firstName: 'xxx',
      lastName: null,
      username: 'xxx',
      phone: null,
      photo: [Object],
      status: null,
      botInfoVersion: 32,
      restrictionReason: null,
      botInlinePlaceholder: null,
      langCode: null
    }
  ]
}
```

Then I use res.peer to send message, it work. The FloodWaitError appear after around 50-100 request

**Comment by painor** [comment]
![image](https://user-images.githubusercontent.com/30215770/184656163-78b22444-2e6d-4d94-b911-5c40824c31e0.png)

**Comment by painor** [comment]
getEntity should also give you that result.

**Comment by laocoi** [comment]
@painor I can't use the current account to use that method now, because it use the contacts.ResolveUsername first, so I will get FloodWaitError

Btw if I have accessHash, can I send message without FloodWaitError ?

**Comment by painor** [comment]
only if you use the .users result.

**Comment by laocoi** [comment]
@painor Thank you. I think my problem came from converting the raw number to bigInt.

How can I convert raw accessHash: -12345678 to something like this: `Integer { value: -12345678n }` ?

**Comment by laocoi** [comment]
@painor I think my problem came from convert raw string to Bigint

I am getting problem with conver accessHash from raw. 
```
Helpers.returnBigInt(-3563441647559576810)
```
Getting result `Integer { value: 3563441647559576576n }` ?

Can you tell me why the last three number is different?

**Comment by laocoi** [comment]
I try `Helpers.returnBigInt('-3563441647559576810')` and it work. I think there is a bug at here

**Comment by painor** [comment]
it's not a bug. this is just how javascript works.
![image](https://user-images.githubusercontent.com/30215770/184846779-9d939ba8-fdca-42f8-8b1a-fb587d78bab1.png)

you can't use normal numbers to represent big integers
