### ISSUE TITLE
How to download document with just documentId in Api.ReactionCustomEmoji

### ISSUE THREAD

**Issue by kaatt** [gram-js/gramjs#405]
`ReactionCustomEmoji` just has `documentId`, how do i download the document?

**Comment by painor** [comment]
Do you have an example of a custom emoji that only has a documentId ? (like a message in a channel so I can take a look at it)

**Comment by zubiden** [comment]
https://corefork.telegram.org/method/messages.getCustomEmojiDocuments

**Comment by painor** [comment]
> https://corefork.telegram.org/method/messages.getCustomEmojiDocuments

ah so it's very new. do you know how to access this on telegram desktop or mobile ?

**Comment by kaatt** [comment]
its only for telegram premium members
