### ISSUE TITLE
How to send stickers correctly?

### ISSUE THREAD

**Issue by kaatt** [gram-js/gramjs#414]
```typescript
const file = filePath
const msgSendParams = {
  file,
  attributes: [
    new Api.DocumentAttributeSticker({ stickerset: new Api.InputStickerSetEmpty(), alt: '😂' }),
    // doesn't work either: new Api.DocumentAttributeSticker({ stickerset: new Api.InputStickerSetID({ accessHash: ss.accessHash, id: ss.id }), alt: '' }),
    new Api.DocumentAttributeFilename({ fileName: fileName }),
  ],
}
await client.sendMessage(threadID, msgSendParams)
```
Altho this sends the sticker, the sidebar says " Sticker" instead of "😂 Sticker" in telegram app. Also sending webm stickers don't render in telegram app.

**Comment by painor** [comment]
I think the emoji part only happens when you send a sticker from a sticker set not from a file ?

**Comment by painor** [comment]
you need the sticker id/access hsah from somewhere and then you can use it with `InputMediaDocument`
