### ISSUE TITLE
InviteToChannelRequest: Uncaught (in promise) TypeError: bigInt is undefined

### ISSUE THREAD

**Issue by kimnamcham** [gram-js/gramjs#42]
How to call request InviteToChannelRequest? This is my code:
```

const channelIdInvite = inviteId.value
const InputPeerUser = []
    listUsers.forEach(function (user) {
        InputPeerUser.push(new types.InputUser({
            user_id: user["id"],
            access_hash: user["accessHash"],
        }))
    })
    const InputChannel = new types.InputChannel({
        channel_id: parseInt(channelIdInvite),
        access_hash: 4408054091230359217,
    })
    const result = await client.invoke(new functions.channels.InviteToChannelRequest(
        {
            channel: InputChannel,
            users: InputPeerUser,
        },
    ))
```
This is console log error:

> Uncaught (in promise) TypeError: bigInt is undefined
>     readBufferFromBigInt webpack://gramjs/./gramjs/Helpers.js?:62
>     getBytes webpack://gramjs/./gramjs/tl/types/index.js?:531
>     getBytes webpack://gramjs/./gramjs/tl/functions/channels.js?:1805
>     RequestState webpack://gramjs/./gramjs/network/RequestState.js?:13
>     send webpack://gramjs/./gramjs/network/MTProtoSender.js?:289
>     _callee7$ webpack://gramjs/./gramjs/client/TelegramClient.js?:691
>     Babel 10
>     <anonymous> file:///Users/apple/congviec/WorkSpace/TelegramProject/gramjs-master/examples/simpleLogin.js:206
>     EventListener.handleEvent* file:///Users/apple/congviec/WorkSpace/TelegramProject/gramjs-master/examples/simpleLogin.js:177
> 

What 's wrong? Anyone help, pls?

**Comment by foodornt** [comment]
I think you need to make a tsconfig file
just type `tsc --init`

**Comment by mannguyen0107** [comment]
@kimnamcham have you been able to get this working? it seem that this has nothing to do with gramjs maybe @painor  can close this issue to clean the issues up abit :D
