### ISSUE TITLE
Dc problem of 'GetFile'

### ISSUE THREAD

**Issue by po-lan** [gram-js/gramjs#433]
When I want to download a file through Api. upload. GetFile, I sometimes report an error.

The following is the error report

    code: 303
    errorMessage: 'The file to be accessed is currently stored in DC 4 (caused by upload.GetFile)'
    newDc: 4

And in‘ https://gram.js.org/tl/upload/GetFile ’There is no corresponding solution

**Comment by painor** [comment]
You'd have to create a sender for the specific DC and use it to download the files. 
```sender = await client.getSender(e.newDc);```

and then do
```await sender.send(request)```

**Comment by po-lan** [comment]
OK，I checked the content of 'client/downloads. ts' and solved the problem according to your suggestions and code
