### ISSUE TITLE
Is the delete/editMessage working?

### ISSUE THREAD

**Issue by ncesar** [gram-js/gramjs#442]
I have tried with several examples but none of them work to delete/edit messages.
I have tried to delete a message like this:

```
  const result = await client.invoke(
    new Api.messages.DeleteMessages({
      id: [22],
      revoke: true,
    }),
  );
  console.log(result, 'result');
```

no success. Console is printed with this:
```
{
  CONSTRUCTOR_ID: 2228326789,
  SUBCLASS_OF_ID: 3469983854,
  className: 'messages.AffectedMessages',
  classType: 'constructor',
  pts: 661,
  ptsCount: 0
} result
```
I also tried with this: 

```
      await client.deleteMessages(secondChatId, [17, 18, 20], {
        revoke: true,
      });
```

and not working as well.
And edit message:

```
  await client.editMessage(secondChatId, {
    message: 22,
    text: 'Test edit',
  });

Nothing is printed.
```

**Comment by painor** [comment]
I don't get it. what do you want it to print? 

These two should be working fine.

The first one will delete messages of ID 17,18,20 from secondChatId and the other will edit message 22 from secondChatId

**Comment by ncesar** [comment]
The messages are not being deleted/edited. This is what I'm facing :/

**Comment by painor** [comment]
maybe you're trying to delete the wrong messages? 
There are also some limitation to deleteting a message fi you are using a bot not a user.

**Comment by ncesar** [comment]
I'm pretty sure I was deleting the correct ID. Are you able to reproduce it? I was using a user in a channel group.

**Comment by ncesar** [comment]
Sorry @painor everything is working as expected.

The problem that I was facing is that I was trying to delete the message using the messageID from another channel. Sorry.
