### ISSUE TITLE
Handle FloodWaitError myself

### ISSUE THREAD

**Issue by gunrosen** [gram-js/gramjs#445]
I see the very close document [here]( https://painor.gitbook.io/gramjs/getting-started/handling-errors)
But it seems gramjs handle it, let me waiting and just log info to console. 
For example: 
` [Sleeping for 45s on flood wait (Caused by contacts.ResolveUsername)]`
My question is 
`is there any way to handle FloodWaitError myself. That means I can handle it like an exception maybe?`
Thank you.

**Comment by gunrosen** [comment]
Sorry, it is my mistake.
It seems throw exception when floodSleepThreshold exceed

**Comment by painor** [comment]
you can also reduce the threshold. it's 60 sec by default
