### ISSUE TITLE
[Browser] Browser-based implementation missing the functions/types object

### ISSUE THREAD

**Issue by bryancresswell** [gram-js/gramjs#45]
As mentioned in title, I compiled it with `npx webpack` and when I inspect the entire `gramjs` variable, I don't see any functions/types field inside it. As such I am not able to make these calls on the browser. Any idea?

Also, I notice that on the browser implementation, on line 58, the example should be `const { StringSession } = gramjs.sessions` instead of `const { StringSession } = gramjs.session`.

Any help is appreciated.

**Comment by painor** [comment]
You are correct it should be sessions instead of session. as for the functions they are in gramjs.tl 
there are requests and constructors. you can do console.dir(gramjs) to see everything. 
![image](https://user-images.githubusercontent.com/30215770/99730217-5d273180-2abc-11eb-8876-e7ea5df30e37.png)

**Comment by bryancresswell** [comment]
Indeed, @painor, I did that and I saw the entire structure of it, but I can't see `functions.Messages` for example if I want to run the `GetMessagesRequest` method.

**Comment by painor** [comment]
Currently, it's under `requests.messages`  and it's `GetMessages`. The requests postfix is no longer present. Will add docs soon to explain all of that in the future.

**Comment by bryancresswell** [comment]
Got it thanks! @painor. Do you want me to send a PR to update the examples?

**Comment by painor** [comment]
Yes sure!

**Comment by bryancresswell** [comment]
Also, I've been doing the flow as mentioned, `client.invoke(new requests.messages.GetMessage(chat, limit=None))` but it keeps failing with this error: 
```
api.js:325 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at VirtualClass.getBytes (api.js:325)
    at new RequestState (RequestState.js:6)
    at MTProtoSender.send (MTProtoSender.js:257)
    at TelegramClient.invoke (TelegramClient.js:594)
    at <anonymous>:1:8
```

Do you have any clue? Am I doing something wrong?

**Comment by painor** [comment]
what's None? also max limit is 100

**Comment by bryancresswell** [comment]
Hi @painor, I'm following the documentation on Telethon, which mentions that the `get_messages` method can take a limit arg of `None`, which retrieves all the messages since the start of the chat. 

I've done some extra digging and found that `api.js` seems to throw the array as it tries to call `this[arg].length` in the for loop, but when I do the above, and add the proper argument (`id`), setting a breakpoint shows `arg` as `"id"`, but `this` doesn't happen to have any values available in the `this` variable, which then results in `this['id']` as undefined.

**Comment by painor** [comment]
Telethon's get_messages is a friendly method that accepts any limit and then chunks it into lists of 100 for requests. so if you do get_messages(limit=200) it will call requests.messages.GetHistory 2 times which you can find here https://github.com/LonamiWebs/Telethon/blob/64d751a39717ccf94f786867648c3ce11e652631/telethon/client/messages.py#L137. 
```requests.messages.GetHistory``` is a raw method provided by telegram and they only accept chunks of 100.
all functions under `tl.requests` are RAW API functions which you can find them here https://core.telegram.org/methods. So far this is the ported part of Telethon. The friendly methods are not ported yet.

**Comment by painor** [comment]
the documentation now explains this a bit more https://painor.gitbook.io/gramjs/
