### ISSUE TITLE
Is possible to work with tdata folders?

### ISSUE THREAD

**Issue by loss-and-quick** [gram-js/gramjs#458]
I need to work with telegram's tdata folders, but gram.js doesn't provide functionality for this

**Comment by painor** [comment]
https://gist.github.com/painor/0eabf0095d18bdc49ec0d2220998a38d can probably try this

**Comment by loss-and-quick** [comment]
> https://gist.github.com/painor/0eabf0095d18bdc49ec0d2220998a38d can probably try this


I need convert `tdata` folder to gram.js session string

**Comment by painor** [comment]
Yes that's what the link I sent does.

**Comment by loss-and-quick** [comment]
> Yes that's what the link I sent does.

Is this some kind of meta humor or something?
How can 'Import GramJS session into Telethon' be the solution to my tdata issue?

**Comment by painor** [comment]
ops my bad wrong gist https://gist.github.com/painor/7ef6c68a1d5bdea01a2f58b1de147104
