### ISSUE TITLE
`iterDownload` throws Invalid offset error for any offset except 0

### ISSUE THREAD

**Issue by rtcq** [gram-js/gramjs#465]
When I call `client.iterDownload` with a specific offset there is an error: 
```
RPCError: 400: OFFSET_INVALID (caused by upload.GetFile)
```
```ts
    const iter = client.iterDownload({
        file: new Api.InputDocumentFileLocation({
            id: bigInt(5904624792618667783n),
            fileReference: Buffer.from([0x02, 0x63, 0x4b, 0xbb, 0xf5, 0x00, 0x00, 0x03, 0xd0, 0x63, 0xc1, 0xcc, 0xdc, 0x34, 0x55, 0xd7, 0x15, 0xc9, 0x6e, 0x9f, 0x15, 0x85, 0x4a, 0x84, 0x97, 0xc5, 0x2f, 0xe7, 0xa5]),
            accessHash: bigInt(567999851661693602n),
            thumbSize: ''
        }),
        offset: bigInt(1638400) // Total file size is 2862601,
        requestSize: 64 * 1024
    })
    for await (const chunk of iter) {
        console.log("Chunk length", chunk.length)
    }
```
The download starts when the offset is 0 but when it's another value (e.g. when I seek audio and there's an HTTP Range value) it throws this error; while the condition for the `offset` documented [here](https://core.telegram.org/api/files#downloading-files) is 
> The parameter offset must be divisible by 4 KB

`1638400 % 4 == 0` is `true`, and I could not figure out the problem.
Also, there was another condition:
> In any case the requested part should be within one 1 MB chunk from the beginning of the file, i. e.
> - offset / (1024 * 1024) == (offset + limit - 1) / (1024 * 1024).

 Which I don't think is the problem since the limit should always be 1?!

Note Telethon `client.iter_download` had no issue

**Comment by musa-42** [comment]
Did you find a solution?

**Comment by rtcq** [comment]
I ended up using JS back then, but now commented out this line and it works https://github.com/gram-js/gramjs/blob/8cbab35c7035528432c5af40100ae55658ec9bef/gramjs/client/downloads.ts#L241
Seems `bad` variable is not getting calculated properly, and since my offset is already a valid offset it should have been 0 but it was 25; so the offset was changed to 1638375 and was invalid.

**Comment by musa-42** [comment]
@painor
