### ISSUE TITLE
How to enumerate chats where user is connected?

### ISSUE THREAD

**Issue by xluckydegen** [gram-js/gramjs#470]
Hi,

I can't find a way how to enumerate chats where the logged user account is connected.

Is there any way?

Or what is the preferred way how to get chatId for channel/group? Right now I'm doing it by listening to messages and waiting for the first one, but I believe there has to be a better way.

Thank you

**Comment by xluckydegen** [comment]
I just found `Api.channels.GetInactiveChannels` but can't find any opposit `GetActiveChannels` or something like that.

Thanks for any advice

**Comment by painor** [comment]
can also use https://gram.js.org/beta/classes/TelegramClient.html#getDialogs
