### ISSUE TITLE
Chat_id is always invalid when chat id is correct

### ISSUE THREAD

**Issue by anggi117** [gram-js/gramjs#490]
Is any problem with my code, its always showing error CHAT_ID_INVALID

my code :
![image](https://user-images.githubusercontent.com/42998655/221466966-06fd16a6-6af1-4ef0-94e3-05f935d268da.png)

Proof my chat id valid :
![image](https://user-images.githubusercontent.com/42998655/221467020-3bee874f-4fe2-4341-b61b-741cdadced34.png)

**Comment by painor** [comment]
That usually means you're using the wrong method. 
That method only works for small groups not supergorups.

**Comment by anggi117** [comment]
> That usually means you're using the wrong method. That method only works for small groups not supergorups.

I see, thankss broo
