### ISSUE TITLE
How to filter incoming messages from specific channel? message.fromId is null

### ISSUE THREAD

**Issue by siandreev** [gram-js/gramjs#496]
I'm trying to listen for messages from the specific channel:

```
    const client = new TelegramClient(stringSession, apiId, apiHash, {
        connectionRetries: 5
    });
    await client.connect();
    await client.getMe();

    client.addEventHandler(console.log, new NewMessage({}));
```

event handler works well, but all messages from channels has `fromId` eq null. So my question is how can I filter messages to listen only for the specific channel in the  `client.addEventHandler` callback?

**Comment by painor** [comment]
you can try filtering the event.message.chatId

**Comment by sinhpn92** [comment]
I have same issue. Can you please explain How can filtering the `fromId` from `event.message.chatId`? @painor @siandreev
