### ISSUE TITLE
Supergroup has the chat's className

### ISSUE THREAD

**Issue by chabwino** [gram-js/gramjs#497]
If I add my bot to a regular group, ```event.message.chat.className``` is a ```Chat``` (that's how it should be).   
But if I add my bot to a supergroup (still a chat!), ```event.message.chat.className``` is a ```Channel``` (like if I would add it to a channel).   
Also supergroup and channels have the same ```CONSTRUCTOR_ID``` and ```SUBCLASS_OF_ID```, which makes impossible to identify their type.

Like so:
```
Group: {
  CONSTRUCTOR_ID: 1103884886,
  SUBCLASS_OF_ID: 3316604308,
  className: 'Chat'
}
```   
```
Supergroup: {
  CONSTRUCTOR_ID: 2200278116,
  SUBCLASS_OF_ID: 3316604308,
  className: 'Channel'
}
```   
```
Channel: {
  CONSTRUCTOR_ID: 2200278116,
  SUBCLASS_OF_ID: 3316604308,
  className: 'Channel'
}
```

**Comment by painor** [comment]
Supergroups are actually channels with the attribute .broadcast = false.
