### ISSUE TITLE
Could the browser version be made  to work with cloudlfare workers ?

### ISSUE THREAD

**Issue by divyam234** [gram-js/gramjs#506]
I tried using the browser module  in cf workers.Although the code successfully  started by the workers bu it  didn't respond to any calls whenever I called client.connect().It was also making the socket connection to telegram server

**Comment by painor** [comment]
I haven't worked with cloudflare workers before, is it similar to AWS ? 
if you want to listen to incoming events the app needs to be running 24/7

**Comment by divyam234** [comment]
Yeah its like aws lambda serverless platform.But its support all web apis that currently runs in browser.

**Comment by painor** [comment]
I really got no idea sadly;
maybe someone else with better experience sees it.

**Comment by phongplus** [comment]
someone is success run in cloudflare workers ?
