### ISSUE TITLE
messages AddChatUser sends back CHAT_ID_INVALID

### ISSUE THREAD

**Issue by iliyaM** [gram-js/gramjs#510]
```
Api.Updates = client.invoke(
          new Api.messages.AddChatUser({
            chatId: targetGroup.id,
            userId: users[i].id,
            fwdLimit: 43
          })
));
```

Maybe there is another method to do this?
the traget group is not a chat is its a MEGA GROUP. but even if I pass the ID from the CHATS arrray className === 'Chat' its still gives the same error.

 code: 400,
  errorMessage: 'CHAT_ID_INVALID'

**Comment by iliyaM** [comment]
@iliyaM Hello all this is actually my issue

**Comment by SamHoque** [comment]
Did you find a solution for this?

**Comment by iliyaM** [comment]
Yes. there is a difference between CHAT and GROUP. 
I don't know what qualifies as a CHAT I think its the amount of participants and or messages inside.
but once it becomes a CHANNEL you need to use a different method for adding users there.

**Api.channels.InviteToChannel**

if you need to know if your entity is a CHAT or a CHANNEL type you can filter them by the field megagroup: boolean.
so that's why it didn't work for me.
I tried to add people to the CHANNEL by calling a method for adding users to a CHAT.
