### ISSUE TITLE
How leave groups,chats,channels?

### ISSUE THREAD

**Issue by loss-and-quick** [gram-js/gramjs#515]
I am storing ids of those types(they have type `bigInt.BigIntenger`) and i have to leave all of them
How i can leave them by id?

**Comment by painor** [comment]
first call client.getDialogs to load up local cache then you can use https://gram.js.org/tl/channels/LeaveChannel#channelsleavechannel

**Comment by loss-and-quick** [comment]
> first call client.getDialogs to load up

Soo you mean that i can not use directly ids of chats or groups?

**Comment by painor** [comment]
if the library has never seen the group id before no, 
that's why it's better to call getDialogs at startup (when you log in for the first time) so the library can cache them.
