### ISSUE TITLE
Using  file names with extension  in caption is always parsed to http link  

### ISSUE THREAD

**Issue by divyam234** [gram-js/gramjs#527]
![Screenshot 2023-05-09 161947](https://github.com/gram-js/gramjs/assets/47589864/22dbbd8f-92d3-49b0-b2ac-00790672b83d)

How do I prevent this?

**Comment by painor** [comment]
that's telegram's ui. even if you send that using the desktop client for example you'll get the same result

**Comment by divyam234** [comment]
I have sent same file with pyrogram its not parsing in that mode
