### ISSUE TITLE
Preventing Auth Flood Error in Test Environment When Making Frequent Changes and Reconnections to Telegram Server.

### ISSUE THREAD

**Issue by SarkarKurdish** [gram-js/gramjs#530]
How can I prevent the auth flood error from occurring in my test environment? As I make frequent changes and restarts, there are multiple reconnections to the Telegram server, resulting in the flood error message: 

`FloodWaitError: A wait of 1057 seconds is required (caused by auth.ImportBotAuthorization).`

 I have attempted to resolve the issue by setting the test servers to true, but this has not had any effect. Here is an example of the code I'm using:

```javascript
const client = new TelegramClient(stringSession, apiId, apiHash, {
  connectionRetries: 5,
  testServers: true,
  floodSleepThreshold: 60,
});
```

I would greatly appreciate any advice on how to mitigate this error.

**Comment by painor** [comment]
You are probably logging in each time you refresh. make sure your string session is not empty and remove the bot token from the .start() method.

**Comment by SarkarKurdish** [comment]
@painor my string session is not empty but I do have bot tokenm why is that a problem? what If I want to work on a bot not my main account?

**Comment by SarkarKurdish** [comment]
@painor anything you can think of that could solve the rate limit ?

**Comment by painor** [comment]
but the ImportBotAuthorization error means that your string session is empty or invalid. 
I don't know what else I can link but basically you only need to call .start() once to generate the string session.
then you can use the same session to run it multiple times and you only need to call .connect()

**Comment by SarkarKurdish** [comment]
@painor , thank you. You were right—I was calling "start" every time I ran my script, when I only needed to do that once in order to obtain the session string.
