### ISSUE TITLE
Missing MTProto Entity: Please, make sure to add TL definition for ID 3424265246

### ISSUE THREAD

**Issue by obius-byte** [gram-js/gramjs#536]
Hello! 

installed: npm i telegram@browser
in package.json: "telegram": "^2.17.3"
in the console for some reason 2.17.0 (screenshot / logs)

p.s. - on 2.15.9 it works without problems
[console-export-2023-5-16_1-34-21.txt](https://github.com/gram-js/gramjs/files/11482429/console-export-2023-5-16_1-34-21.txt)

![изображение](https://github.com/gram-js/gramjs/assets/18569827/552738dc-a8a9-4734-9a18-1c8063be4c55)

**Comment by painor** [comment]
Clear the local storage of your browser

**Comment by obius-byte** [comment]
> Clear the local storage of your browser

Thanks! Helped deleting GramJs:apiCache in localStorage.
