### ISSUE TITLE
Inconsistent fileSize type in downloadFile method

### ISSUE THREAD

**Issue by YouXam** [gram-js/gramjs#542]
Hello,

I found a discrepancy in the downloadFile method as described in the [documentation](https://gram.js.org/beta/classes/TelegramClient.html#downloadFile).

According to the example provided, the fileSize parameter is a string "m", as shown below:

```js
const photo = message.photo;  
const buffer = await client.downloadFile(  
  new Api.InputPhotoFileLocation({  
    id: photo.id,  
    accessHash: photo.accessHash,  
    fileReference: photo.fileReference,  
    thumbSize: size.type  
  }),  
  {  
    dcId: photo.dcId,  
    fileSize: "m",  
  }
);
```

However, when I tried to use the method in this way, I encountered a TypeError: fileSize.lesser is not a function.
```
TypeError: fileSize.lesser is not a function
    at Object.getAppropriatedPartSize (.../node_modules/telegram/Utils.js:914:18)
    at downloadFileV2 (.../node_modules/telegram/client/downloads.js:269:36)
    at .../index.js:51:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
I managed to resolve this issue by changing fileSize to an object with a method lesser:

```js
const photo = message.photo;
const buffer = await client.downloadFile(
  new Api.InputPhotoFileLocation({
    id: photo.id,
    accessHash: photo.accessHash,
    fileReference: photo.fileReference,
    thumbSize: size.type
  }),
  {
    dcId: photo.dcId,
    fileSize: { lesser : x => x < size.size } // assuming size.size is a number
  }
);
```

It appears that the documentation might not align with the actual usage of the method. If my understanding is correct, could the documentation be updated to reflect this?

**Comment by painor** [comment]
hmm yes you are right the documentation should be updated.

We used to use the pickFileSize but telegram has added some updates and now need to pass the actual size.

the reason it expects something with lesser is because it's expecting a big int. 
so you can just do bigInt(your_number_file_sze)

**Comment by YouXam** [comment]
> hmm yes you are right the documentation should be updated.
> 
> We used to use the pickFileSize but telegram has added some updates and now need to pass the actual size.
> 
> the reason it expects something with lesser is because it's expecting a big int. so you can just do bigInt(your_number_file_sze)

@painor  Are you referring to the same bigInt as the built-in JavaScript BigInt? As far as I know, BigInt doesn't have a lesser method and I'm still encountering the TypeError: fileSize.lesser is not a function error in my tests. Could you please clarify this?

**Comment by YouXam** [comment]
I've found the relevant code definition [here](https://github.com/gram-js/gramjs/blob/8cbab35c7035528432c5af40100ae55658ec9bef/gramjs/client/downloads.ts#LL24C19-L24C36). And I've managed to fix the issue.

I used the big-integer library like this:

```javascript
const bigInt = require("big-integer");
// ...
const buffer = await client.downloadFile(
  new Api.InputPhotoFileLocation({
    id: photo.id,
    accessHash: photo.accessHash,
    fileReference: photo.fileReference,
    thumbSize: size.type
  }),
  {
    dcId: photo.dcId,
    fileSize: bigInt(file_size)
  }
);
// ...
```
Thank you for your response.
