### ISSUE TITLE
messages.GetHistory throw new Error(`Cannot cast ${toWrite} to any kind of ${target}`);

### ISSUE THREAD

**Issue by Almurik** [gram-js/gramjs#544]
I am able to authenticate and call successfuly contacts.ResolveUsername which returns channelid and accesshash but calling messages.GetHistory with these values always throws cast error:

new Error(`Cannot cast ${toWrite} to any kind of ${target}`);
Error: Cannot cast [object Object] to any kind of peer

How to solve this?

The code is here:
```ts
const { TelegramClient } = require("telegram");
const { StringSession } = require("telegram/sessions");
const { Api } = require("telegram/tl");
const input = require("input"); // npm i input

const apiId = 28129639;
const apiHash = '4d40b72c337266c615e12f80fa1f9245';
const stringSession = new StringSession("xxxxxxxx"); // fill this later with the value from session.save()

(async () => {
  console.log("Loading interactive example...");
  const client = new TelegramClient(stringSession, apiId, apiHash, {
    connectionRetries: 5,
  });
  await client.start({
    phoneNumber: async () => await input.text("Please enter your number: "),
    password: async () => await input.text("Please enter your password: "),
    phoneCode: async () =>
      await input.text("Please enter the code you received: "),
    onError: (err) => console.log(err),
  });
  console.log("You should now be connected.");
  /*console.log(client.session.save()); // Save this string to avoid logging in again*/

  const result = await client.invoke(
    new Api.contacts.ResolveUsername({
      username: 'xxxxxx',
    })
  );

  console.log('Access hash:', result.chats[0].accessHash.value);
  console.log('Channel id:', result.chats[0].id.value);  
  let access_hash = result.chats[0].accessHash.value;
  let id = result.chats[0].id.value;
  const messages = await client.invoke(
    new Api.messages.GetHistory({
      peer: {
        _: 'inputPeerChannel',
        channel_id: id,
        access_hash: access_hash
      },
      limit: 20,
  })
  );
  console.log('messages', messages.messages);
})();
```

**Comment by painor** [comment]
1) Don't use .value since the id and accessHash are big ints not numbers. (just pass the value directly) 
2) That's not how you create an object in gramJS. it's new Api.InputPeerChanne({channelId:id,accessHash:hash});
3) you can just pass the username directly to GetHistory

**Comment by Almurik** [comment]
> 1. Don't use .value since the id and accessHash are big ints not numbers. (just pass the value directly)
> 2. That's not how you create an object in gramJS. it's new Api.InputPeerChanne({channelId:id,accessHash:hash});
> 3. you can just pass the username directly to GetHistory

Could you please explain : 2. That's not how you create an object in gramJS. it's new Api.InputPeerChannel({channelId:id,accessHash:hash}); How can I use with GetHistory? 

I passed the values directly (without .value) and still getting same error

**Comment by painor** [comment]
```ts
const messages = await client.invoke(
    new Api.messages.GetHistory({
      peer: new Api.InputPeerChannel({
        channelId: id,
        accessHash: access_hash
      }),
      limit: 20,
  })
  );
```

**Comment by Almurik** [comment]
Sorry, both works. I put  
  channel_id: id,
  access_hash: access_hash

as in telegram api

instead of 

channelId: id,
accessHash: access_hash

This works.  Where to get these correct variable names? study code on github? cause at https://gram.js.org/tl/messages/GetHistory it links to telegram api with wrong names.

**Comment by Almurik** [comment]
painor's solution worked

**Comment by painor** [comment]
You can get them at https://gram.js.org/beta/classes/Api.InputPeerChannel.html

**Comment by Almurik** [comment]
> You can get them at https://gram.js.org/beta/classes/Api.InputPeerChannel.html

Thx!
