### ISSUE TITLE
Accessing messages.GetHistory orf private channel returns error

### ISSUE THREAD

**Issue by Almurik** [gram-js/gramjs#545]
How to access message.GetHistory of the private channel where autenticated user is a member? There is no channel username to use with contacts.ResolveUsername hence I cant obtain access_hash. Also should private channel id have 100 added as a prefix?

**Comment by painor** [comment]
use client.getDialogs to get a list of groups that you are in.
Yes private channes have a "-100" prefix (this is just to help the library know it's a channel. the real ID doesn't have that)

**Comment by Almurik** [comment]
Thank you so much for the promt answer. It worked!
