### ISSUE TITLE
How to create a public Channel?

### ISSUE THREAD

**Issue by Almurik** [gram-js/gramjs#547]
I am trying to use channels.CreateChannel but getting error 406 even though I have only one private channel for the user.

**Comment by painor** [comment]
Try to not pass extra arguments you don't need to create channel. (like address,geoPoint etc)

**Comment by Almurik** [comment]
OK. Will try in a moment. Once it worka is going to be a public or private channel?  Title is a username? Or I need to setup username with UpdateChannel afterwards?

**Comment by Almurik** [comment]
I was able to create a channel after I took extra arguments out. Channel is private. How to make it public now?

**Comment by painor** [comment]
You have to setup a new username after you create it.
You need two requests to create a public channel.

**Comment by Almurik** [comment]
const result = await client.invoke(
    new Api.channels.UpdateUsername({
      channel: channetId.value,
      username: "xxxxx",
    })
  );

I was able to setup username only after I input channeld.value. Was getting cast error with just channelId. 

Thank you so much for all the help! Amazing job you are doing replying so quickly.
