### ISSUE TITLE
couldnt find NewMessage on the browser version

### ISSUE THREAD

**Issue by ongspxm** [gram-js/gramjs#556]
managed to compile and use most of the feature, i face a problem when trying to set up the eventHandler for messages.

problem 1: 
https://painor.gitbook.io/gramjs/getting-started/updates-events
unable to find the `NewMessage` type. (using the browser version, so i only have a telegram object, please point me to the right path, if available)

problem 2:
unable to clear handlers if i dun use the type
```
for e in client.listEventHandlers():
    client.removeEventHandler(e)
```

all the event handlers are still there after running above code

**Comment by painor** [comment]
in the browser version you can find it in object.events I believe.
As for deleting events you can loop over client._eventBuilders and delete from there if you want.

**Comment by ongspxm** [comment]
right, that works, thanks a lot
