### ISSUE TITLE
RPCError: 401: AUTH_KEY_UNREGISTERED  while using signInUserWithQrCode on browser

### ISSUE THREAD

**Issue by divyam234** [gram-js/gramjs#563]
![Screenshot from 2023-07-26 19-48-23](https://github.com/gram-js/gramjs/assets/47589864/65cb1631-96b7-43c7-ac04-a5bb5a35ab85)

I think getMe is causing this error as user is not authenticated during the flow

**Comment by painor** [comment]
What version and what code are you using ?

**Comment by divyam234** [comment]
2.18.3 for browser

**Comment by painor** [comment]
ah 2.18.3 is not ready yet. Can you use 2.17.X

**Comment by divyam234** [comment]
Which one is compatible with browser?

**Comment by painor** [comment]
[2.17.9](https://www.npmjs.com/package/telegram/v/2.17.9) probably
