### ISSUE TITLE
Client disconnects after one request

### ISSUE THREAD

**Issue by maheshbansod** [gram-js/gramjs#62]
After making one raw request through gramjs, it went through and returned the correct response but a few seconds after that I got this error on the console:
```
{ Error: Invalid checksum (1241442304 when 1399867364 was expected). This packet should be skipped.
    at FullPacketCodec.<anonymous> (/home/null/apps/epic-light-bot/node_modules/telegram/dist/network/connection/TCPFull.js:53:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/null/apps/epic-light-bot/node_modules/telegram/dist/network/connection/TCPFull.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) checksum: 1241442304, validChecksum: 1399867364 }
```
Any requests after this, result in an error saying it cannot send requests while disconnected:
```
Error: Cannot send requests while disconnected
    at MTProtoSender.send (/home/null/apps/epic-light-bot/node_modules/telegram/dist/network/MTProtoSender.js:199:19)
    at TelegramClient.<anonymous> (/home/null/apps/epic-light-bot/node_modules/telegram/dist/client/users.js:39:50)
    at Generator.next (<anonymous>)
    at fulfilled (/home/null/apps/epic-light-bot/node_modules/telegram/dist/client/users.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
I'm not sure if I'm doing something wrong. Everything works well, when I do `client.start` again.

Also, is there a way to disable the [DEBUG] logs on the console?

**Comment by maheshbansod** [comment]
The API call was `users.GetFullUser`
I made a smaller node js application to reproduce it:
```
const { TelegramClient } = require('telegram/dist')
const { StringSession } = require('telegram/dist/sessions');
const teletl = require('telegram/dist/tl');
const readline = require('readline');
const { Logger } = require('telegram/dist/extensions');

const apiId = process.env.API_ID // put your api id here [for example 123456789]
const apiHash = process.env.API_HASH // put your api hash here [for example '123456abcfghe']
const client = new TelegramClient(new StringSession(process.env.STRING_SESSION), apiId, apiHash, {
    connectionRetries: 3,
})

var username = 'justanotherlight';
client.start();
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});


Logger.setLevel("debug");

rl.question('make getfulluser? y for yes ', async (choice) => {

    if (choice != 'y') {
        return;
    }
    client.invoke(new teletl.Api.users.GetFullUser({ id: username }))
        .then((res) => console.log(res))
        .catch((err) => {
            console.log(err);
        });

    rl.close();
});
```

Apparently making multiple requests one after the other works if I do it in the above code, but if I wait and do nothing for like 30 seconds, it shows this 
```
[2021-03-11T11:23:15.453Z] [INFO] - [connection closed]
{ Error: Invalid checksum (2699144061 when 2396756994 was expected). This packet should be skipped.
    at FullPacketCodec.<anonymous> (/home/null/apps/test-gramjs/node_modules/telegram/dist/network/connection/TCPFull.js:53:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/null/apps/test-gramjs/node_modules/telegram/dist/network/connection/TCPFull.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) checksum: 2699144061, validChecksum: 2396756994 }

```

does it mean that I should do a `client.start` for every request if the requests are not that frequent(like a few minutes to a few hours)?

**Comment by painor** [comment]
that's very weird. I tried your code and it's been running fine for 10 min. are you sure you're not using a VPN or have an IPV6 or something weird like that ?

**Comment by maheshbansod** [comment]
Yea no it doesn't I think, one network I tried on had IPv6, but it had the same error as with the IPv4 one. Putting it on Heroku gives me the same thing too. So basically I see the same error message on different networks and different machines, so I can't make more than one request since the client is disconnected. Also, I don't use a VPN.
What should I be doing to fix this?
Is there any more information that I can provide to solve this problem?

**Comment by plukito** [comment]
Also get this error. In my case I called `messages.GetHistory`

```javascript
await telegram.invoke(new Api.messages.GetHistory({
    peer: new Api.InputPeerChat({
        chatId: parseInt(id)
    })
}));
```

**Comment by painor** [comment]
well one thing for sure is that ipv6 is not supported. 
As for getHistory try to pass the id directly instead of an InputPeerChat. It's very weird that this is happening.

**Comment by plukito** [comment]
Yes, already tried that, but got the same error. Is there any recommendation?

**Comment by painor** [comment]
which error are you getting btw the disconnect one ?

**Comment by plukito** [comment]
same as the author, the Invalid checksum error

**Comment by plukito** [comment]
I reinstalling everything and I haven't found any issue from checksum error.

All I did are removing yarn.lock and node_modules then ran `yarn install`

Thank you for your help @painor

**Comment by plukito** [comment]
Sorry, seems the invalid checksum error is reapearring this morning. I suspect the network, but then I tried to run the same function in telethon and it ran successfully.

Does anyone have any idea why does this error reoccurring despite having no code changes?

**Comment by painor** [comment]
I think the issue was in the TCP connection reader on slower connections. It might have been fixed in latest patch. you could also use `connection:ConnectionTCPObfuscated` in the args to try if it's better.
```    const client = new TelegramClient(new StringSession(stringSession), apiId, apiHash, { connection:ConnectionTCPObfuscated })```

**Comment by maheshbansod** [comment]
Yes, looks like it's fixed now. Thanks!
