### ISSUE TITLE
client.connect() resulted infinity loop of "Error: Not connected"

### ISSUE THREAD

**Issue by izulwahidin** [gram-js/gramjs#643]
so i want to create group chat using this code (sveltekit). reference [messagescreatechat](https://gram.js.org/tl/messages/CreateChat#messagescreatechat)

![carbon (6)](https://github.com/gram-js/gramjs/assets/22869335/a9c32d97-f38b-40e7-bd1e-e3fb6bc440c4)

but i got infinity loop of "Error: Not connected" on **client.connect()**

![23 02 2024_15 58 41_REC](https://github.com/gram-js/gramjs/assets/22869335/47637caf-d556-43d7-9534-c87f0f0f523b)

**Comment by izulwahidin** [comment]
nvm i found out that you can't nativelly run sessions you created on the web in node.

**Comment by 3lang3** [comment]
I have same issue

@izulwahidin do you solve this?

**Comment by izulwahidin** [comment]
> I have same issue
> 
> @izulwahidin do you solve this?

Yes, I got this error because I tried to use session that I created from web to node

If you create session on web you should also connect to web client and vice versa
