### ISSUE TITLE
the telegram account is blocked when i used gramjs. It happened twice

### ISSUE THREAD

**Issue by santiagz** [gram-js/gramjs#66]
I just copied and pasted the code, didn't change, didn't modify. 
And when sending several messages, everything was fine, but the next time when sending a message to myself, I got a ban, without explaining the reasons. 

I tried it on another account - the result is the same - a ban, but after sending one message.

here is my teamplate:

```
import { TelegramClient } from 'telegram'
import { StringSession }  from 'telegram/sessions'
import input from 'input'; // npm i input

const apiId = 123456
const apiHash = '123456abcdfg'
const stringSession = new StringSession(''); // fill this later with the value from session.save()
(async () => {
    console.log('Loading interactive example...');
    const client = new TelegramClient(stringSession, apiId, apiHash, { connectionRetries: 5 });
    await client.start({
        phoneNumber: async () => await input.text('number ?'),
        password: async () => await input.text('password?'),
        phoneCode: async () => await input.text('Code ?'),
        onError: (err) => console.log(err),
    });
    console.log('You should now be connected.');
    console.log(client.session.save()) // Save this string to avoid logging in again
    await client.sendMessage('me', { message: 'Hello!' });
})()
```

**Comment by painor** [comment]
telegram hates voip accounts. if your number is from a real sim then a simple email to the support would fix the issue and you won't have any issues with that number again. 

It also helps to specify the deviceModel and systemVersion and appVersion to something real in TelegramClient(). 
something like this

```
const client = new TelegramClient(new StringSession(stringSession), apiId, apiHash, {
    appVersion:"2.7.1",
    deviceModel:"PC",
    systemVersion:"Windows 10"
})
```

There is a discussion about it here https://github.com/LonamiWebs/Telethon/issues/824
