### ISSUE TITLE
args of progressCallback not at the correct order

### ISSUE THREAD

**Issue by yunyu950908** [gram-js/gramjs#708]
Hi, I found something confused while I'm trying to download media, the defination and comments of the args are conflict
<img width="1225" alt="image" src="https://github.com/user-attachments/assets/587dbbe7-1485-4773-b4c0-a0469f6b8ff6">

In doc site and in current latest commit on master branch, `progressCallback` defined as follows
notice that `downloaded` is the first arg and `total` is the second
https://github.com/gram-js/gramjs/blob/1094d124ff43a28af42955982db5fc099eb079b2/gramjs/client/downloads.ts#L16-L33

But here in `define.d.ts` , params of the `ProgressCallback` are opposite (and this is wrong)
https://github.com/gram-js/gramjs/blob/1094d124ff43a28af42955982db5fc099eb079b2/gramjs/define.d.ts#L66-L69

the actual behavior of progressCallback is given the first arg `downloaded` and the second arg `total`
https://github.com/gram-js/gramjs/blob/1094d124ff43a28af42955982db5fc099eb079b2/gramjs/client/downloads.ts#L434-L436

Is this intentional for some reason? or it's just a mistake?

**Comment by yunyu950908** [comment]
And this downloaded will not meet the end because the callback called before the downloaded update
https://github.com/gram-js/gramjs/blob/1094d124ff43a28af42955982db5fc099eb079b2/gramjs/client/downloads.ts#L424-L444

**Comment by painor** [comment]
You're correct it was just a mistake
