### ISSUE TITLE
Want to get all messages and updates in a Chat Group

### ISSUE THREAD

**Issue by soheil61** [gram-js/gramjs#79]
Hi, I want to get all messages and updates realtime in a group, which method should I use and how?

Also  how should I fill  "InputChannel" ? 
[new Api.InputChannel({...})]   ??

Cheers

**Comment by painor** [comment]
not sure why you need InputChannel ? don't you want to use updates for that ? https://painor.gitbook.io/gramjs/getting-started/updates-events
