### ISSUE TITLE
[Browser] 'TelegramClient' is not exported by browser/gramjs.js

### ISSUE THREAD

**Issue by sh-a-v** [gram-js/gramjs#8]
```
Rollup: Missing Export
'TelegramClient' is not exported by ../gramjs/browser/gramjs.js
```

And are you planning to add types? It’s very difficult to figure out without them.

**Comment by YouTwitFace** [comment]
GramJS is still in its alpha phase and will be getting docs and will most likely get types.

**Comment by painor** [comment]
@sh-a-v can you post the code you tried? you only need the gram.js file if you want to run it in browsers

**Comment by sh-a-v** [comment]
> 
> 
> @sh-a-v can you post the code you tried? you only need the gram.js file if you want to run it in browsers

I have a file `index.js` with this code:
```
import { TelegramClient } from './gramjs';
```
The file `gramjs.js` was copied from the directory `browser`.

**Comment by painor** [comment]
it should be working fine now with the latest update. Reopen if it's not
