### ISSUE TITLE
Example code does not work

### ISSUE THREAD

**Issue by Bramzor** [gram-js/gramjs#83]
Want to move from telethon (python) to nodejs but seems the example code from https://painor.gitbook.io/gramjs/ does not work (anymore).

```const { TelegramClient } = require('telegram')
const { StringSession } = require('telegram/sessions')
const input = require('input') // npm i input

const apiId = 111111
const apiHash = 'fcf............................'
const stringSession = new StringSession(''); // fill this later with the value from session.save()
(async () => {
    console.log('Loading interactive example...')
    const client = new TelegramClient(stringSession, apiId, apiHash, { connectionRetries: 5 })
    await client.start({
        phoneNumber: async () => await input.text('number ?'),
        password: async () => await input.text('password?'),
        phoneCode: async () => await input.text('Code ?'),
        onError: (err) => console.log(err),
    });
    console.log('You should now be connected.')
    console.log(client.session.save()) // Save this string to avoid logging in again
    await client.sendMessage('me', { message: 'Hello!' });
})()
```

Is not able to create the websocket connection.

```[2021-05-22T21:17:08.354Z] [INFO] - [Connecting to 149.154.167.51:80/TCPFull...]
[2021-05-22T21:17:08.354Z] [DEBUG] - [Connecting]
[2021-05-22T21:17:08.378Z] [DEBUG] - [Finished connecting]
[2021-05-22T21:17:08.379Z] [DEBUG] - [Connection success!]
[2021-05-22T21:17:08.379Z] [DEBUG] - [New auth_key attempt ...]
[2021-05-22T21:17:08.408Z] [ERROR] - [WebSocket connection failed attempt : 1]
[2021-05-22T21:17:09.409Z] [INFO] - [Connecting to 149.154.167.51:80/TCPFull...]
[2021-05-22T21:17:09.410Z] [DEBUG] - [Connecting]
[2021-05-22T21:17:09.433Z] [DEBUG] - [Finished connecting]
[2021-05-22T21:17:09.433Z] [DEBUG] - [Connection success!]
[2021-05-22T21:17:09.433Z] [DEBUG] - [New auth_key attempt ...]
[2021-05-22T21:17:09.455Z] [ERROR] - [WebSocket connection failed attempt : 2]
```

Why does it try to build the connection over port 80?  Also https://my.telegram.org/apps points towards 149.154.167.50:443 for production. Which does not match with the IP shown above.

Telegram version 1.5.23

**Comment by painor** [comment]
it should still be working fine. are you able to ping telegram's server ? ping 149.154.167.51

The 80 or 443 doesn't really matter that much.

**Comment by Bramzor** [comment]
I do not think it's connectivity or something like that because telethon just works.
`ping 149.154.167.51
PING 149.154.167.51 (149.154.167.51): 56 data bytes
64 bytes from 149.154.167.51: icmp_seq=0 ttl=52 time=19.402 ms
64 bytes from 149.154.167.51: icmp_seq=1 ttl=52 time=19.288 ms
^C
--- 149.154.167.51 ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 19.288/19.345/19.402/0.057 ms
 ~ telnet 149.154.167.51 80
Trying 149.154.167.51...
Connected to 149.154.167.51.
`

**Comment by painor** [comment]
that's very weird. it's just saying that the socket failed to connect to telegram. if you want to try 443 port use useWSS: true

    const client = new TelegramClient(new StringSession(stringSession), apiId, apiHash, {
        useWSS:true,
            })

**Comment by Bramzor** [comment]
Hoped that it would work over https but same issue.
Strange that it does work with telethon. Maybe because I already made a session with python that it does not allow me to create one with gramjs?
Running tests on the same client/IP so it's not a problem with connectivity.

**Comment by painor** [comment]
it shouldn't have anything to do with each other.  maybe you could try to ping the server from inside node? it could be an issue with node itself. from the logs it looks like it's not receiving any response from telegram server without even sending any. 

If you want to debug further you could try to add a console.log(e) in these 2 lines and it'll show the full error. 
https://github.com/gram-js/gramjs/blob/master/gramjs/network/MTProtoSender.ts#L205
https://github.com/gram-js/gramjs/blob/master/gramjs/network/MTProtoSender.ts#L832

**Comment by Bramzor** [comment]
Added the console.log line at connect and this is the result:
`
[2021-05-22T23:41:02.587Z] [ERROR] - [WebSocket connection failed attempt : 1]

ReferenceError: BigInt is not defined
`

**Comment by Bramzor** [comment]
Ow I feel so stupid....
Was running nodejs v9.11.2 which apparently does not work with this app.
Works using v15

**Comment by randybastian777** [comment]
> that's very weird. it's just saying that the socket failed to connect to telegram. if you want to try 443 port use useWSS: true
> 
> ```
> const client = new TelegramClient(new StringSession(stringSession), apiId, apiHash, {
>     useWSS:true,
>         })
> ```

work !!. thanks

**Comment by randybastian777** [comment]
> Does it work with node v16? It just hangs for me.

try above
