### ISSUE TITLE
Missing accessHash for owned channel.

### ISSUE THREAD

**Issue by justinemar** [gram-js/gramjs#97]
I'm getting all the available chats with `telegram.Api.messages.GetAllChats`
`        const res = await telegramClient.invoke(new API.messages.GetAllChats({exceptIds: []}));`

This returns the chat entities, all of the chats have accessHash in them except the chat where I am the owner. Instead there is a `migratedTo` object where the accessHash is located. This makes it hard to have a concise parser, is there any reason for this and any available methods where owned chats is treated as other chats?

// res.chats[0].accessHash
`undefined`
// res.chats[0].migratedTo
```
VirtualClass {
  CONSTRUCTOR_ID: 2951442734,
  SUBCLASS_OF_ID: 1089602301,
  className: 'InputChannel',
  classType: 'constructor',
  channelId: 1366881121,
  accessHash: Integer { value: -6922079065321462446n }
}
```

**Comment by painor** [comment]
not sure why you would use GetAllChats. if you want to get the list of dialogs you can use client.getDialogs for that.

**Comment by justinemar** [comment]
I was dealing with a chat instance of the channel i wanted instead of actual channel
