### ISSUE TITLE
Native BigInt throws casterror 

### ISSUE THREAD

**Issue by justinemar** [gram-js/gramjs#98]
The following is being thrown when using the native BigInt constructor
`CastError: Found wrong type for accessHash. expected bigInt but received -6932079065621462016. If you think this is a mistake please report it.`
// Using native BigInt expects to evaluate to true when comparing type
```
INPUTCHANNEL VirtualClass {
  CONSTRUCTOR_ID: 2951442734,
  SUBCLASS_OF_ID: 1089602301,
  className: 'InputChannel',
  classType: 'constructor',
  channelId: 1366881721,
  accessHash: -6932079065621462016n 
}

output - false (casterror)

```

I have to use the same package that the api is using when asserting access hash type
https://www.npmjs.com/package/big-integer 

which builds the expected object that the api is trying to assert

```
INPUTCHANNEL VirtualClass {
  CONSTRUCTOR_ID: 2951442734,
  SUBCLASS_OF_ID: 1089602301,
  className: 'InputChannel',
  classType: 'constructor',
  channelId: 1366881721,
  accessHash: Integer { value: -6932079065621462446n }
}
```

**Comment by painor** [comment]
should be fixed in 1.7.7
